# Phase 3 – Validation Workbook – Acquisition des données

## Objectif

Ce workbook constitue le contrôle maître de la Phase 3. Il valide progressivement la gouvernance, les acquisitions RAW, les préparations nécessaires à l’acquisition, la traçabilité et la couverture des sources avant de clôturer la phase.

Principes de validation :

- **Registry-driven** : la configuration est lue depuis le Source Registry ;
- **RAW-first** : les réponses fournisseurs sont conservées avant préparation métier ;
- **lineage explicite** : les dépendances entre datasets sont contrôlées ;
- **pas de sélection arbitraire** : les ambiguïtés sont conservées et documentées ;
- **couverture incrémentale** : une nouvelle source n’est ajoutée que si les sources déjà acquises ne couvrent pas suffisamment le besoin ;
- **validation avant clôture** : la Phase 3 n’est considérée comme terminée qu’après stabilisation de toutes les sources nécessaires.

> SRC-003A Alpha Vantage et SRC-003B Yahoo Finance sont volontairement laissées en attente dans ce workbook et seront validées ultérieurement.

# 1. Imports et chemins projet

In [3]:
from pathlib import Path
import json
import re
import sqlite3

import pandas as pd

from IPython.display import Markdown, display
from pathlib import Path
import io
import re
import zipfile

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 120)

cwd = Path.cwd().resolve()

candidates = [cwd, cwd.parent, cwd.parent.parent]
PROJECT_ROOT = next((p for p in candidates if (p / "src").is_dir()), None)

if PROJECT_ROOT is None:
    raise RuntimeError("Unable to locate project root containing src/.")

SOURCE_REGISTRY_FILE = PROJECT_ROOT / "audit" / "source_registry.xlsx"
DATABASE_FILE = PROJECT_ROOT / "database" / "sdg_investment.db"
TECHNICAL_LOG = PROJECT_ROOT / "logs" / "technical.log"

BENCHMARK_DIR = PROJECT_ROOT / "data/01_raw/benchmark"
RAW_SECURITIES_DIR = PROJECT_ROOT / "data/01_raw/securities"
PROCESSED_SECURITIES_DIR = PROJECT_ROOT / "data/02_processed/securities"
RAW_MARKET_DIR = PROJECT_ROOT / "data/01_raw/market"
RAW_MACRO_DIR = PROJECT_ROOT / "data/01_raw/macro"
RAW_FUNDAMENTALS_DIR = PROJECT_ROOT / "data/01_raw/fundamentals"

print("Project root:", PROJECT_ROOT)
print("Source Registry:", SOURCE_REGISTRY_FILE)
print("Database:", DATABASE_FILE)

Project root: C:\Users\MameBARBOSAMONTEIRO\projet01
Source Registry: C:\Users\MameBARBOSAMONTEIRO\projet01\audit\source_registry.xlsx
Database: C:\Users\MameBARBOSAMONTEIRO\projet01\database\sdg_investment.db

> Les chemins doivent être résolus depuis la racine du projet, sans dépendre du répertoire depuis lequel le notebook est lancé.

# 2. Governance – Source Registry

Le Source Registry comporte deux couches complémentaires :

- **Sources** : gouvernance des fournisseurs et sources externes ;
- **Datasets** : contrats techniques de production, dépendances, stockage et activation.

In [4]:
from IPython.display import Markdown, display

if not SOURCE_REGISTRY_FILE.exists():
    raise FileNotFoundError(
        SOURCE_REGISTRY_FILE
    )

sources_registry = pd.read_excel(
    SOURCE_REGISTRY_FILE,
    sheet_name="Sources",
)

datasets_registry = pd.read_excel(
    SOURCE_REGISTRY_FILE,
    sheet_name="Datasets",
)

sources_count = len(
    sources_registry
)

datasets_count = len(
    datasets_registry
)

print(
    "Sources:",
    sources_registry.shape,
)

print(
    "Datasets:",
    datasets_registry.shape,
)

if (
    sources_count > 0
    and datasets_count > 0
):
    status = "PASS"
    message = (
        f"Le Source Registry contient **{sources_count} sources** "
        f"et **{datasets_count} datasets configurés**. "
        "Les deux feuilles de gouvernance sont non vides."
    )
else:
    status = "FAIL"
    message = (
        f"Le Source Registry contient **{sources_count} sources** "
        f"et **{datasets_count} datasets**. "
        "Au moins une feuille de gouvernance est vide."
    )

display(
    Markdown(
        f"""

{message}

**Résultat : {status}**
"""
    )
)

Sources: (12, 7)
Datasets: (9, 15)

Le Source Registry contient **12 sources** et **9 datasets configurés**. Les deux feuilles de gouvernance sont non vides.

**Résultat : PASS**

In [5]:
def get_dataset_path(dataset_id: str) -> Path:
    """
    Resolve a dataset output path from the Dataset Registry.
    """

    matches = datasets_registry.loc[
        datasets_registry["Dataset ID"].eq(
            dataset_id
        )
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one Registry entry "
            f"for {dataset_id}; found {len(matches)}."
        )

    dataset = matches.iloc[0]

    storage_directory = str(
        dataset["Storage Directory"]
    ).strip()

    output_file_name = str(
        dataset["Output File Name"]
    ).strip()

    if not storage_directory:
        raise ValueError(
            f"{dataset_id}: Storage Directory is required."
        )

    if not output_file_name:
        raise ValueError(
            f"{dataset_id}: Output File Name is required."
        )

    return (
        PROJECT_ROOT
        / storage_directory
        / output_file_name
    )

## 2.1 Sources actives

In [6]:
source_columns = [
    col for col in [
        "Source ID", "Provider", "Reliability", "Backup Source", "Status", "Comments"
    ] if col in sources_registry.columns
]

sources_registry[source_columns]

,Source ID,Provider,Reliability,Backup Source,Status,Comments
0,SRC-001,iShares / BlackRock,High,NaN,Active,Benchmark officiel du projet utilisé comme référence d'investissement et de comparaison des performances
1,SRC-002,OpenFIGI,High,Manual Research,Active,Source principale utilisée pour construire le Securities Master et standardiser les identifiants des instruments fin...
2,SRC-003A,Alpha Vantage,Medium,SRC-003B,Active,Source secondaire utilisée comme source de backup et de validation des données de marché.
3,SRC-003B,Yahoo Finance,Medium,SRC-003A,Active,Source principale utilisée pour l'acquisition des données historiques de marché nécessaires aux analyses de performa...
4,SRC-004A,SED EDGAR,High,SRC-004B,Active,Source réglementaire structurée utilisée en priorité pour l’acquisition des données fondamentales des entreprises co...
5,SRC-004,Investor Relations Websites,High,Company Annual Reports,Active,Source générique de référence pour les données fondamentales des entreprises composant l'univers investissable.
6,SRC-005A,FRED,High,SRC-005C,Active,Source principale retenue pour les indicateurs macroéconomiques utilisés dans les analyses d'investissement.
7,SRC-005B,World Bank Data,High,SRC-005C,Active,Source de référence utilisée pour les indicateurs macroéconomiques de long terme.
8,SRC-005C,International Monetary Fund (IMF),High,SRC-005B,Active,Source complémentaire utilisée pour enrichir et valider les analyses macroéconomiques.
9,SRC-006,Swiss National Bank (SNB),High,NaN,Active,Source officielle retenue pour la conversion des prix et rendements vers la devise de reporting CHF.
10,SRC-007,"Annual Reports, Sustainability Reports & Corporate Websites",Medium,Public Sustainability Reports,Active,"Source générique utilisée pour documenter les activités économiques, les preuves d'alignement ODD et les controverse..."
11,SRC-008,"Public Controversy Sources, Annual Reports & Sustainability Reports",Medium,NaN,Active,Source utilisée pour documenter les exclusions du mandat et renforcer le contrôle de non-préjudice dans la méthodolo...

## 2.2 Datasets configurés

In [7]:
dataset_columns = [
    "Dataset ID", "Source ID", "Dataset Name", "Production Method", "Connector",
    "Access Endpoint", "Parameters", "Input Dataset IDs", "Output File Name",
    "Storage Directory", "Frequency", "Load Enabled", "Quality Enabled",
    "Chronology Enabled", "Active"
]

missing_dataset_columns = sorted(set(dataset_columns) - set(datasets_registry.columns))
print("Missing Dataset columns:", missing_dataset_columns)

datasets_registry[[c for c in dataset_columns if c in datasets_registry.columns]]

Missing Dataset columns: []

,Dataset ID,Source ID,Dataset Name,Production Method,Connector,Access Endpoint,Parameters,Input Dataset IDs,Output File Name,Storage Directory,Frequency,Load Enabled,Quality Enabled,Chronology Enabled,Active
0,DS-000,SRC-001,Benchmark Holdings,Download,NaN,https://www.blackrock.com/varnish-api/blk-one01-product-data/product-data/api/v1/get-fund-document?appType=PRODUCT_P...,{},[],benchmark_holdings.xls,data/01_raw/benchmark,Periodic,False,False,False,True
1,DS-001,SRC-001,Security Candidates,Preparation,NaN,NaN,"{\n ""worksheet"": ""Holdings"",\n ""asset_class_column"": ""Asset Class"",\n ""included_asset_classes"": [""Equity""],\n ""d...","[""DS-000""]",security_candidates.csv,data/02_processed/securities,Periodic,True,False,False,True
2,DS-002,SRC-002,OpenFIGI Mapping,API,openfigi,https://api.openfigi.com/v3/mapping,"{\n ""id_type"": ""TICKER"",\n ""id_value_column"": ""Ticker""\n}","[""DS-001""]",openfigi_mapping.csv,data/01_raw/securities,On demand,True,True,False,True
3,DS-003,SRC-002,Security Master,Preparation,NaN,NaN,{},"[""DS-001"",""DS-002""]",securities_master.csv,data/02_processed/securities,On demand,True,True,False,True
4,DS-004,SRC-003B,Market Prices,Package,yfinance,NaN,"{\n ""symbol_column"": ""yahoo_symbol"",\n ""name_column"": ""Name"",\n ""exchange_column"": ""Exchange"",\n ""period"": ""max""...","[""DS-003""]",market_prices.csv,data/01_raw/market,Daily,True,True,True,True
5,DS-005,SRC-005A,Risk Free Rate,API,fred,https://api.stlouisfed.org/fred/series/observations,"{\n ""series_id"": ""DGS3MO"",\n ""file_type"": ""json""\n}",[],risk_free_rate.csv,data/01_raw/macro,Daily,True,True,True,True
6,DS-006,SRC-005A,Macro Indicators,API,fred,https://api.stlouisfed.org/fred/series/observations,"{\n ""series_ids"": [""CPIAUCSL"", ""UNRATE"", ""FEDFUNDS""],\n ""file_type"": ""json""\n}",[],macro_indicators.csv,data/01_raw/macro,Monthly,True,True,True,True
7,DS-007,SRC-003A,Market Prices AV,API,alpha_vantage,https://www.alphavantage.co/query,"{\n ""function"": ""TIME_SERIES_DAILY"",\n ""symbol_column"": ""Ticker"",\n ""name_column"": ""Name"",\n ""location_column"": ...","[""DS-003""]",market_prices_av.csv,data/01_raw/market,Daily,True,True,True,True
8,DS-008,SRC-004A,SEC Fundamentals,API,sec_edgar,https://data.sec.gov/api/xbrl/companyfacts/,"{\n ""ticker_column"": ""Ticker""\n}","[""DS-003""]",fundamentals_sec.csv,data/01_raw/fundamentals,Quarterly,True,True,True,True

## 2.3 Intégrité Source ID

In [8]:
unknown_source_ids = (
    set(
        datasets_registry[
            "Source ID"
        ]
        .dropna()
        .astype(str)
    )
    - set(
        sources_registry[
            "Source ID"
        ]
        .dropna()
        .astype(str)
    )
)

if not unknown_source_ids:
    status = "PASS"
    message = (
        "Tous les `Source ID` utilisés dans la feuille "
        "Datasets existent dans la feuille Sources."
    )
else:
    status = "FAIL"
    message = (
        f"**{len(unknown_source_ids)} Source ID inconnu(s)** "
        "détecté(s) : "
        f"`{sorted(unknown_source_ids)}`."
    )

display(
    Markdown(
        f"""
{message}

**Résultat : {status}**
"""
    )
)

Tous les `Source ID` utilisés dans la feuille Datasets existent dans la feuille Sources.

**Résultat : PASS**

## 2.4 Production Methods et dépendances

In [9]:
print("Production Methods:")
print(datasets_registry["Production Method"].value_counts(dropna=False))
print()
print("Active datasets:")
active_mask = datasets_registry["Active"].astype(str).str.upper().isin(["TRUE", "1"])
datasets_registry.loc[active_mask, ["Dataset ID", "Dataset Name", "Production Method", "Input Dataset IDs"]]

Production Methods:
Production Method
API            5
Preparation    2
Download       1
Package        1
Name: count, dtype: int64

Active datasets:

  Dataset ID         Dataset Name Production Method    Input Dataset IDs
0     DS-000   Benchmark Holdings          Download                   []
1     DS-001  Security Candidates       Preparation           ["DS-000"]
2     DS-002     OpenFIGI Mapping               API           ["DS-001"]
3     DS-003      Security Master       Preparation  ["DS-001","DS-002"]
4     DS-004        Market Prices           Package           ["DS-003"]
5     DS-005       Risk Free Rate               API                   []
6     DS-006     Macro Indicators               API                   []
7     DS-007     Market Prices AV               API           ["DS-003"]
8     DS-008     SEC Fundamentals               API           ["DS-003"]

# 3. Gouvernance SQLite

La base SQLite conserve le registry technique et la traçabilité des exécutions. Les tables métier évoluent avec les datasets chargés et ne doivent pas être supposées à l’avance.

In [10]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        technical_tables = pd.read_sql(
            """
            SELECT name
            FROM sqlite_master
            WHERE type='table'
            ORDER BY name
            """,
            connection,
        )

    display(technical_tables)

else:
    print(
        "Database not found yet:",
        DATABASE_FILE,
    )

                     name
0         acquisition_log
1        dataset_registry
2  quality_control_result
3   quality_metric_result
4             quality_run
5       schema_migrations
6       securities_master
7    securities_unmatched
8     security_candidates

# 4. DS-000 / SRC-001 – Benchmark Holdings
On vérifie que le benchmark officiel a été acquis dans la couche RAW et on identifie automatiquement sa structure réelle pour la préparation DS-001.

In [11]:
benchmark_file = get_dataset_path(
    "DS-000"
)

if not benchmark_file.exists():
    raise FileNotFoundError(
        benchmark_file
    )

print(
    "Benchmark file:",
    benchmark_file,
)

Benchmark file: C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark\benchmark_holdings.xls

In [12]:
def inspect_file_structure(path: Path) -> dict:
    """
    Detect the physical file format from its content and inspect
    worksheet names when the detected format supports worksheets.
    """

    if not isinstance(path, Path):
        raise TypeError(
            "path must be a pathlib.Path."
        )

    if not path.exists():
        raise FileNotFoundError(path)

    if not path.is_file():
        raise ValueError(
            f"Path is not a file: {path}"
        )

    with path.open("rb") as handle:
        content = handle.read()

    result = {
        "format": None,
        "extension": path.suffix,
        "worksheets": [],
    }

    # Office Open XML / XLSX
    if content.startswith(b"PK\x03\x04"):
        result["format"] = "Office Open XML / XLSX"

        try:
            with zipfile.ZipFile(
                io.BytesIO(content)
            ) as archive:
                workbook_xml = archive.read(
                    "xl/workbook.xml"
                ).decode(
                    "utf-8",
                    errors="ignore",
                )

            result["worksheets"] = re.findall(
                r'<sheet[^>]+name="([^"]+)"',
                workbook_xml,
            )

        except (
            KeyError,
            zipfile.BadZipFile,
        ):
            pass

    # Legacy binary XLS
    elif content.startswith(
        b"\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1"
    ):
        result["format"] = "XLS Binary"

        try:
            workbook = pd.ExcelFile(path)

            result["worksheets"] = (
                workbook.sheet_names
            )

        except Exception:
            pass

    # PDF
    elif content.startswith(b"%PDF-"):
        result["format"] = "PDF"

    # Text-based formats
    else:
        text_content = content

        if text_content.startswith(
            b"\xEF\xBB\xBF"
        ):
            text_content = text_content[3:]

        try:
            text = text_content.decode(
                "utf-8"
            ).lstrip()

        except UnicodeDecodeError:
            result["format"] = (
                "Unknown binary format"
            )

        else:
            lowered = text.casefold()

            # SpreadsheetML XML
            if (
                "<ss:workbook" in lowered
                or (
                    text.startswith("<?xml")
                    and
                    "urn:schemas-microsoft-com:"
                    "office:spreadsheet"
                    in lowered
                )
            ):
                result["format"] = (
                    "SpreadsheetML XML"
                )

                result["worksheets"] = (
                    re.findall(
                        r'Worksheet\s+ss:Name="([^"]+)"',
                        text,
                    )
                )

            # Generic XML
            elif text.startswith("<?xml"):
                result["format"] = "XML"

            # HTML
            elif (
                lowered.startswith(
                    "<!doctype html"
                )
                or lowered.startswith(
                    "<html"
                )
            ):
                result["format"] = "HTML"

            else:
                result["format"] = (
                    "Unknown text format"
                )

    print(
        "Detected format:",
        result["format"],
    )

    print(
        "File extension:",
        result["extension"],
    )

    if result["worksheets"]:
        print(
            "Worksheets:",
            result["worksheets"],
        )

        print(
            "Worksheet count:",
            len(result["worksheets"]),
        )

    return result


benchmark_structure = inspect_file_structure(
    benchmark_file
)

Detected format: SpreadsheetML XML
File extension: .xls
Worksheets: ['Disclaimers', 'Holdings', 'Historical', 'Performance', 'Distributions']
Worksheet count: 5

# 5. DS-001 – Security Candidates

DS-001 est une préparation de DS-000 utilisée comme univers d’entrée pour les acquisitions nécessitant les instruments du benchmark.

In [13]:
security_candidates_file = get_dataset_path(
    "DS-001"
)

if not security_candidates_file.exists():
    raise FileNotFoundError(
        security_candidates_file
    )

security_candidates = pd.read_csv(
    security_candidates_file,
    dtype=str,
    keep_default_na=False,
)

if security_candidates.empty:
    status = "FAIL"
    message = "DS-001 est vide."

else:
    status = "PASS"
    message = (
        f"DS-001 contient "
        f"**{len(security_candidates):,} instruments**."
    )

display(
    security_candidates.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

  Ticker                  Name       Location                            Exchange Currency Asset Class
0   MRVL    MARVELL TECHNOLOGY  United States                              NASDAQ      USD      Equity
1   NVDA                NVIDIA  United States                              NASDAQ      USD      Equity
2   6669    WIWYNN CORPORATION         Taiwan               Taiwan Stock Exchange      USD      Equity
3    VWS   VESTAS WIND SYSTEMS        Denmark  Omx Nordic Exchange Copenhagen A/S      USD      Equity
4    BMY  BRISTOL MYERS SQUIBB  United States                                NYSE      USD      Equity

DS-001 contient **120 instruments**.

**Résultat : PASS**

In [14]:
exchange_summary = (
    security_candidates["Exchange"]
    .value_counts()
    .rename_axis("Exchange")
    .reset_index(name="securities")
)

print(
    "Distinct exchanges:",
    security_candidates["Exchange"].nunique(),
)

display(exchange_summary)

Distinct exchanges: 29

                                Exchange  securities
0   Hong Kong Exchanges And Clearing Ltd          21
1                                 NASDAQ          14
2                   Tokyo Stock Exchange          10
3                                   NYSE           8
4                Shenzhen Stock Exchange           7
5                Shanghai Stock Exchange           7
6       National Stock Exchange Of India           6
7         Nyse Euronext - Euronext Paris           5
8     Omx Nordic Exchange Copenhagen A/S           4
9                  London Stock Exchange           4
10                 Taiwan Stock Exchange           3
11                    SIX Swiss Exchange           3
12                     Asx - All Markets           3
13                     Nasdaq Omx Nordic           3
14             Bolsa Mexicana De Valores           3
15                                 Xetra           2
16                         Oslo Bors Asa           2
17         Korea Exchange (Stock Market)           2
18     Nyse Euronext - Euronext Brussels           2
19                    Singapore Exchange           2
20                       Bolsa De Madrid           1
21                Toronto Stock Exchange           1
22                      Wiener Boerse Ag           1
23       Nyse Euronext - Euronext Lisbon           1
24               Korea Exchange (Kosdaq)           1
25               Tel Aviv Stock Exchange           1
26           Johannesburg Stock Exchange           1
27                        Borsa Italiana           1
28                  Saudi Stock Exchange           1

# 6. DS-002 / SRC-002 – OpenFIGI Mapping RAW

On vérifie si l’acquisition OpenFIGI conserve toutes les réponses provider avant résolution dans le Security Master.

In [15]:
openfigi_file = get_dataset_path(
    "DS-002"
)

if not openfigi_file.exists():
    raise FileNotFoundError(
        openfigi_file
    )

openfigi_raw = pd.read_csv(
    openfigi_file,
    dtype=str,
    keep_default_na=False,
)

if openfigi_raw.empty:
    status = "FAIL"
    message = "DS-002 est vide."

else:
    status = "PASS"
    message = (
        f"DS-002 contient "
        f"**{len(openfigi_raw):,} lignes de réponses OpenFIGI** "
    )

display(
    openfigi_raw.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,input_position,input_index,id_type,id_value,result_position,figi,ticker,name,exch_code,market_sector,security_type,security_type_2,security_description,composite_figi,share_class_figi,provider_warning,provider_error
0,0,0,TICKER,MRVL,0.0,BBG002JV5037,MRVL,MAVEN RENOVAR VCT PLC,PO,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG000QXL3L5,BBG001SH8BP9,,
1,0,0,TICKER,MRVL,1.0,BBG006T7B0B4,MRVL,MAVEN RENOVAR VCT PLC,B3,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG006T7B097,BBG001SH8BP9,,
2,0,0,TICKER,MRVL,2.0,BBG006TBD390,MRVL,MAVEN RENOVAR VCT PLC,L3,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG006TBD381,BBG001SH8BP9,,
3,0,0,TICKER,MRVL,3.0,BBG00MXMTC99,MRVL,MARVEL BIOSCIENCES CORP,CN,Equity,Common Stock,Common Stock,MRVL,BBG00MXMTC99,BBG00MXMTCB6,,
4,0,0,TICKER,MRVL,4.0,BBG00NGL3MV9,MRVL,MARVEL BIOSCIENCES CORP,CV,Equity,Common Stock,Common Stock,MRVL,BBG00MXMTC99,BBG00MXMTCB6,,

DS-002 contient **1,992 lignes de réponses OpenFIGI**

**Résultat : PASS**

In [16]:
positions = pd.to_numeric(
    openfigi_raw["input_position"],
    errors="raise",
).astype(int)

positions_valid = positions.between(
    0,
    len(security_candidates) - 1,
).all()

expected_tickers = positions.map(
    security_candidates
    .reset_index(drop=True)["Ticker"]
)

ticker_matches = (
    openfigi_raw["id_value"]
    .str.casefold()
    .eq(
        expected_tickers
        .str.casefold()
    )
)

mismatches = int(
    (~ticker_matches).sum()
)

if positions_valid and mismatches == 0:
    status = "PASS"
    message = (
        "La lineage DS-001 → DS-002 est complète : "
        f"**{openfigi_raw['input_position'].nunique():,} "
        "Security Candidates** sont représentés et tous les "
        "`id_value` correspondent au ticker source."
    )
else:
    status = "FAIL"
    message = (
        f"Anomalie de lineage détectée : "
        f"**{mismatches:,} correspondance(s) ticker incorrecte(s)**."
    )

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

La lineage DS-001 → DS-002 est complète : **120 Security Candidates** sont représentés et tous les `id_value` correspondent au ticker source.

**Résultat : PASS**

In [17]:
figi_count = (
    openfigi_raw.loc[
        openfigi_raw["figi"].ne(""),
        "figi",
    ]
    .nunique()
)

summary = pd.Series(
    {
        "Raw mapping rows":
            len(openfigi_raw),
        "Candidate positions represented":
            openfigi_raw["input_position"].nunique(),
        "Distinct non-empty FIGIs":
            openfigi_raw.loc[
                openfigi_raw["figi"].ne(""),
                "figi",
            ].nunique(),
        "Warnings":
            openfigi_raw["provider_warning"].ne("").sum(),
        "Errors":
            openfigi_raw["provider_error"].ne("").sum(),
    }
)

display(summary)

warnings = openfigi_raw.loc[
    openfigi_raw["provider_warning"].ne(""),
    [
        "id_value",
        "provider_warning",
    ],
].drop_duplicates()

errors = openfigi_raw.loc[
    openfigi_raw["provider_error"].ne(""),
    [
        "id_value",
        "provider_error",
    ],
].drop_duplicates()

if not warnings.empty:
    print("Provider warnings:")
    display(warnings)

if not errors.empty:
    print("Provider errors:")
    display(errors)

Raw mapping rows                   1992
Candidate positions represented     120
Distinct non-empty FIGIs           1983
Warnings                              9
Errors                                0
dtype: int64

Provider warnings:

        id_value      provider_warning
450     ESSITY B  No identifier found.
1011         UU.  No identifier found.
1139      SUZLON  No identifier found.
1415       SCA B  No identifier found.
1435  HINDUNILVR  No identifier found.
1787       LUPIN  No identifier found.
1943   NESTLEIND  No identifier found.
1947   FIBRAPL14  No identifier found.
1971      COLPAL  No identifier found.

# 7. DS-003 – Security Master

On vérifie que le Security Master associe correctement les Security Candidates aux résultats OpenFIGI et documente les instruments résolus, ambigus ou non résolus.

In [18]:
security_master_file = get_dataset_path(
    "DS-003"
)

if not security_master_file.exists():
    raise FileNotFoundError(
        security_master_file
    )

security_master = pd.read_csv(
    security_master_file,
    dtype=str,
    keep_default_na=False,
)

if security_master.empty:
    status = "FAIL"
    message = "DS-003 est vide."

else:
    status = "PASS"
    message = (
        f"DS-003 contient "
        f"**{len(security_master):,} instruments**."
    )

display(
    security_master.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,Ticker,Name,Location,Exchange,Currency,Asset Class,figi,composite_figi,share_class_figi,openfigi_ticker,openfigi_name,exch_code,market_sector,security_type,security_type_2,security_description,resolution_status,resolution_rule,mapping_candidates,expected_exch_code,yahoo_symbol
0,MRVL,MARVELL TECHNOLOGY,United States,NASDAQ,USD,Equity,BBG00ZXBJ153,BBG00ZXBJ153,BBG00ZXBJ162,MRVL,MARVELL TECHNOLOGY INC,US,Equity,Common Stock,Common Stock,MRVL,RESOLVED,EXCHANGE_MATCH,1,US,MRVL
1,NVDA,NVIDIA,United States,NASDAQ,USD,Equity,BBG000BBJQV0,BBG000BBJQV0,BBG001S5TZJ6,NVDA,NVIDIA CORP,US,Equity,Common Stock,Common Stock,NVDA,RESOLVED,MARKET_SECTOR_EQUITY_EXCHANGE_MATCH,1,US,NVDA
2,6669,WIWYNN CORPORATION,Taiwan,Taiwan Stock Exchange,USD,Equity,,,,,,,,,,,AMBIGUOUS,AMBIGUOUS_MULTIPLE_FIGIS,3,TT,6669.TW
3,VWS,VESTAS WIND SYSTEMS,Denmark,Omx Nordic Exchange Copenhagen A/S,USD,Equity,BBG000BJBK53,BBG000BJBJM7,BBG001S7TVH3,VWS,VESTAS WIND SYSTEMS A/S,DC,Equity,Common Stock,Common Stock,VWS,RESOLVED,EXCHANGE_MATCH,1,DC,VWS.CO
4,BMY,BRISTOL MYERS SQUIBB,United States,NYSE,USD,Equity,BBG000DQLV23,BBG000DQLV23,BBG001S8N8J6,BMY,BRISTOL-MYERS SQUIBB CO,US,Equity,Common Stock,Common Stock,BMY,RESOLVED,MARKET_SECTOR_EQUITY_EXCHANGE_MATCH,1,US,BMY

DS-003 contient **120 instruments**.

**Résultat : PASS**

In [19]:
resolution_summary = (
    security_master["resolution_status"]
    .value_counts(dropna=False)
    .rename_axis("resolution_status")
    .reset_index(name="records")
)

resolution_summary["percentage"] = (
    resolution_summary["records"]
    / len(security_master)
    * 100
).round(2)

display(resolution_summary)

  resolution_status  records  percentage
0          RESOLVED      100       83.33
1         AMBIGUOUS       11        9.17
2        UNRESOLVED        9        7.50

In [20]:
resolution_rules = (
    security_master["resolution_rule"]
    .value_counts(dropna=False)
    .rename_axis("resolution_rule")
    .reset_index(name="records")
)

display(resolution_rules)

                       resolution_rule  records
0                       EXCHANGE_MATCH       74
1  MARKET_SECTOR_EQUITY_EXCHANGE_MATCH       25
2             AMBIGUOUS_MULTIPLE_FIGIS       11
3                   UNRESOLVED_NO_FIGI        9
4                          UNIQUE_FIGI        1

In [21]:
if "yahoo_symbol" in security_master.columns:
    yahoo_coverage = (
        security_master["yahoo_symbol"]
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        "Yahoo symbols populated:",
        yahoo_coverage,
    )

    display(
        security_master[
            [
                "Ticker",
                "Exchange",
                "resolution_status",
                "yahoo_symbol",
            ]
        ].head(20)
    )

else:
    print(
        "yahoo_symbol is not present "
        "in DS-003."
    )

Yahoo symbols populated: 120

   Ticker                              Exchange resolution_status yahoo_symbol
0    MRVL                                NASDAQ          RESOLVED         MRVL
1    NVDA                                NASDAQ          RESOLVED         NVDA
2    6669                 Taiwan Stock Exchange         AMBIGUOUS      6669.TW
3     VWS    Omx Nordic Exchange Copenhagen A/S          RESOLVED       VWS.CO
4     BMY                                  NYSE          RESOLVED          BMY
5     TSN                                  NYSE          RESOLVED          TSN
6    FSLR                                NASDAQ          RESOLVED         FSLR
7    9020                  Tokyo Stock Exchange          RESOLVED       9020.T
8    NOVN                    SIX Swiss Exchange          RESOLVED      NOVN.SW
9    1216                 Taiwan Stock Exchange         AMBIGUOUS      1216.TW
10   2015  Hong Kong Exchanges And Clearing Ltd          RESOLVED      2015.HK
11   9698  Hong Kong Exchanges And Clearing Ltd          RESOLVED      9698.HK
12    288  Hong Kong Exchanges And Clearing Ltd          RESOLVED      0288.HK
13   9866  Hong Kong Exchanges And Clearing Ltd          RESOLVED      9866.HK
14    KMB                                NASDAQ          RESOLVED          KMB
15   EQIX                                NASDAQ          RESOLVED         EQIX
16   9022                  Tokyo Stock Exchange          RESOLVED       9022.T
17   9868  Hong Kong Exchanges And Clearing Ltd          RESOLVED      9868.HK
18   REGN                                NASDAQ          RESOLVED         REGN
19    CSL                     Asx - All Markets          RESOLVED       CSL.AX

# 8. DS-004 / SRC-003B – Yahoo Finance

On vérifie la couverture et la traçabilité des données historiques de marché acquises depuis la source principale Market.

In [22]:
market_prices_file = get_dataset_path(
    "DS-004"
)

if not market_prices_file.exists():
    raise FileNotFoundError(
        market_prices_file
    )

market_prices = pd.read_csv(
    market_prices_file,
    dtype=str,
    keep_default_na=False,
)

if market_prices.empty:
    status = "FAIL"
    message = "DS-004 est vide."
else:
    status = "PASS"
    message = (
        f"DS-004 contient "
        f"**{len(market_prices):,} observations de marché**."
    )

display(
    market_prices.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,input_position,input_index,configured_symbol,resolved_symbol,symbol_resolution_status,symbol,timestamp,open,high,low,close,adj_close,volume,dividends,stock_splits
0,55,55,6160.HK,6160.HK,DIRECT,6160.HK,2018-08-08,108.0,108.19999694824219,103.0,107.0,107.0,6857700.0,0.0,0.0
1,55,55,6160.HK,6160.HK,DIRECT,6160.HK,2018-08-09,105.30000305175781,105.30000305175781,103.0,104.0999984741211,104.0999984741211,1315600.0,0.0,0.0
2,55,55,6160.HK,6160.HK,DIRECT,6160.HK,2018-08-10,104.9000015258789,104.9000015258789,103.0,104.0,104.0,1293400.0,0.0,0.0
3,55,55,6160.HK,6160.HK,DIRECT,6160.HK,2018-08-13,100.0,100.4000015258789,95.3499984741211,99.94999694824219,99.94999694824219,1954202.0,0.0,0.0
4,55,55,6160.HK,6160.HK,DIRECT,6160.HK,2018-08-14,98.19999694824219,98.19999694824219,96.0,97.9000015258789,97.9000015258789,1368702.0,0.0,0.0

DS-004 contient **647,005 observations de marché**.

**Résultat : PASS**

In [23]:
coverage = (
    market_prices[
        [
            "configured_symbol",
            "resolved_symbol",
            "symbol_resolution_status",
        ]
    ]
    .drop_duplicates()
)

display(
    coverage[
        "symbol_resolution_status"
    ]
    .value_counts()
)

configured_count = (
    coverage["configured_symbol"]
    .nunique()
)

resolved_count = (
    coverage["resolved_symbol"]
    .nunique()
)

coverage_rate = (
    resolved_count
    / configured_count
    * 100
    if configured_count
    else 0
)

status = (
    "PASS"
    if configured_count > 0
    and resolved_count == configured_count
    else "FAIL"
)

message = (
    f"DS-004 couvre **{resolved_count:,} instruments sur "
    f"{configured_count:,}**, soit **{coverage_rate:.2f} %**."
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

symbol_resolution_status
DIRECT             118
SEARCH_RESOLVED      2
Name: count, dtype: int64

DS-004 couvre **120 instruments sur 120**, soit **100.00 %**.

**Résultat : PASS**

In [24]:
search_resolved = (
    coverage.loc[
        coverage[
            "symbol_resolution_status"
        ].eq("SEARCH_RESOLVED"),
        [
            "configured_symbol",
            "resolved_symbol",
        ],
    ]
    .reset_index(drop=True)
)

if not search_resolved.empty:
    display(search_resolved)
else:
    print(
        "Aucune résolution dynamique "
        "n'a été nécessaire."
    )

  configured_symbol resolved_symbol
0           CICT.SI         C38U.SI
1           CLAR.SI         A17U.SI

In [25]:
history_coverage = (
    market_prices
    .groupby(
        "configured_symbol",
        as_index=False,
    )
    .agg(
        first_date=("timestamp", "min"),
        last_date=("timestamp", "max"),
        observations=("timestamp", "count"),
    )
    .sort_values(
        "observations",
        ascending=True,
    )
)

display(history_coverage)

    configured_symbol  first_date   last_date  observations
24            3750.HK  2025-05-20  2026-09-29           339
40          688472.SS  2023-06-09  2026-09-29           803
111            URW.PA  2023-04-14  2026-09-29           884
21          301358.SZ  2023-02-09  2026-09-29           885
48            9863.HK  2022-09-29  2026-09-29           982
49            9866.HK  2022-03-10  2026-09-29          1119
23          373220.KS  2022-01-27  2026-09-29          1139
16            2082.SR  2021-12-19  2026-09-29          1196
97               RIVN  2021-11-10  2026-09-29          1225
39          688187.SS  2021-09-07  2026-09-29          1226
15            2015.HK  2021-08-12  2026-09-29          1261
50            9868.HK  2021-07-07  2026-09-29          1287
32          600905.SS  2021-06-10  2026-09-29          1288
35          605117.SS  2021-04-20  2026-09-29          1322
83           LODHA.NS  2021-04-19  2026-09-29          1353
41          688578.SS  2020-12-02  2026-09-29          1414
51            9901.HK  2020-11-09  2026-09-29          1449
47            9698.HK  2020-11-02  2026-09-29          1454
46            9633.HK  2020-09-08  2026-09-29          1489
22            3692.HK  2019-06-14  2026-09-29          1797
18          247540.KQ  2019-03-05  2026-09-29          1858
14            1801.HK  2018-10-31  2026-09-29          1947
36            6160.HK  2018-08-08  2026-09-29          2004
20          300750.SZ  2018-06-11  2026-09-29          2015
38            6669.TW  2017-11-13  2026-09-29          2158
68        ESSITY-B.ST  2017-06-15  2026-09-29          2335
33          601127.SS  2016-06-17  2026-09-29          2498
13            1585.HK  2016-05-19  2026-09-29          2554
93          ORSTED.CO  2016-06-09  2026-09-29          2581
34          603806.SS  2014-10-08  2026-09-29          2913
7             0288.HK  2014-08-05  2026-09-29          2994
37            6446.TW  2014-03-11  2026-09-29          3068
70       FIBRAPL14.MX  2014-06-04  2026-09-29          3100
54            ARGX.BR  2014-07-10  2026-09-29          3128
116            VNA.DE  2013-07-11  2026-09-29          3356
19          300274.SZ  2011-11-02  2026-09-29          3621
114            VCX.AX  2011-12-05  2026-09-29          3751
101            SCG.AX  2010-12-13  2026-09-29          3994
109               TAL  2010-10-20  2026-09-29          4009
9             0916.HK  2009-12-10  2026-09-29          4142
91             NRP.JO  2009-04-17  2026-09-29          4445
4           002202.SZ  2007-12-26  2026-09-29          4558
64            EDPR.LS  2008-06-04  2026-09-29          4691
3           002129.SZ  2007-04-20  2026-09-29          4728
56            CICT.SI  2007-11-05  2026-09-29          4749
98            SALM.OL  2007-05-08  2026-09-29          4871
25            3898.HK  2006-12-20  2026-09-29          4875
71               FSLR  2006-11-17  2026-09-29          4995
104           SOBI.ST  2006-09-15  2026-09-29          5036
43             8951.T  2005-09-29  2026-09-29          5173
108         SUZLON.NS  2005-10-19  2026-09-29          5178
57            CLAR.SI  2005-09-30  2026-09-29          5283
78             IPN.PA  2005-12-07  2026-09-29          5324
63               DXCM  2005-04-14  2026-09-29          5399
65             ELI.BR  2005-06-20  2026-09-29          5448
17            2319.HK  2004-06-10  2026-09-29          5510
62                DLR  2004-10-29  2026-09-29          5513
52               ALNY  2004-06-01  2026-09-29          5618
11            1093.HK  2003-05-13  2026-09-29          5792
89       NESTLEIND.NS  2002-08-12  2026-09-29          6003
58          COLPAL.NS  2002-07-01  2026-09-29          6033
84           LUPIN.NS  2001-09-10  2026-09-29          6243
105           SOON.SW  2001-09-24  2026-09-29          6337
45             9022.T  2001-01-04  2026-09-29          6408
42             8113.T  2001-01-01  2026-09-29          6411
5             0066.HK  2000-10-09  2026-09-29          6468
73            GMAB.CO  2000-10-20  2026-09-29          6545
67               EQIX  2000-08-11  2026-09-29          6571
87               MRVL  2000-06-30  2026-09-29          6600
77               INSM  2000-06-01  2026-09-29          6621
12            1216.TW  2000-01-04  2026-09-29          6654
118            VWS.CO  2000-05-10  2026-09-29          6662
61          DEMANT.CO  2000-05-08  2026-09-29          6664
1             0012.HK  2000-01-04  2026-09-29          6667
69                 EW  2000-03-27  2026-09-29          6667
10            1044.HK  2000-01-04  2026-09-29          6667
8             0322.HK  2000-01-04  2026-09-29          6667
26             4151.T  2000-01-04  2026-09-29          6670
31             4568.T  2000-01-04  2026-09-29          6670
27             4507.T  2000-01-04  2026-09-29          6670
28             4519.T  2000-01-04  2026-09-29          6670
29             4523.T  2000-01-04  2026-09-29          6670
30             4543.T  2000-01-04  2026-09-29          6670
44             9020.T  2000-01-04  2026-09-29          6670
6           010120.KS  2000-01-04  2026-09-29          6684
66            ENLT.TA  2000-02-01  2026-09-29          6711
115            VER.VI  2000-01-03  2026-09-29          6763
86            MOWI.OL  2000-01-03  2026-09-29          6780
103        SIGMAFA.MX  2000-01-03  2026-09-29          6785
100          SCA-B.ST  2000-01-03  2026-09-29          6785
79         KIMBERA.MX  2000-01-03  2026-09-29          6785
106           SPSN.SW  2000-01-04  2026-09-29          6786
112              UTHR  1999-06-17  2026-09-29          6863
53             ANA.MC  2000-01-03  2026-09-29          6867
59             COV.PA  2000-01-03  2026-09-29          6871
0           000895.SZ  1998-12-10  2026-09-29          6882
92               NVDA  1999-01-22  2026-09-29          6964
75             HOT.DE  1998-07-22  2026-09-29          7212
99             SAP.TO  1997-10-24  2026-09-29          7334
88               NBIX  1996-05-23  2026-09-29          7636
74      HINDUNILVR.NS  1996-01-01  2026-09-29          7728
90            NOVN.SW  1995-04-03  2026-09-29          8027
95             REC.MI  1995-03-24  2026-09-29          8078
107               SUI  1993-12-09  2026-09-29          8256
60             CSL.AX  1994-05-31  2026-09-29          8263
76               INCY  1993-11-04  2026-09-29          8280
2           001979.SZ  1993-06-07  2026-09-29          8320
82              LI.PA  1992-07-09  2026-09-29          8823
72             GFC.PA  1992-07-08  2026-09-29          8824
117              VRTX  1991-07-24  2026-09-29          8859
96               REGN  1991-04-02  2026-09-29          8938
113              UU.L  1989-12-11  2026-09-29          9431
94             PSON.L  1988-07-01  2026-09-29          9807
102            SGRO.L  1988-07-01  2026-09-29          9807
81             LAND.L  1988-07-01  2026-09-29          9807
80                KMB  1980-03-17  2026-09-29         11729
110               TSN  1980-03-17  2026-09-29         11729
85                MAS  1980-03-17  2026-09-29         11729
119                WY  1973-05-03  2026-09-29         13465
55                BMY  1972-06-01  2026-09-29         13695

In [46]:
identity_review = (
    security_master[
        [
            "Ticker",
            "Name",
            "Exchange",
            "yahoo_symbol",
        ]
    ]
    .merge(
        history_coverage[
            [
                "configured_symbol",
                "first_date",
                "last_date",
                "observations",
            ]
        ],
        left_on="yahoo_symbol",
        right_on="configured_symbol",
        how="left",
    )
    .drop(
        columns="configured_symbol"
    )
    .sort_values(
        [
            "Exchange",
            "Ticker",
        ]
    )
    .reset_index(
        drop=True
    )
)

display(identity_review)

         Ticker                                Name                              Exchange   yahoo_symbol  first_date   last_date  observations
0           CSL                                 CSL                     Asx - All Markets         CSL.AX  1994-05-31  2026-09-29        8263.0
1           SCG                       SCENTRE GROUP                     Asx - All Markets         SCG.AX  2010-12-13  2026-09-29        3994.0
2           VCX                    VICINITY CENTRES                     Asx - All Markets         VCX.AX  2011-12-05  2026-09-29        3751.0
3           ANA                             ACCIONA                       Bolsa De Madrid         ANA.MC  2000-01-03  2026-09-29        6867.0
4     FIBRAPL14       PROLOGIS PROPERTY MEXICO REIT             Bolsa Mexicana De Valores   FIBRAPL14.MX  2014-06-04  2026-09-29        3100.0
5       KIMBERA    KIMBERLY-CLARK DE MEXICO CLASS A             Bolsa Mexicana De Valores     KIMBERA.MX  2000-01-03  2026-09-29        6785.0
6       SIGMAFA                              ALFA A             Bolsa Mexicana De Valores     SIGMAFA.MX  2000-01-03  2026-09-29        6785.0
7           REC  RECORDATI INDUSTRIA CHIMICA E FARM                        Borsa Italiana         REC.MI  1995-03-24  2026-09-29        8078.0
8          1044          HENGAN INTERNATIONAL GROUP  Hong Kong Exchanges And Clearing Ltd        1044.HK  2000-01-04  2026-09-29        6667.0
9          1093           CSPC PHARMACEUTICAL GROUP  Hong Kong Exchanges And Clearing Ltd        1093.HK  2003-05-13  2026-09-29        5792.0
10           12      HENDERSON LAND DEVELOPMENT LTD  Hong Kong Exchanges And Clearing Ltd          12.HK         NaN         NaN           NaN
11         1585                YADEA GROUP HOLDINGS  Hong Kong Exchanges And Clearing Ltd        1585.HK  2016-05-19  2026-09-29        2554.0
12         1801                  INNOVENT BIOLOGICS  Hong Kong Exchanges And Clearing Ltd        1801.HK  2018-10-31  2026-09-29        1947.0
13         2015                     LI AUTO CLASS A  Hong Kong Exchanges And Clearing Ltd        2015.HK  2021-08-12  2026-09-29        1261.0
14         2319             CHINA MENGNIU DAIRY LTD  Hong Kong Exchanges And Clearing Ltd        2319.HK  2004-06-10  2026-09-29        5510.0
15          288                            WH GROUP  Hong Kong Exchanges And Clearing Ltd         288.HK         NaN         NaN           NaN
16          322    TINGYI (CAYMAN ISLANDS) HOLDINGS  Hong Kong Exchanges And Clearing Ltd         322.HK         NaN         NaN           NaN
17         3692         HANSOH PHARMACEUTICAL GROUP  Hong Kong Exchanges And Clearing Ltd        3692.HK  2019-06-14  2026-09-29        1797.0
18         3750  CONTEMPORARY AMPEREX TECHNOLOGY CL  Hong Kong Exchanges And Clearing Ltd        3750.HK  2025-05-20  2026-09-29         339.0
19         3898   ZHUZHOU CRRC TIMES ELECTRIC LTD H  Hong Kong Exchanges And Clearing Ltd        3898.HK  2006-12-20  2026-09-29        4875.0
20         6160                  BEONE MEDICINES AG  Hong Kong Exchanges And Clearing Ltd        6160.HK  2018-08-08  2026-09-29        2004.0
21           66                     MTR CORPORATION  Hong Kong Exchanges And Clearing Ltd          66.HK         NaN         NaN           NaN
22          916        CHINA LONGYUAN POWER GROUP H  Hong Kong Exchanges And Clearing Ltd         916.HK         NaN         NaN           NaN
23         9633                 NONGFU SPRING LTD H  Hong Kong Exchanges And Clearing Ltd        9633.HK  2020-09-08  2026-09-29        1489.0
24         9698                GDS HOLDINGS CLASS A  Hong Kong Exchanges And Clearing Ltd        9698.HK  2020-11-02  2026-09-29        1454.0
25         9863   ZHEJIANG LEAPMOTOR TECHNOLOGY LTD  Hong Kong Exchanges And Clearing Ltd        9863.HK  2022-09-29  2026-09-29         982.0
26         9866                         NIO CLASS A  Hong Kong Exchanges And Clearing Ltd        9866.HK  2022-03-10  2026-09-29        1119.0
27         9868                   XPENG CLASS A INC  Hong Kong Exchanges And Clearing Ltd        9868.HK  2021-07-07  2026-09-29        1287.0
28         9901  NEW ORIENTAL EDUCATION & TECHNOLOG  Hong Kong Exchanges And Clearing Ltd        9901.HK  2020-11-09  2026-09-29        1449.0
29          NRP                     NEPI ROCKCASTLE           Johannesburg Stock Exchange         NRP.JO  2009-04-17  2026-09-29        4445.0
30       247540                       ECOPRO BM LTD               Korea Exchange (Kosdaq)      247540.KQ  2019-03-05  2026-09-29        1858.0
31       010120                     LS ELECTRIC LTD         Korea Exchange (Stock Market)      010120.KS  2000-01-04  2026-09-29        6684.0
32       373220              LG ENERGY SOLUTION LTD         Korea Exchange (Stock Market)      373220.KS  2022-01-27  2026-09-29        1139.0
33         LAND      LAND SECURITIES GROUP REIT PLC                 London Stock Exchange         LAND.L  1988-07-01  2026-09-29        9807.0
34         PSON                         PEARSON PLC                 London Stock Exchange         PSON.L  1988-07-01  2026-09-29        9807.0
35         SGRO                      SEGRO REIT PLC                 London Stock Exchange         SGRO.L  1988-07-01  2026-09-29        9807.0
36          UU.          UNITED UTILITIES GROUP PLC                 London Stock Exchange          UU..L         NaN         NaN           NaN
37         ALNY             ALNYLAM PHARMACEUTICALS                                NASDAQ           ALNY  2004-06-01  2026-09-29        5618.0
38         DXCM                          DEXCOM INC                                NASDAQ           DXCM  2005-04-14  2026-09-29        5399.0
39         EQIX                        EQUINIX REIT                                NASDAQ           EQIX  2000-08-11  2026-09-29        6571.0
40         FSLR                         FIRST SOLAR                                NASDAQ           FSLR  2006-11-17  2026-09-29        4995.0
41         INCY                         INCYTE CORP                                NASDAQ           INCY  1993-11-04  2026-09-29        8280.0
42         INSM                              INSMED                                NASDAQ           INSM  2000-06-01  2026-09-29        6621.0
43          KMB                      KIMBERLY CLARK                                NASDAQ            KMB  1980-03-17  2026-09-29       11729.0
44         MRVL                  MARVELL TECHNOLOGY                                NASDAQ           MRVL  2000-06-30  2026-09-29        6600.0
45         NBIX              NEUROCRINE BIOSCIENCES                                NASDAQ           NBIX  1996-05-23  2026-09-29        7636.0
46         NVDA                              NVIDIA                                NASDAQ           NVDA  1999-01-22  2026-09-29        6964.0
47         REGN           REGENERON PHARMACEUTICALS                                NASDAQ           REGN  1991-04-02  2026-09-29        8938.0
48         RIVN       RIVIAN AUTOMOTIVE INC CLASS A                                NASDAQ           RIVN  2021-11-10  2026-09-29        1225.0
49         UTHR                 UNITED THERAPEUTICS                                NASDAQ           UTHR  1999-06-17  2026-09-29        6863.0
50         VRTX              VERTEX PHARMACEUTICALS                                NASDAQ           VRTX  1991-07-24  2026-09-29        8859.0
51          BMY                BRISTOL MYERS SQUIBB                                  NYSE            BMY  1972-06-01  2026-09-29       13695.0
52          DLR           DIGITAL REALTY TRUST REIT                                  NYSE            DLR  2004-10-29  2026-09-29        5513.0
53           EW                EDWARDS LIFESCIENCES                                  NYSE             EW  2000-03-27  2026-09-29        6667.0
54          MAS                               MASCO                                  NYSE            MAS  1980-03-17  2026-09-29       11729.0
55          SUI            SUN COMMUNITIES REIT INC                                  NYSE            SUI  1993-12-09  2026-09-29        8256.0
56          TAL       TAL EDUCATION GROUP ADR REPTG                                  NYSE            TAL  2010-10-20  2026-09-29        4009.0
57          TSN             TYSON FOODS INC CLASS A                                  NYSE            TSN  1980-03-17  2026-09-29       11729.0
58           WY                   WEYERHAEUSER REIT                                  NYSE             WY  1973-05-03  2026-09-29       13465.0
59     ESSITY B                      ESSITY CLASS B                     Nasdaq Omx Nordic    ESSITY B.ST         NaN         NaN           NaN
60        SCA B                 SVENSKA CELLULOSA B                     Nasdaq Omx Nordic       SCA B.ST         NaN         NaN           NaN
61         SOBI            SWEDISH ORPHAN BIOVITRUM                     Nasdaq Omx Nordic        SOBI.ST  2006-09-15  2026-09-29        5036.0
62       COLPAL         COLGATE PALMOLIVE INDIA LTD      National Stock Exchange Of India      COLPAL.NS  2002-07-01  2026-09-29        6033.0
63   HINDUNILVR              HINDUSTAN UNILEVER LTD      National Stock Exchange Of India  HINDUNILVR.NS  1996-01-01  2026-09-29        7728.0
64        LODHA                LODHA DEVELOPERS LTD      National Stock Exchange Of India       LODHA.NS  2021-04-19  2026-09-29        1353.0
65        LUPIN                               LUPIN      National Stock Exchange Of India       LUPIN.NS  2001-09-10  2026-09-29        6243.0
66    NESTLEIND                    NESTLE INDIA LTD      National Stock Exchange Of India   NESTLEIND.NS  2002-08-12  2026-09-29        6003.0
67       SUZLON                       SUZLON ENERGY      National Stock Exchange Of India      SUZLON.NS  2005-10-19  2026-09-29        5178.0
68         ARGX                              ARGENX     Nyse Euronext - Euronext Brussels        ARGX.BR  2014-07-10  2026-09-29        3128.0
69          ELI                       ELIA GROUP SA     Nyse Euronext - Euronext Brussels         ELI.BR  2005-06-20  2026-09-29        5448.0
70         EDPR                   EDP RENEWABLES SA       Nyse Euronext - Euronext Lisbon        EDPR.LS  2008-06-04  2026-09-29        4691.0
71          COV                          COVIVIO SA        Nyse Euronext - Euronext Paris         COV.PA  2000-01-03  2026-09-29        6871.0
72          GFC                           GECINA SA        Nyse Euronext - Euronext Paris         GFC.PA  1992-07-08  2026-09-29        8824.0
73          IPN                            IPSEN SA        Nyse Euronext - Euronext Paris         IPN.PA  2005-12-07  2026-09-29        5324.0
74           LI                   KLEPIERRE REIT SA        Nyse Euronext - Euronext Paris          LI.PA  1992-07-09  2026-09-29        8823.0
75          URW    UNIBAIL RODAMCO WE STAPLED UNITS        Nyse Euronext - Euronext Paris         URW.PA  2023-04-14  2026-09-29         884.0
76       DEMANT                              DEMANT    Omx Nordic Exchange Copenhagen A/S      DEMANT.CO  2000-05-08  2026-09-29        6664.0
77         GMAB                              GENMAB    Omx Nordic Exchange Copenhagen A/S        GMAB.CO  2000-10-20  2026-09-29        6545.0
78       ORSTED                          ORSTED A/S    Omx Nordic Exchange Copenhagen A/S      ORSTED.CO  2016-06-09  2026-09-29        2581.0
79          VWS                 VESTAS WIND SYSTEMS    Omx Nordic Exchange Copenhagen A/S         VWS.CO  2000-05-10  2026-09-29        6662.0
80         MOWI                                MOWI                         Oslo Bors Asa        MOWI.OL  2000-01-03  2026-09-29        6780.0
81         SALM                              SALMAR                         Oslo Bors Asa        SALM.OL  2007-05-08  2026-09-29        4871.0
82         NOVN                         NOVARTIS AG                    SIX Swiss Exchange        NOVN.SW  1995-04-03  2026-09-29        8027.0
83         SOON                   SONOVA HOLDING AG                    SIX Swiss Exchange        SOON.SW  2001-09-24  2026-09-29        6337.0
84         SPSN                 SWISS PRIME SITE AG                    SIX Swiss Exchange        SPSN.SW  2000-01-04  2026-09-29        6786.0
85         2082                       ACWA POWER CO                  Saudi Stock Exchange       2082.SAU         NaN         NaN           NaN
86       600905  CHINA THREE GORGES RENEWABLES(GROU               Shanghai Stock Exchange      600905.SS  2021-06-10  2026-09-29        1288.0
87       601127                       SERES GROUP A               Shanghai Stock Exchange      601127.SS  2016-06-17  2026-09-29        2498.0
88       603806  HANGZHOU FIRST APPLIED MATERIAL LT               Shanghai Stock Exchange      603806.SS  2014-10-08  2026-09-29        2913.0
89       605117       NINGBO DEYE TECHNOLOGY CORP A               Shanghai Stock Exchange      605117.SS  2021-04-20  2026-09-29        1322.0
90       688187   ZHUZHOU CRRC TIMES ELECTRIC LTD A               Shanghai Stock Exchange      688187.SS  2021-09-07  2026-09-29        1226.0
91       688472                     CSI SOLAR LTD A               Shanghai Stock Exchange      688472.SS  2023-06-09  2026-09-29         803.0
92       688578  SHANGHAI ALLIST PHARMACEUTICALS LT               Shanghai Stock Exchange      688578.SS  2020-12-02  2026-09-29        1414.0
93       000895  HENAN SHUANGHUI INVESTMENT & DEVEL               Shenzhen Stock Exchange      000895.SZ  1998-12-10  2026-09-29        6882.0
94       001979   CHINA MERCHANTS SHEKOU INDUSTRIAL               Shenzhen Stock Exchange      001979.SZ  1993-06-07  2026-09-29        8320.0
95       002129  TCL ZHONGHUAN RENEWABLE ENERGY TEC               Shenzhen Stock Exchange      002129.SZ  2007-04-20  2026-09-29        4728.0
96       002202   GOLDWIND SCIENCE&TECHNOLOGY LTD A               Shenzhen Stock Exchange      002202.SZ  2007-12-26  2026-09-29        4558.0
97       300274          SUNGROW POWER SUPPLY LTD A               Shenzhen Stock Exchange      300274.SZ  2011-11-02  2026-09-29        3621.0
98       300750   CONTEMPORARY AMPEREX TECHNOLOGY A               Shenzhen Stock Exchange      300750.SZ  2018-06-11  2026-09-29        2015.0
99       301358  HUNAN YUNENG NEW ENERGY BATTERY MA               Shenzhen Stock Exchange      301358.SZ  2023-02-09  2026-09-29         885.0
100        CICT  CAPITALAND INTEGRATED COMMERCIAL T                    Singapore Exchange        CICT.SI  2007-11-05  2026-09-29        4749.0
101        CLAR            CAPITALAND ASCENDAS REIT                    Singapore Exchange        CLAR.SI  2005-09-30  2026-09-29        5283.0
102        1216           UNI-PRESIDENT ENTERPRISES                 Taiwan Stock Exchange        1216.TW  2000-01-04  2026-09-29        6654.0
103        6446                      PHARMAESSENTIA                 Taiwan Stock Exchange        6446.TW  2014-03-11  2026-09-29        3068.0
104        6669                  WIWYNN CORPORATION                 Taiwan Stock Exchange        6669.TW  2017-11-13  2026-09-29        2158.0
105        ENLT            ENLIGHT RENEWABLE ENERGY               Tel Aviv Stock Exchange        ENLT.TA  2000-02-01  2026-09-29        6711.0
106        4151                     KYOWA KIRIN LTD                  Tokyo Stock Exchange         4151.T  2000-01-04  2026-09-29        6670.0
107        4507                            SHIONOGI                  Tokyo Stock Exchange         4507.T  2000-01-04  2026-09-29        6670.0
108        4519           CHUGAI PHARMACEUTICAL LTD                  Tokyo Stock Exchange         4519.T  2000-01-04  2026-09-29        6670.0
109        4523                               EISAI                  Tokyo Stock Exchange         4523.T  2000-01-04  2026-09-29        6670.0
110        4543                              TERUMO                  Tokyo Stock Exchange         4543.T  2000-01-04  2026-09-29        6670.0
111        4568                  DAIICHI SANKYO LTD                  Tokyo Stock Exchange         4568.T  2000-01-04  2026-09-29        6670.0
112        8113                            UNICHARM                  Tokyo Stock Exchange         8113.T  2001-01-01  2026-09-29        6411.0
113        8951           NIPPON BUILDING FUND REIT                  Tokyo Stock Exchange         8951.T  2005-09-29  2026-09-29        5173.0
114        9020                  EAST JAPAN RAILWAY                  Tokyo Stock Exchange         9020.T  2000-01-04  2026-09-29        6670.0
115        9022               CENTRAL JAPAN RAILWAY                  Tokyo Stock Exchange         9022.T  2001-01-04  2026-09-29        6408.0
116         SAP                              SAPUTO                Toronto Stock Exchange         SAP.TO  1997-10-24  2026-09-29        7334.0
117         VER                          VERBUND AG                      Wiener Boerse Ag         VER.VI  2000-01-03  2026-09-29        6763.0
118         HOT                         HOCHTIEF AG                                 Xetra         HOT.DE  1998-07-22  2026-09-29        7212.0
119         VNA                          VONOVIA SE                                 Xetra         VNA.DE  2013-07-11  2026-09-29        3356.0

# 9. DS-007 / SRC-003A – Alpha Vantage

On vérifie que l’acquisition Alpha Vantage produit les données de marché attendues pour les instruments couverts, tout en identifiant clairement les instruments non couverts ou en erreur.

# 10. SRC-004A / DS-008 – SEC EDGAR Fundamentals RAW

## Objectif

Valider l’acquisition source-faithful de tous les Company Facts XBRL disponibles pour les titres reconnus par SEC EDGAR.

DS-008 ne sélectionne pas encore Revenue, EBIT, EBITDA, Net Income, Total Assets, Debt, Cash, FCF ou Shares Outstanding. Ces transformations appartiendront à une future préparation Fundamentals.

In [20]:
sec_path = RAW_FUNDAMENTALS_DIR / "fundamentals_sec.csv"
sec_raw = pd.read_csv(sec_path, dtype=str, keep_default_na=False)

print("SEC RAW shape:", sec_raw.shape)
print("Columns:", sec_raw.columns.tolist())

SEC RAW shape: (586897, 20)
Columns: ['input_position', 'input_index', 'input_ticker', 'cik', 'entity_name', 'taxonomy', 'concept', 'label', 'description', 'unit', 'start', 'end', 'value', 'accession', 'fiscal_year', 'fiscal_period', 'form', 'filed', 'frame', 'provider_status']

## 10.1 Contrat RAW

In [21]:
SEC_EXPECTED_COLUMNS = [
    "input_position", "input_index", "input_ticker", "cik", "entity_name",
    "taxonomy", "concept", "label", "description", "unit", "start", "end",
    "value", "accession", "fiscal_year", "fiscal_period", "form", "filed",
    "frame", "provider_status"
]

print("Column contract valid:", list(sec_raw.columns) == SEC_EXPECTED_COLUMNS)
print("Column count:", len(sec_raw.columns))

Column contract valid: True
Column count: 20

## 10.2 Provider status

In [22]:
sec_status = (
    sec_raw["provider_status"]
    .value_counts(dropna=False)
    .rename_axis("provider_status")
    .reset_index(name="records")
)
sec_status["percentage"] = (sec_status["records"] / len(sec_raw) * 100).round(4)
sec_status

    provider_status  records  percentage
0           success   586809      99.985
1  ticker_not_found       88       0.015

## 10.3 Couverture société

La couverture Fundamentals est mesurée au niveau des sociétés, et non au nombre de faits XBRL.

In [23]:
sec_covered_tickers = set(sec_raw.loc[sec_raw["cik"].ne(""), "input_ticker"])
sec_not_found_tickers = set(sec_raw.loc[sec_raw["provider_status"].eq("ticker_not_found"), "input_ticker"])

sec_coverage = pd.Series({
    "Security Master securities": security_master["Ticker"].nunique(),
    "SEC-covered securities": len(sec_covered_tickers),
    "Ticker not found": len(sec_not_found_tickers),
    "Coverage (%)": round(len(sec_covered_tickers) / security_master["Ticker"].nunique() * 100, 2),
})
sec_coverage

Security Master securities    120.00
SEC-covered securities         32.00
Ticker not found               88.00
Coverage (%)                   26.67
dtype: float64

## 10.4 Lineage DS-003 → DS-008

In [24]:
sec_lineage = sec_raw[["input_position", "input_ticker"]].drop_duplicates().copy()
sec_lineage["input_position_int"] = pd.to_numeric(sec_lineage["input_position"], errors="raise").astype(int)

valid_positions = sec_lineage["input_position_int"].between(0, len(security_master) - 1).all()
master_ticker_by_position = security_master.reset_index(drop=True)["Ticker"]
sec_lineage["master_ticker"] = sec_lineage["input_position_int"].map(master_ticker_by_position)
sec_lineage["ticker_match"] = (
    sec_lineage["input_ticker"].str.casefold()
    == sec_lineage["master_ticker"].str.casefold()
)

print("Input positions valid:", valid_positions)
print("Ticker lineage matches:", sec_lineage["ticker_match"].all())
print("Lineage mismatches:", int((~sec_lineage["ticker_match"]).sum()))

Input positions valid: True
Ticker lineage matches: True
Lineage mismatches: 0

## 10.5 CIK et identité des entités

In [25]:
sec_facts = sec_raw[sec_raw["provider_status"].eq("success")].copy()

sec_identity = (
    sec_facts.groupby("input_ticker")
    .agg(
        distinct_ciks=("cik", "nunique"),
        cik=("cik", "first"),
        entity_name=("entity_name", "first"),
        fact_records=("concept", "size"),
    )
    .reset_index()
    .sort_values("fact_records", ascending=False)
)

print("SEC-covered tickers:", len(sec_identity))
print("Tickers with multiple CIKs:", int(sec_identity["distinct_ciks"].gt(1).sum()))
sec_identity

SEC-covered tickers: 32
Tickers with multiple CIKs: 0

   input_ticker  distinct_ciks         cik                       entity_name  fact_records
2           BMY              1  0000014272      BRISTOL-MYERS SQUIBB COMPANY         37651
8          EQIX              1  0001101239                     EQUINIX, INC.         32323
10         FSLR              1  0001274494                 First Solar, Inc.         31775
17          MAS              1  0000062996                 Masco Corporation         28701
21         NVDA              1  0001045810                       NVIDIA CORP         27281
9            EW              1  0001099800  Edwards Lifesciences Corporation         26992
4           CSL              1  0000790051   CARLISLE COMPANIES INCORPORATED         26987
30         VRTX              1  0000875320   VERTEX PHARMACEUTICALS INC / MA         25970
5           DLR              1  0001297996        DIGITAL REALTY TRUST, INC.         24663
25          SUI              1  0000912593              SUN COMMUNITIES, INC         24632
27          TSN              1  0000100493                 TYSON FOODS, INC.         23586
14          KMB              1  0000055785        KIMBERLY-CLARK CORPORATION         23575
31           WY              1  0000106535              WEYERHAEUSER COMPANY         22634
3          CLAR              1  0000913277                CLARUS CORPORATION         21700
28         UTHR              1  0001082554   United Therapeutics Corporation         20826
6          DXCM              1  0001093557                      DEXCOM, INC.         20371
20          NRP              1  0001171486      NATURAL RESOURCE PARTNERS LP         20174
12         INCY              1  0000879169                INCYTE CORPORATION         19702
22         REGN              1  0000872589   REGENERON PHARMACEUTICALS, INC.         19466
13         INSM              1  0001104506                        INSMED INC         17723
0          ALNY              1  0001178670     ALNYLAM PHARMACEUTICALS, INC.         16818
19         NBIX              1  0000914475        NEUROCRINE BIOSCIENCES INC         16543
15         LAND              1  0001495240               GLADSTONE LAND CORP         13652
18         MRVL              1  0001835632           MARVELL TECHNOLOGY, INC          8423
26          TAL              1  0001499620               TAL Education Group          6788
23         RIVN              1  0001874178      Rivian Automotive, Inc. / DE          6215
24          SAP              1  0001000184                            SAP SE          5828
1          ARGX              1  0001697862                         ARGENX SE          5776
16           LI              1  0001791706                      Li Auto Inc.          4133
11         GMAB              1  0001434265                        Genmab A/S          3748
7          ENLT              1  0001922641     Enlight Renewable Energy Ltd.          2097
29          VCX              1  0001867090     Fundrise Innovation Fund, LLC            56

## 10.6 Revue benchmark → entité SEC

Ce contrôle doit être revu humainement afin d’identifier les collisions de ticker éventuelles. Une correspondance ticker → CIK n’est pas automatiquement considérée comme une validation définitive de l’identité.

In [26]:
sec_identity_review = (
    security_master[["Ticker", "Name", "Location", "Exchange"]]
    .merge(
        sec_identity[["input_ticker", "cik", "entity_name", "fact_records"]],
        left_on="Ticker",
        right_on="input_ticker",
        how="left",
    )
)
sec_identity_review["sec_covered"] = sec_identity_review["cik"].notna()
sec_identity_review.loc[sec_identity_review["sec_covered"]].reset_index(drop=True)

   Ticker                            Name        Location                            Exchange input_ticker         cik                       entity_name  fact_records  sec_covered
0    MRVL              MARVELL TECHNOLOGY   United States                              NASDAQ         MRVL  0001835632           MARVELL TECHNOLOGY, INC        8423.0         True
1    NVDA                          NVIDIA   United States                              NASDAQ         NVDA  0001045810                       NVIDIA CORP       27281.0         True
2     BMY            BRISTOL MYERS SQUIBB   United States                                NYSE          BMY  0000014272      BRISTOL-MYERS SQUIBB COMPANY       37651.0         True
3     TSN         TYSON FOODS INC CLASS A   United States                                NYSE          TSN  0000100493                 TYSON FOODS, INC.       23586.0         True
4    FSLR                     FIRST SOLAR   United States                              NASDAQ         FSLR  0001274494                 First Solar, Inc.       31775.0         True
5     KMB                  KIMBERLY CLARK   United States                              NASDAQ          KMB  0000055785        KIMBERLY-CLARK CORPORATION       23575.0         True
6    EQIX                    EQUINIX REIT   United States                              NASDAQ         EQIX  0001101239                     EQUINIX, INC.       32323.0         True
7    REGN       REGENERON PHARMACEUTICALS   United States                              NASDAQ         REGN  0000872589   REGENERON PHARMACEUTICALS, INC.       19466.0         True
8     CSL                             CSL       Australia                   Asx - All Markets          CSL  0000790051   CARLISLE COMPANIES INCORPORATED       26987.0         True
9    VRTX          VERTEX PHARMACEUTICALS   United States                              NASDAQ         VRTX  0000875320   VERTEX PHARMACEUTICALS INC / MA       25970.0         True
10     WY               WEYERHAEUSER REIT   United States                                NYSE           WY  0000106535              WEYERHAEUSER COMPANY       22634.0         True
11    DLR       DIGITAL REALTY TRUST REIT   United States                                NYSE          DLR  0001297996        DIGITAL REALTY TRUST, INC.       24663.0         True
12    MAS                           MASCO   United States                                NYSE          MAS  0000062996                 Masco Corporation       28701.0         True
13    SAP                          SAPUTO          Canada              Toronto Stock Exchange          SAP  0001000184                            SAP SE        5828.0         True
14   RIVN   RIVIAN AUTOMOTIVE INC CLASS A   United States                              NASDAQ         RIVN  0001874178      Rivian Automotive, Inc. / DE        6215.0         True
15     EW            EDWARDS LIFESCIENCES   United States                                NYSE           EW  0001099800  Edwards Lifesciences Corporation       26992.0         True
16   DXCM                      DEXCOM INC   United States                              NASDAQ         DXCM  0001093557                      DEXCOM, INC.       20371.0         True
17    TAL   TAL EDUCATION GROUP ADR REPTG           China                                NYSE          TAL  0001499620               TAL Education Group        6788.0         True
18   ARGX                          ARGENX         Belgium   Nyse Euronext - Euronext Brussels         ARGX  0001697862                         ARGENX SE        5776.0         True
19   ALNY         ALNYLAM PHARMACEUTICALS   United States                              NASDAQ         ALNY  0001178670     ALNYLAM PHARMACEUTICALS, INC.       16818.0         True
20   INCY                     INCYTE CORP   United States                              NASDAQ         INCY  0000879169                INCYTE CORPORATION       19702.0         True
21   GMAB                          GENMAB         Denmark  Omx Nordic Exchange Copenhagen A/S         GMAB  0001434265                        Genmab A/S        3748.0         True
22   NBIX          NEUROCRINE BIOSCIENCES   United States                              NASDAQ         NBIX  0000914475        NEUROCRINE BIOSCIENCES INC       16543.0         True
23     LI               KLEPIERRE REIT SA          France      Nyse Euronext - Euronext Paris           LI  0001791706                      Li Auto Inc.        4133.0         True
24   UTHR             UNITED THERAPEUTICS   United States                              NASDAQ         UTHR  0001082554   United Therapeutics Corporation       20826.0         True
25    SUI        SUN COMMUNITIES REIT INC   United States                                NYSE          SUI  0000912593              SUN COMMUNITIES, INC       24632.0         True
26   CLAR        CAPITALAND ASCENDAS REIT       Singapore                  Singapore Exchange         CLAR  0000913277                CLARUS CORPORATION       21700.0         True
27   ENLT        ENLIGHT RENEWABLE ENERGY          Israel             Tel Aviv Stock Exchange         ENLT  0001922641     Enlight Renewable Energy Ltd.        2097.0         True
28    NRP                 NEPI ROCKCASTLE    South Africa         Johannesburg Stock Exchange          NRP  0001171486      NATURAL RESOURCE PARTNERS LP       20174.0         True
29    VCX                VICINITY CENTRES       Australia                   Asx - All Markets          VCX  0001867090     Fundrise Innovation Fund, LLC          56.0         True
30   LAND  LAND SECURITIES GROUP REIT PLC  United Kingdom               London Stock Exchange         LAND  0001495240               GLADSTONE LAND CORP       13652.0         True
31   INSM                          INSMED   United States                              NASDAQ         INSM  0001104506                        INSMED INC       17723.0         True

## 10.7 Securities non couvertes par SEC

In [27]:
sec_uncovered = (
    security_master[~security_master["Ticker"].isin(sec_covered_tickers)]
    [["Ticker", "Name", "Location", "Exchange", "resolution_status"]]
    .sort_values(["Location", "Exchange", "Ticker"], kind="stable")
    .reset_index(drop=True)
)

print("Uncovered securities:", len(sec_uncovered))
sec_uncovered

Uncovered securities: 88

        Ticker                                Name        Location                              Exchange resolution_status
0          SCG                       SCENTRE GROUP       Australia                     Asx - All Markets          RESOLVED
1          VER                          VERBUND AG         Austria                      Wiener Boerse Ag          RESOLVED
2          ELI                       ELIA GROUP SA         Belgium     Nyse Euronext - Euronext Brussels          RESOLVED
3         1044          HENGAN INTERNATIONAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
4         1093           CSPC PHARMACEUTICAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
5         1585                YADEA GROUP HOLDINGS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
6         1801                  INNOVENT BIOLOGICS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
7         2015                     LI AUTO CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
8         2319             CHINA MENGNIU DAIRY LTD           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
9          322    TINGYI (CAYMAN ISLANDS) HOLDINGS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
10        3692         HANSOH PHARMACEUTICAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
11        3750  CONTEMPORARY AMPEREX TECHNOLOGY CL           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
12        3898   ZHUZHOU CRRC TIMES ELECTRIC LTD H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
13        6160                  BEONE MEDICINES AG           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
14         916        CHINA LONGYUAN POWER GROUP H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
15        9633                 NONGFU SPRING LTD H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
16        9698                GDS HOLDINGS CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
17        9863   ZHEJIANG LEAPMOTOR TECHNOLOGY LTD           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
18        9866                         NIO CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
19        9868                   XPENG CLASS A INC           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
20        9901  NEW ORIENTAL EDUCATION & TECHNOLOG           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
21      600905  CHINA THREE GORGES RENEWABLES(GROU           China               Shanghai Stock Exchange          RESOLVED
22      601127                       SERES GROUP A           China               Shanghai Stock Exchange          RESOLVED
23      603806  HANGZHOU FIRST APPLIED MATERIAL LT           China               Shanghai Stock Exchange          RESOLVED
24      605117       NINGBO DEYE TECHNOLOGY CORP A           China               Shanghai Stock Exchange          RESOLVED
25      688187   ZHUZHOU CRRC TIMES ELECTRIC LTD A           China               Shanghai Stock Exchange          RESOLVED
26      688472                     CSI SOLAR LTD A           China               Shanghai Stock Exchange          RESOLVED
27      688578  SHANGHAI ALLIST PHARMACEUTICALS LT           China               Shanghai Stock Exchange          RESOLVED
28      000895  HENAN SHUANGHUI INVESTMENT & DEVEL           China               Shenzhen Stock Exchange         AMBIGUOUS
29      001979   CHINA MERCHANTS SHEKOU INDUSTRIAL           China               Shenzhen Stock Exchange         AMBIGUOUS
30      002129  TCL ZHONGHUAN RENEWABLE ENERGY TEC           China               Shenzhen Stock Exchange         AMBIGUOUS
31      002202   GOLDWIND SCIENCE&TECHNOLOGY LTD A           China               Shenzhen Stock Exchange         AMBIGUOUS
32      300274          SUNGROW POWER SUPPLY LTD A           China               Shenzhen Stock Exchange         AMBIGUOUS
33      300750   CONTEMPORARY AMPEREX TECHNOLOGY A           China               Shenzhen Stock Exchange         AMBIGUOUS
34      301358  HUNAN YUNENG NEW ENERGY BATTERY MA           China               Shenzhen Stock Exchange         AMBIGUOUS
35      DEMANT                              DEMANT         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
36      ORSTED                          ORSTED A/S         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
37         VWS                 VESTAS WIND SYSTEMS         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
38         COV                          COVIVIO SA          France        Nyse Euronext - Euronext Paris          RESOLVED
39         GFC                           GECINA SA          France        Nyse Euronext - Euronext Paris          RESOLVED
40         IPN                            IPSEN SA          France        Nyse Euronext - Euronext Paris          RESOLVED
41         URW    UNIBAIL RODAMCO WE STAPLED UNITS          France        Nyse Euronext - Euronext Paris          RESOLVED
42         HOT                         HOCHTIEF AG         Germany                                 Xetra          RESOLVED
43         VNA                          VONOVIA SE         Germany                                 Xetra          RESOLVED
44          12      HENDERSON LAND DEVELOPMENT LTD       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
45         288                            WH GROUP       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
46          66                     MTR CORPORATION       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
47      COLPAL         COLGATE PALMOLIVE INDIA LTD           India      National Stock Exchange Of India        UNRESOLVED
48  HINDUNILVR              HINDUSTAN UNILEVER LTD           India      National Stock Exchange Of India        UNRESOLVED
49       LODHA                LODHA DEVELOPERS LTD           India      National Stock Exchange Of India          RESOLVED
50       LUPIN                               LUPIN           India      National Stock Exchange Of India        UNRESOLVED
51   NESTLEIND                    NESTLE INDIA LTD           India      National Stock Exchange Of India        UNRESOLVED
52      SUZLON                       SUZLON ENERGY           India      National Stock Exchange Of India        UNRESOLVED
53         REC  RECORDATI INDUSTRIA CHIMICA E FARM           Italy                        Borsa Italiana          RESOLVED
54        4151                     KYOWA KIRIN LTD           Japan                  Tokyo Stock Exchange          RESOLVED
55        4507                            SHIONOGI           Japan                  Tokyo Stock Exchange          RESOLVED
56        4519           CHUGAI PHARMACEUTICAL LTD           Japan                  Tokyo Stock Exchange          RESOLVED
57        4523                               EISAI           Japan                  Tokyo Stock Exchange          RESOLVED
58        4543                              TERUMO           Japan                  Tokyo Stock Exchange          RESOLVED
59        4568                  DAIICHI SANKYO LTD           Japan                  Tokyo Stock Exchange          RESOLVED
60        8113                            UNICHARM           Japan                  Tokyo Stock Exchange          RESOLVED
61        8951           NIPPON BUILDING FUND REIT           Japan                  Tokyo Stock Exchange          RESOLVED
62        9020                  EAST JAPAN RAILWAY           Japan                  Tokyo Stock Exchange          RESOLVED
63        9022               CENTRAL JAPAN RAILWAY           Japan                  Tokyo Stock Exchange          RESOLVED
64      247540                       ECOPRO BM LTD   Korea (South)               Korea Exchange (Kosdaq)          RESOLVED
65      010120                     LS ELECTRIC LTD   Korea (South)         Korea Exchange (Stock Market)          RESOLVED
66      373220              LG ENERGY SOLUTION LTD   Korea (South)         Korea Exchange (Stock Market)          RESOLVED
67   FIBRAPL14       PROLOGIS PROPERTY MEXICO REIT          Mexico             Bolsa Mexicana De Valores        UNRESOLVED
68     KIMBERA    KIMBERLY-CLARK DE MEXICO CLASS A          Mexico             Bolsa Mexicana De Valores          RESOLVED
69     SIGMAFA                              ALFA A          Mexico             Bolsa Mexicana De Valores          RESOLVED
70        MOWI                                MOWI          Norway                         Oslo Bors Asa          RESOLVED
71        SALM                              SALMAR          Norway                         Oslo Bors Asa          RESOLVED
72        EDPR                   EDP RENEWABLES SA        Portugal       Nyse Euronext - Euronext Lisbon          RESOLVED
73        2082                       ACWA POWER CO    Saudi Arabia                  Saudi Stock Exchange         AMBIGUOUS
74        CICT  CAPITALAND INTEGRATED COMMERCIAL T       Singapore                    Singapore Exchange          RESOLVED
75         ANA                             ACCIONA           Spain                       Bolsa De Madrid          RESOLVED
76    ESSITY B                      ESSITY CLASS B          Sweden                     Nasdaq Omx Nordic        UNRESOLVED
77       SCA B                 SVENSKA CELLULOSA B          Sweden                     Nasdaq Omx Nordic        UNRESOLVED
78        SOBI            SWEDISH ORPHAN BIOVITRUM          Sweden                     Nasdaq Omx Nordic          RESOLVED
79        NOVN                         NOVARTIS AG     Switzerland                    SIX Swiss Exchange          RESOLVED
80        SOON                   SONOVA HOLDING AG     Switzerland                    SIX Swiss Exchange          RESOLVED
81        SPSN                 SWISS PRIME SITE AG     Switzerland                    SIX Swiss Exchange          RESOLVED
82        1216           UNI-PRESIDENT ENTERPRISES          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
83        6446                      PHARMAESSENTIA          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
84        6669                  WIWYNN CORPORATION          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
85        PSON                         PEARSON PLC  United Kingdom                 London Stock Exchange          RESOLVED
86        SGRO                      SEGRO REIT PLC  United Kingdom                 London Stock Exchange          RESOLVED
87         UU.          UNITED UTILITIES GROUP PLC  United Kingdom                 London Stock Exchange        UNRESOLVED

## 10.8 Couverture par marché

Cette vue guidera le choix de SRC-004B en privilégiant la source capable de couvrir le plus grand nombre de securities encore absentes.

In [28]:
sec_market_coverage = security_master[["Ticker", "Location", "Exchange"]].copy()
sec_market_coverage["sec_covered"] = sec_market_coverage["Ticker"].isin(sec_covered_tickers)

sec_market_summary = (
    sec_market_coverage.groupby(["Location", "Exchange"], dropna=False)
    .agg(securities=("Ticker", "size"), sec_covered=("sec_covered", "sum"))
    .reset_index()
)
sec_market_summary["not_covered"] = sec_market_summary["securities"] - sec_market_summary["sec_covered"]
sec_market_summary["coverage_pct"] = (sec_market_summary["sec_covered"] / sec_market_summary["securities"] * 100).round(2)
sec_market_summary.sort_values(["not_covered", "securities"], ascending=[False, False]).reset_index(drop=True)

          Location                              Exchange  securities  sec_covered  not_covered  coverage_pct
0            China  Hong Kong Exchanges And Clearing Ltd          18            0           18          0.00
1            Japan                  Tokyo Stock Exchange          10            0           10          0.00
2            China               Shanghai Stock Exchange           7            0            7          0.00
3            China               Shenzhen Stock Exchange           7            0            7          0.00
4            India      National Stock Exchange Of India           6            0            6          0.00
5           France        Nyse Euronext - Euronext Paris           5            1            4         20.00
6          Denmark    Omx Nordic Exchange Copenhagen A/S           4            1            3         25.00
7   United Kingdom                 London Stock Exchange           4            1            3         25.00
8        Hong Kong  Hong Kong Exchanges And Clearing Ltd           3            0            3          0.00
9           Mexico             Bolsa Mexicana De Valores           3            0            3          0.00
10          Sweden                     Nasdaq Omx Nordic           3            0            3          0.00
11     Switzerland                    SIX Swiss Exchange           3            0            3          0.00
12          Taiwan                 Taiwan Stock Exchange           3            0            3          0.00
13         Germany                                 Xetra           2            0            2          0.00
14   Korea (South)         Korea Exchange (Stock Market)           2            0            2          0.00
15          Norway                         Oslo Bors Asa           2            0            2          0.00
16       Australia                     Asx - All Markets           3            2            1         66.67
17         Belgium     Nyse Euronext - Euronext Brussels           2            1            1         50.00
18       Singapore                    Singapore Exchange           2            1            1         50.00
19         Austria                      Wiener Boerse Ag           1            0            1          0.00
20           Italy                        Borsa Italiana           1            0            1          0.00
21   Korea (South)               Korea Exchange (Kosdaq)           1            0            1          0.00
22        Portugal       Nyse Euronext - Euronext Lisbon           1            0            1          0.00
23    Saudi Arabia                  Saudi Stock Exchange           1            0            1          0.00
24           Spain                       Bolsa De Madrid           1            0            1          0.00
25   United States                                NASDAQ          14           14            0        100.00
26   United States                                  NYSE           7            7            0        100.00
27          Canada                Toronto Stock Exchange           1            1            0        100.00
28           China                                  NYSE           1            1            0        100.00
29          Israel               Tel Aviv Stock Exchange           1            1            0        100.00
30    South Africa           Johannesburg Stock Exchange           1            1            0        100.00

## 10.9 Taxonomies SEC

In [29]:
sec_taxonomies = (
    sec_facts["taxonomy"]
    .value_counts(dropna=False)
    .rename_axis("taxonomy")
    .reset_index(name="records")
)
sec_taxonomies["percentage"] = (sec_taxonomies["records"] / len(sec_facts) * 100).round(2)
sec_taxonomies

    taxonomy  records  percentage
0    us-gaap   566730       96.58
1  ifrs-full    17413        2.97
2        dei     1976        0.34
3        ecd      372        0.06
4        ffd      117        0.02
5        srt       96        0.02
6     invest       61        0.01
7        cef       44        0.01

## 10.10 Formulaires SEC

In [30]:
sec_forms = (
    sec_facts["form"]
    .value_counts(dropna=False)
    .rename_axis("form")
    .reset_index(name="records")
)
sec_forms["percentage"] = (sec_forms["records"] / len(sec_facts) * 100).round(2)
sec_forms.head(30)

         form  records  percentage
0        10-Q   346444       59.04
1        10-K   202467       34.50
2        20-F    23029        3.92
3         6-K     4921        0.84
4         8-K     4286        0.73
5      10-K/A     2875        0.49
6      10-Q/A     1784        0.30
7     DEF 14A      432        0.07
8      20-F/A      406        0.07
9       424B2       36        0.01
10     N-2ASR       32        0.01
11        S-8       24        0.00
12      424B5       23        0.00
13      424B7       18        0.00
14     S-3ASR       10        0.00
15    SC TO-T        5        0.00
16  SC TO-I/A        5        0.00
17     F-3ASR        5        0.00
18        S-3        5        0.00
19      8-K/A        2        0.00

## 10.11 Concepts XBRL disponibles

In [31]:
sec_concepts = (
    sec_facts.groupby(["taxonomy", "concept", "label"], dropna=False)
    .agg(records=("value", "size"), securities=("input_ticker", "nunique"))
    .reset_index()
    .sort_values(["securities", "records"], ascending=False)
    .reset_index(drop=True)
)

print("Distinct taxonomy/concept pairs:", sec_facts[["taxonomy", "concept"]].drop_duplicates().shape[0])
sec_concepts.head(50)

Distinct taxonomy/concept pairs: 3963

,taxonomy,concept,label,records,securities
0,us-gaap,NetIncomeLoss,Net Income (Loss) Attributable to Parent,6229,28
1,us-gaap,OperatingIncomeLoss,Operating Income (Loss),5154,27
2,us-gaap,CashAndCashEquivalentsAtCarryingValue,"Cash and Cash Equivalents, at Carrying Value",4769,27
3,us-gaap,ComprehensiveIncomeNetOfTax,"Comprehensive Income (Loss), Net of Tax, Attributable to Parent",4603,27
4,us-gaap,InterestExpense,Interest Expense,3336,27
5,us-gaap,Assets,Assets,3313,27
6,us-gaap,NetCashProvidedByUsedInOperatingActivities,Net Cash Provided by (Used in) Operating Activities,3142,27
7,us-gaap,LiabilitiesAndStockholdersEquity,Liabilities and Equity,3139,27
8,us-gaap,AccumulatedOtherComprehensiveIncomeLossNetOfTax,"Accumulated Other Comprehensive Income (Loss), Net of Tax",3119,27
9,us-gaap,NetCashProvidedByUsedInInvestingActivities,Net Cash Provided by (Used in) Investing Activities,3107,27
10,us-gaap,NetCashProvidedByUsedInFinancingActivities,Net Cash Provided by (Used in) Financing Activities,3099,27
11,us-gaap,OperatingLeaseLiability,"Operating Lease, Liability",509,27
12,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDue,"Lessee, Operating Lease, Liability, to be Paid",362,27
13,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueYearFour,"Lessee, Operating Lease, Liability, to be Paid, Year Four",362,27
14,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueYearThree,"Lessee, Operating Lease, Liability, to be Paid, Year Three",362,27
15,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueYearTwo,"Lessee, Operating Lease, Liability, to be Paid, Year Two",362,27
16,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive,"Lessee, Operating Lease, Liability, to be Paid, after Year Five",310,27
17,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueYearFive,"Lessee, Operating Lease, Liability, to be Paid, Year Five",302,27
18,us-gaap,LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths,"Lessee, Operating Lease, Liability, to be Paid, Year One",288,27
19,us-gaap,EarningsPerShareDiluted,"Earnings Per Share, Diluted",5488,26
20,us-gaap,WeightedAverageNumberOfDilutedSharesOutstanding,"Weighted Average Number of Shares Outstanding, Diluted",4517,26
21,us-gaap,IncomeTaxExpenseBenefit,Income Tax Expense (Benefit),4502,26
22,us-gaap,StockholdersEquity,Stockholders' Equity Attributable to Parent,4394,26
23,us-gaap,OtherNonoperatingIncomeExpense,Other Nonoperating Income (Expense),3579,26
24,us-gaap,CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents,"Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents",2812,26
25,us-gaap,EffectiveIncomeTaxRateContinuingOperations,"Effective Income Tax Rate Reconciliation, Percent",2160,26
26,us-gaap,InterestPaidNet,"Interest Paid, Excluding Capitalized Interest, Operating Activities",1642,26
27,us-gaap,CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect,"Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Excha...",1631,26
28,dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",1416,26
29,us-gaap,OperatingLeaseRightOfUseAsset,"Operating Lease, Right-of-Use Asset",1005,26
30,us-gaap,EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate,"Effective Income Tax Rate Reconciliation, at Federal Statutory Income Tax Rate, Percent",942,26
31,us-gaap,DeferredTaxAssetsValuationAllowance,"Deferred Tax Assets, Valuation Allowance",845,26
32,us-gaap,LesseeOperatingLeaseLiabilityUndiscountedExcessAmount,"Lessee, Operating Lease, Liability, Undiscounted Excess Amount",356,26
33,us-gaap,EarningsPerShareBasic,"Earnings Per Share, Basic",5179,25
34,us-gaap,WeightedAverageNumberOfSharesOutstandingBasic,"Weighted Average Number of Shares Outstanding, Basic",4296,25
35,us-gaap,ShareBasedCompensation,"Share-based Payment Arrangement, Noncash Expense",3028,25
36,us-gaap,RetainedEarningsAccumulatedDeficit,Retained Earnings (Accumulated Deficit),2776,25
37,us-gaap,IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest,"Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest",2344,25
38,us-gaap,CommonStockSharesIssued,"Common Stock, Shares, Issued",2315,25
39,us-gaap,DeferredIncomeTaxExpenseBenefit,Deferred Income Tax Expense (Benefit),1638,25
40,us-gaap,UnrecognizedTaxBenefits,Unrecognized Tax Benefits,1420,25
41,us-gaap,IncomeTaxesPaidNet,"Income Taxes Paid, Net",1345,25
42,us-gaap,RightOfUseAssetObtainedInExchangeForOperatingLeaseLiability,Right-of-Use Asset Obtained in Exchange for Operating Lease Liability,840,25
43,us-gaap,DeferredTaxAssetsGross,"Deferred Tax Assets, Gross",736,25
44,dei,EntityPublicFloat,Entity Public Float,433,25
45,us-gaap,AssetsCurrent,"Assets, Current",2745,24
46,us-gaap,LiabilitiesCurrent,"Liabilities, Current",2701,24
47,us-gaap,OtherLiabilitiesNoncurrent,"Other Liabilities, Noncurrent",2549,24
48,us-gaap,PropertyPlantAndEquipmentNet,"Property, Plant and Equipment, Net",2522,24
49,us-gaap,Liabilities,Liabilities,2514,24

## 10.12 Couverture conceptuelle indicative

La recherche ci-dessous est exploratoire. Elle vérifie uniquement si des familles de concepts potentiellement utiles existent dans le RAW. Elle ne constitue pas le futur mapping comptable de production.

In [32]:
KEYWORDS = {
    "revenue": ["revenue", "sales"],
    "operating_income": ["operating income", "operating profit"],
    "net_income": ["net income", "profit loss"],
    "assets": ["assets"],
    "liabilities": ["liabilities"],
    "equity": ["stockholders equity", "shareholders equity"],
    "cash": ["cash and cash equivalents", "cash equivalents"],
    "debt": ["debt", "borrowings"],
    "shares": ["shares outstanding", "common stocks outstanding"],
}

concept_text = (sec_facts["concept"].fillna("") + " " + sec_facts["label"].fillna("")).str.casefold()
rows = []
for metric, keywords in KEYWORDS.items():
    mask = pd.Series(False, index=sec_facts.index)
    for keyword in keywords:
        mask |= concept_text.str.contains(keyword, regex=False)
    rows.append({
        "indicative_metric": metric,
        "matching_fact_rows": int(mask.sum()),
        "securities_with_match": int(sec_facts.loc[mask, "input_ticker"].nunique()),
    })

pd.DataFrame(rows)

  indicative_metric  matching_fact_rows  securities_with_match
0           revenue               27149                     32
1  operating_income               11927                     27
2        net_income               18565                     28
3            assets               46448                     31
4       liabilities               33170                     31
5            equity                   0                      0
6              cash               15737                     27
7              debt               35677                     32
8            shares               13214                     30

## 10.13 Contrôles temporels

In [33]:
sec_temporal = pd.DataFrame({
    "metric": ["Fact rows", "Filed", "End", "Start", "Fiscal year", "Fiscal period", "Frame"],
    "records": [
        len(sec_facts), sec_facts["filed"].ne("").sum(), sec_facts["end"].ne("").sum(),
        sec_facts["start"].ne("").sum(), sec_facts["fiscal_year"].ne("").sum(),
        sec_facts["fiscal_period"].ne("").sum(), sec_facts["frame"].ne("").sum(),
    ],
})
sec_temporal["percentage"] = (sec_temporal["records"] / len(sec_facts) * 100).round(2)
sec_temporal

          metric  records  percentage
0      Fact rows   586809      100.00
1          Filed   586809      100.00
2            End   586809      100.00
3          Start   357776       60.97
4    Fiscal year   582873       99.33
5  Fiscal period   582873       99.33
6          Frame   246124       41.94

## 10.14 Doublons techniques exacts

In [34]:
SEC_DUPLICATE_KEY = [
    "input_ticker", "cik", "taxonomy", "concept", "unit", "start", "end",
    "value", "accession", "form", "filed", "frame"
]
sec_duplicate_mask = sec_facts.duplicated(subset=SEC_DUPLICATE_KEY, keep=False)

print("Rows involved in exact duplicates:", int(sec_duplicate_mask.sum()))
print("Exact duplicate groups:", sec_facts.loc[sec_duplicate_mask, SEC_DUPLICATE_KEY].drop_duplicates().shape[0])

Rows involved in exact duplicates: 0
Exact duplicate groups: 0

## 10.15 Champs structurants manquants

In [35]:
SEC_STRUCTURAL_FIELDS = [
    "input_ticker", "cik", "entity_name", "taxonomy", "concept", "unit",
    "value", "accession", "form", "filed"
]

missing_rows = []
for column in SEC_STRUCTURAL_FIELDS:
    blank = sec_facts[column].astype(str).str.strip().eq("")
    missing_rows.append({
        "field": column,
        "missing_records": int(blank.sum()),
        "missing_pct": round(float(blank.mean() * 100), 4),
    })

pd.DataFrame(missing_rows)

          field  missing_records  missing_pct
0  input_ticker                0          0.0
1           cik                0          0.0
2   entity_name                0          0.0
3      taxonomy                0          0.0
4       concept                0          0.0
5          unit                0          0.0
6         value                0          0.0
7     accession                0          0.0
8          form                0          0.0
9         filed                0          0.0

### Conclusion SRC-004A / DS-008

Résultat actuellement observé :

- **120** securities en entrée ;
- **32** securities associées à un CIK SEC ;
- **88** `ticker_not_found` ;
- **586 809** faits XBRL acquis ;
- **586 897** lignes RAW au total ;
- taxonomies majoritairement `us-gaap`, avec présence de `ifrs-full` et taxonomies complémentaires ;
- formulaires principalement `10-Q`, `10-K` et `20-F`.

La couverture société est donc **26,67 %**, insuffisante pour clôturer l’acquisition des fondamentaux. SRC-004A est validée techniquement, mais une SRC-004B est nécessaire afin d’augmenter la couverture des 88 securities restantes.

Les éventuelles collisions ticker → entité SEC doivent être revues sans réécrire le RAW.

# 11. Logging et traçabilité

## Technical Log

Le Technical Log documente les étapes d’exécution, validations, warnings et erreurs techniques.

In [36]:
if TECHNICAL_LOG.exists():
    with open(TECHNICAL_LOG, "r", encoding="utf-8", errors="ignore") as handle:
        log_lines = handle.readlines()
    print("Technical log lines:", len(log_lines))
    print("".join(log_lines[-20:]))
else:
    print("Technical log not found:", TECHNICAL_LOG)

Technical log lines: 2146
2026-09-29 09:34:28,893 | INFO | API Connector resolved: sec_edgar
2026-09-29 09:34:28,893 | INFO | API output resolved: C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\fundamentals\fundamentals_sec.csv
2026-09-29 09:34:28,893 | INFO | Loading API upstream Dataset: C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities\securities_master.csv
2026-09-29 09:34:28,910 | INFO | API upstream Dataset loaded: Rows=120; Columns=21
2026-09-29 09:34:54,343 | INFO | SEC EDGAR acquisition completed: Input=120; SEC-covered=32; TickerNotFound=88; Requests=32; Records=586897; Facts=586809
2026-09-29 09:35:05,077 | INFO | Database schema initialization started
2026-09-29 09:35:05,090 | INFO | Database migration already applied: 1
2026-09-29 09:35:05,090 | INFO | Database migration already applied: 2
2026-09-29 09:35:05,090 | INFO | Database schema version: 2
2026-09-29 09:35:05,090 | INFO | Technical table available: acquisition_log
2026-09-29 09:35:05,090 | INFO | Technical table available: dataset_registry
2026-09-29 09:35:05,090 | INFO | Technical table available: quality_run
2026-09-29 09:35:05,090 | INFO | Technical table available: quality_control_result
2026-09-29 09:35:05,090 | INFO | Technical table available: quality_metric_result
2026-09-29 09:35:05,090 | INFO | Database schema initialization completed successfully
2026-09-29 09:35:05,110 | INFO | [AUDIT] RUN-20260929-073505-1C9EB3E2 | Acquisition | fundamentals_sec.csv | Success | Records=586897
2026-09-29 09:35:05,110 | INFO | API Dataset acquisition logged: Dataset=DS-008; RunID=RUN-20260929-073505-1C9EB3E2
2026-09-29 09:35:05,110 | INFO | API Dataset execution completed: Dataset=DS-008; Records=586897
2026-09-29 09:35:05,226 | INFO | Generic API acquisition completed successfully: Datasets=1
2026-09-29 09:35:05,226 | INFO | API engine published 1 Dataset(s)

## Acquisition / Preparation Log

La validation du log métier doit s’appuyer sur la table ou le fichier réellement utilisé par `acquisition_logger.py`. Le workbook ne suppose plus l’ancien contrat Excel si le mécanisme courant a évolué.

In [37]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        tables = set(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", connection)["name"])
        if "acquisition_log" in tables:
            acquisition_log = pd.read_sql(
                "SELECT * FROM acquisition_log ORDER BY execution_date DESC LIMIT 30",
                connection,
            )
            display(acquisition_log)
        else:
            print("acquisition_log table not found.")

,run_id,execution_date,process_type,output_file,storage_location,status,records_produced,notes,created_at
0,RUN-20260929-073505-1C9EB3E2,2026-09-29T07:35:05+00:00,Acquisition,fundamentals_sec.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\fundamentals,Success,586897.0,"{""connector"": ""sec_edgar"", ""dataset_id"": ""DS-008"", ""metadata"": {""companyfacts_requests"": 32, ""fact_records"": 586809,...",2026-09-29T07:35:05+00:00
1,RUN-20260929-072914-589D3BE5,2026-09-29T07:29:14+00:00,Acquisition,fundamentals_sec.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\fundamentals,Success,586897.0,"{""connector"": ""sec_edgar"", ""dataset_id"": ""DS-008"", ""metadata"": {""companyfacts_requests"": 32, ""fact_records"": 586809,...",2026-09-29T07:29:14+00:00
2,RUN-20260929-072808-8A35BC3C,2026-09-29T07:28:08+00:00,Acquisition,fundamentals_sec.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\fundamentals,Failed,NaN,"{""connector"": ""sec_edgar"", ""dataset_id"": ""DS-008"", ""error"": ""SEC EDGAR Parameters are missing: ['ticker_column']"", ""...",2026-09-29T07:28:08+00:00
3,RUN-20260922-075058-4E28E1B9,2026-09-22T07:50:58+00:00,Acquisition,market_prices.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\market,Success,1686360.0,"{""connector"": ""yfinance"", ""dataset_id"": ""DS-004"", ""metadata"": {""end"": null, ""interval"": ""1d"", ""observation_records"":...",2026-09-22T07:50:58+00:00
4,RUN-20260922-074909-A9248D6A,2026-09-22T07:49:09+00:00,Preparation,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,"{""ambiguous_records"": 11, ""candidate_records"": 120, ""inputs"": [""security_candidates.csv"", ""openfigi_mapping.csv""], ""...",2026-09-22T07:49:09+00:00
5,RUN-20260922-073423-7F8A4616,2026-09-22T07:34:23+00:00,Acquisition,market_prices.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\market,Success,1642680.0,"{""connector"": ""yfinance"", ""dataset_id"": ""DS-004"", ""metadata"": {""end"": null, ""interval"": ""1d"", ""observation_records"":...",2026-09-22T07:34:23+00:00
6,RUN-20260922-072654-BEB1F2B5,2026-09-22T07:26:54+00:00,Acquisition,market_prices.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\market,Failed,NaN,"{""connector"": ""yfinance"", ""dataset_id"": ""DS-004"", ""error"": ""name 'symbol_level' is not defined"", ""error_type"": ""Name...",2026-09-22T07:26:54+00:00
7,RUN-20260922-072523-31196DE2,2026-09-22T07:25:23+00:00,Acquisition,market_prices.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\market,Failed,NaN,"{""connector"": ""yfinance"", ""dataset_id"": ""DS-004"", ""error"": ""'dict' object has no attribute 'eys'"", ""error_type"": ""At...",2026-09-22T07:25:23+00:00
8,RUN-20260921-143641-C00F39E5,2026-09-21T14:36:41+00:00,Preparation,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,"{""ambiguous_records"": 11, ""candidate_records"": 120, ""inputs"": [""security_candidates.csv"", ""openfigi_mapping.csv""], ""...",2026-09-21T14:36:41+00:00
9,RUN-20260921-143453-A85E63EF,2026-09-21T14:34:53+00:00,Preparation,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,"{""ambiguous_records"": 11, ""candidate_records"": 120, ""inputs"": [""security_candidates.csv"", ""openfigi_mapping.csv""], ""...",2026-09-21T14:34:53+00:00
10,RUN-20260921-142156-130298D1,2026-09-21T14:21:56+00:00,Acquisition,openfigi_mapping.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\securities,Success,1992.0,"{""connector"": ""openfigi"", ""dataset_id"": ""DS-002"", ""metadata"": {""http_requests"": 2, ""input_records"": 120, ""mapping_jo...",2026-09-21T14:21:56+00:00
11,RUN-20260921-142106-10DDA30E,2026-09-21T14:21:06+00:00,Preparation,security_candidates.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,Input=benchmark_holdings.xls; Worksheet=Holdings; HoldingsRows=150; SelectedRows=121; InvalidTickerRejected=1; Missi...,2026-09-21T14:21:06+00:00
12,RUN-20260921-121249-C7E379A2,2026-09-21T12:12:49+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Success,NaN,"{""bytes_written"": 1376054, ""content_length"": 1376054, ""content_type"": ""application/vnd.ms-excel"", ""dataset_id"": ""DS-...",2026-09-21T12:12:49+00:00
13,RUN-20260921-121242-FDA8314F,2026-09-21T12:12:42+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Success,NaN,"{""bytes_written"": 1376054, ""content_length"": 1376054, ""content_type"": ""application/vnd.ms-excel"", ""dataset_id"": ""DS-...",2026-09-21T12:12:42+00:00
14,RUN-20260921-114202-72B8BBE2,2026-09-21T11:42:02+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Success,NaN,"{""bytes_written"": 1376054, ""content_length"": 1376054, ""content_type"": ""application/vnd.ms-excel"", ""dataset_id"": ""DS-...",2026-09-21T11:42:02+00:00
15,RUN-20260921-113559-8B1DA055,2026-09-21T11:35:59+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Failed,NaN,"{""dataset_id"": ""DS-000"", ""error"": ""stream_response_to_file() got an unexpected keyword argument 'chunk_size_bytes'"",...",2026-09-21T11:35:59+00:00
16,RUN-20260915-112819-64D88D34,2026-09-15T11:28:19+00:00,Acquisition,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Partial Success,103.0,Input records=120; Matches=103; Exceptions=17; Coverage=85.83%,2026-09-15T11:28:19+00:00
17,RUN-20260915-112819-3F52A99A,2026-09-15T11:28:19+00:00,Acquisition,securities_unmatched.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,17.0,Input records=120; Matches=103; Exceptions=17; Coverage=85.83%,2026-09-15T11:28:19+00:00
18,RUN-20260915-112607-02A029BE,2026-09-15T11:26:07+00:00,Acquisition,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Partial Success,103.0,Input records=120; Matches=103; Exceptions=17; Coverage=85.83%,2026-09-15T11:26:07+00:00
19,RUN-20260915-112607-57246D60,2026-09-15T11:26:07+00:00,Acquisition,securities_unmatched.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,17.0,Input records=120; Matches=103; Exceptions=17; Coverage=85.83%,2026-09-15T11:26:07+00:00
20,RUN-20260915-103445-B8AD3C68,2026-09-15T10:34:45+00:00,Preparation,security_candidates.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,Input file=benchmark_holdings.xls; Holdings rows=155; Output rows=120,2026-09-15T10:34:45+00:00
21,RUN-20260915-095706-6A26A347,2026-09-15T09:57:06+00:00,Preparation,security_candidates.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,121.0,Input file=benchmark_holdings.xls; Holdings rows=155; Output rows=121,2026-09-15T09:57:06+00:00
22,RUN-20260915-082058-369ED751,2026-09-15T08:20:58+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Success,NaN,File size bytes=1380184; Worksheets=10,2026-09-15T08:20:58+00:00
23,RUN-20260915-081457-F1F672BA,2026-09-15T08:14:57+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Failed,NaN,name 'ElementTree' is not defined,2026-09-15T08:14:57+00:00
24,RUN-20260915-081141-17755FED,2026-09-15T08:11:41+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Failed,NaN,The downloaded XML workbook is invalid.,2026-09-15T08:11:41+00:00
25,RUN-20260915-080230-F478244F,2026-09-15T08:02:30+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Failed,NaN,The downloaded XML workbook is invalid.,2026-09-15T08:02:30+00:00

# 12. Database – état courant

Le chargement SQLite est une étape distincte de l’acquisition. Ce contrôle inventorie les tables réellement disponibles sans exiger des tables historiques supprimées par le refactoring.

In [40]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        database_tables = pd.read_sql(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name",
            connection,
        )
    database_tables
else:
    print("Database not found.")

# 13. Couverture globale de la Phase 3

Ce tableau est mis à jour à mesure que chaque source est définitivement validée.

In [39]:
phase3_status = pd.DataFrame([
    {"Source": "SRC-001", "Dataset": "DS-000", "Domain": "Benchmark", "Status": "VALIDATED"},
    {"Source": "SRC-002", "Dataset": "DS-002", "Domain": "Security identifiers", "Status": "VALIDATED"},
    {"Source": "SRC-003A", "Dataset": "DS-007", "Domain": "Market", "Status": "DEFERRED"},
    {"Source": "SRC-003B", "Dataset": "DS-004", "Domain": "Market", "Status": "DEFERRED"},
    {"Source": "SRC-004A", "Dataset": "DS-008", "Domain": "Fundamentals", "Status": "VALIDATED / COVERAGE INCOMPLETE"},
    {"Source": "SRC-004B+", "Dataset": "TBD", "Domain": "Fundamentals", "Status": "REQUIRED"},
    {"Source": "SRC-005A", "Dataset": "DS-005 / DS-006", "Domain": "Macro", "Status": "TO VALIDATE"},
    {"Source": "SRC-005B", "Dataset": "TBD", "Domain": "Macro", "Status": "TO BUILD"},
    {"Source": "SRC-005C", "Dataset": "TBD", "Domain": "Macro", "Status": "TO BUILD"},
    {"Source": "SRC-006", "Dataset": "TBD", "Domain": "FX", "Status": "TO BUILD"},
    {"Source": "SRC-007", "Dataset": "TBD", "Domain": "ODD", "Status": "TO BUILD"},
    {"Source": "SRC-008", "Dataset": "TBD", "Domain": "Exclusions", "Status": "TO BUILD"},
])
phase3_status

       Source          Dataset                Domain                           Status
0     SRC-001           DS-000             Benchmark                        VALIDATED
1     SRC-002           DS-002  Security identifiers                        VALIDATED
2    SRC-003A           DS-007                Market                         DEFERRED
3    SRC-003B           DS-004                Market                         DEFERRED
4    SRC-004A           DS-008          Fundamentals  VALIDATED / COVERAGE INCOMPLETE
5   SRC-004B+              TBD          Fundamentals                         REQUIRED
6    SRC-005A  DS-005 / DS-006                 Macro                      TO VALIDATE
7    SRC-005B              TBD                 Macro                         TO BUILD
8    SRC-005C              TBD                 Macro                         TO BUILD
9     SRC-006              TBD                    FX                         TO BUILD
10    SRC-007              TBD                   ODD                         TO BUILD
11    SRC-008              TBD            Exclusions                         TO BUILD

# 14. Critères de clôture de la Phase 3

La Phase 3 sera considérée comme terminée lorsque :

1. toutes les sources nécessaires du Source Registry disposent d’un contrat Dataset exploitable ;
2. chaque source automatisable possède un connector ou une méthode Download fonctionnelle ;
3. les acquisitions RAW sont produites et validées ;
4. les sources de backup nécessaires sont construites jusqu’à atteindre une couverture suffisante ;
5. les dépendances et la lineage sont validées ;
6. les runs sont traçables ;
7. les datasets destinés à SQLite disposent d’un contrat de chargement ;
8. les exceptions connues sont documentées ;
9. aucune nouvelle source n’est ajoutée lorsqu’elle n’apporte plus de couverture utile.

# Conclusion actuelle

Les acquisitions SRC-001, SRC-002 et SRC-004A sont techniquement validées dans l’architecture actuelle.

Le pipeline `DS-000 → DS-001 → DS-002 → DS-003` fournit la base de lineage des instruments. SRC-004A / DS-008 ajoute une première couche Fundamentals RAW structurée via SEC EDGAR, avec 32 securities couvertes sur 120 et 586 809 faits XBRL acquis.

La couverture Fundamentals reste insuffisante et nécessite au moins une source supplémentaire. SRC-003A et SRC-003B seront reprises ultérieurement, conformément à la décision de reporter la validation finale des sources de marché.

Le workbook doit continuer à être enrichi source par source jusqu’à satisfaire les critères de clôture de la Phase 3.