# Phase 3 – Validation Workbook – Acquisition des données

## Objectif

Ce workbook constitue le contrôle maître de la Phase 3. Il valide progressivement la gouvernance, les acquisitions RAW, les préparations nécessaires à l’acquisition, la traçabilité et la couverture des sources avant de clôturer la phase.

Principes de validation :

- **Registry-driven** : la configuration est lue depuis le Source Registry ;
- **RAW-first** : les réponses fournisseurs sont conservées avant préparation métier ;
- **lineage explicite** : les dépendances entre datasets sont contrôlées ;
- **pas de sélection arbitraire** : les ambiguïtés sont conservées et documentées ;
- **couverture incrémentale** : une nouvelle source n’est ajoutée que si les sources déjà acquises ne couvrent pas suffisamment le besoin ;
- **validation avant clôture** : la Phase 3 n’est considérée comme terminée qu’après stabilisation de toutes les sources nécessaires.

> Les cours de marché viennent de Yahoo Finance, `DS-004`. Un titre sans historique complet reste acquis ; il est écarté seulement à la construction du portefeuille.

# 1. Imports et chemins projet

In [1]:
from pathlib import Path
import json
import re
import sqlite3

import pandas as pd

from IPython.display import Markdown, display
from pathlib import Path
import io
import re
import zipfile

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 120)

cwd = Path.cwd().resolve()

candidates = [cwd, cwd.parent, cwd.parent.parent]
PROJECT_ROOT = next((p for p in candidates if (p / "src").is_dir()), None)

if PROJECT_ROOT is None:
    raise RuntimeError("Unable to locate project root containing src/.")

SOURCE_REGISTRY_FILE = PROJECT_ROOT / "audit" / "source_registry.xlsx"
DATABASE_FILE = PROJECT_ROOT / "database" / "sdg_investment.db"
TECHNICAL_LOG = PROJECT_ROOT / "logs" / "technical.log"

BENCHMARK_DIR = PROJECT_ROOT / "data/01_raw/benchmark"
RAW_SECURITIES_DIR = PROJECT_ROOT / "data/01_raw/securities"
PROCESSED_SECURITIES_DIR = PROJECT_ROOT / "data/02_processed/securities"
RAW_MARKET_DIR = PROJECT_ROOT / "data/01_raw/market"
RAW_MACRO_DIR = PROJECT_ROOT / "data/01_raw/macro"
RAW_FUNDAMENTALS_DIR = PROJECT_ROOT / "data/01_raw/fundamentals"

print("Project root:", PROJECT_ROOT)
print("Source Registry:", SOURCE_REGISTRY_FILE)
print("Database:", DATABASE_FILE)

Project root: C:\Users\MameBARBOSAMONTEIRO\projet01
Source Registry: C:\Users\MameBARBOSAMONTEIRO\projet01\audit\source_registry.xlsx
Database: C:\Users\MameBARBOSAMONTEIRO\projet01\database\sdg_investment.db

> Les chemins doivent être résolus depuis la racine du projet, sans dépendre du répertoire depuis lequel le notebook est lancé.

# 2. Governance – Source Registry

Le Source Registry comporte deux couches complémentaires :

- **Sources** : gouvernance des fournisseurs et sources externes ;
- **Datasets** : contrats techniques de production, dépendances, stockage et activation.

In [2]:
from IPython.display import Markdown, display

if not SOURCE_REGISTRY_FILE.exists():
    raise FileNotFoundError(
        SOURCE_REGISTRY_FILE
    )

sources_registry = pd.read_excel(
    SOURCE_REGISTRY_FILE,
    sheet_name="Sources",
)

datasets_registry = pd.read_excel(
    SOURCE_REGISTRY_FILE,
    sheet_name="Datasets",
)

sources_count = len(
    sources_registry
)

datasets_count = len(
    datasets_registry
)

print(
    "Sources:",
    sources_registry.shape,
)

print(
    "Datasets:",
    datasets_registry.shape,
)

if (
    sources_count > 0
    and datasets_count > 0
):
    status = "PASS"
    message = (
        f"Le Source Registry contient **{sources_count} sources** "
        f"et **{datasets_count} datasets configurés**. "
        "Les deux feuilles de gouvernance sont non vides."
    )
else:
    status = "FAIL"
    message = (
        f"Le Source Registry contient **{sources_count} sources** "
        f"et **{datasets_count} datasets**. "
        "Au moins une feuille de gouvernance est vide."
    )

display(
    Markdown(
        f"""

{message}

**Résultat : {status}**
"""
    )
)

Sources: (11, 7)
Datasets: (10, 15)

Le Source Registry contient **11 sources** et **10 datasets configurés**. Les deux feuilles de gouvernance sont non vides.

**Résultat : PASS**

In [3]:
def get_dataset_path(dataset_id: str) -> Path:
    """
    Resolve a dataset output path from the Dataset Registry.
    """

    matches = datasets_registry.loc[
        datasets_registry["Dataset ID"].eq(
            dataset_id
        )
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one Registry entry "
            f"for {dataset_id}; found {len(matches)}."
        )

    dataset = matches.iloc[0]

    storage_directory = str(
        dataset["Storage Directory"]
    ).strip()

    output_file_name = str(
        dataset["Output File Name"]
    ).strip()

    if not storage_directory:
        raise ValueError(
            f"{dataset_id}: Storage Directory is required."
        )

    if not output_file_name:
        raise ValueError(
            f"{dataset_id}: Output File Name is required."
        )

    return (
        PROJECT_ROOT
        / storage_directory
        / output_file_name
    )

## 2.1 Sources actives

In [4]:
source_columns = [
    col for col in [
        "Source ID", "Provider", "Reliability", "Backup Source", "Status", "Comments"
    ] if col in sources_registry.columns
]

sources_registry[source_columns]

,Source ID,Provider,Reliability,Backup Source,Status,Comments
0,SRC-001,iShares / BlackRock,High,NaN,Active,Benchmark officiel du projet utilisé comme référence d'investissement et de comparaison des performances
1,SRC-002,OpenFIGI,High,Manual Research,Active,Source principale utilisée pour construire le Securities Master et standardiser les identifiants des instruments fin...
2,SRC-003B,Yahoo Finance,Medium,NaN,Active,Source principale utilisée pour l'acquisition des données historiques de marché nécessaires aux analyses de performa...
3,SRC-004A,SED EDGAR,High,NaN,Active,Source réglementaire structurée utilisée en priorité pour l’acquisition des données fondamentales des entreprises co...
4,SRC-004,Investor Relations Websites,High,Company Annual Reports,Active,Source générique de référence pour les données fondamentales des entreprises composant l'univers investissable.
5,SRC-005A,FRED,High,SRC-005C,Active,Source principale retenue pour les indicateurs macroéconomiques utilisés dans les analyses d'investissement.
6,SRC-005B,World Bank Data,High,SRC-005C,Active,Source de référence utilisée pour les indicateurs macroéconomiques de long terme.
7,SRC-005C,International Monetary Fund (IMF),High,SRC-005B,Active,Source complémentaire utilisée pour enrichir et valider les analyses macroéconomiques.
8,SRC-006A,Swiss National Bank (SNB),High,NaN,Active,Source officielle retenue pour la conversion des prix et rendements vers la devise de reporting CHF.
9,SRC-007,"Annual Reports, Sustainability Reports & Corporate Websites",Medium,Public Sustainability Reports,Active,"Source générique utilisée pour documenter les activités économiques, les preuves d'alignement ODD et les controverse..."
10,SRC-008,"Public Controversy Sources, Annual Reports & Sustainability Reports",Medium,NaN,Active,Source utilisée pour documenter les exclusions du mandat et renforcer le contrôle de non-préjudice dans la méthodolo...

## 2.2 Datasets configurés

In [5]:
dataset_columns = [
    "Dataset ID", "Source ID", "Dataset Name", "Production Method", "Connector",
    "Access Endpoint", "Parameters", "Input Dataset IDs", "Output File Name",
    "Storage Directory", "Frequency", "Load Enabled", "Quality Enabled",
    "Chronology Enabled", "Active"
]

missing_dataset_columns = sorted(set(dataset_columns) - set(datasets_registry.columns))
print("Missing Dataset columns:", missing_dataset_columns)

datasets_registry[[c for c in dataset_columns if c in datasets_registry.columns]]

Missing Dataset columns: []

,Dataset ID,Source ID,Dataset Name,Production Method,Connector,Access Endpoint,Parameters,Input Dataset IDs,Output File Name,Storage Directory,Frequency,Load Enabled,Quality Enabled,Chronology Enabled,Active
0,DS-000,SRC-001,Benchmark Holdings,Download,NaN,https://www.blackrock.com/varnish-api/blk-one01-product-data/product-data/api/v1/get-fund-document?appType=PRODUCT_P...,{},[],benchmark_holdings.xls,data/01_raw/benchmark,Periodic,False,False,False,True
1,DS-001,SRC-001,Security Candidates,Preparation,NaN,NaN,"{\n ""worksheet"": ""Holdings"",\n ""asset_class_column"": ""Asset Class"",\n ""included_asset_classes"": [""Equity""],\n ""d...","[""DS-000""]",security_candidates.csv,data/02_processed/securities,Periodic,True,False,False,True
2,DS-002,SRC-002,OpenFIGI Mapping,API,openfigi,https://api.openfigi.com/v3/mapping,"{\n ""id_type"": ""TICKER"",\n ""id_value_column"": ""Ticker""\n}","[""DS-001""]",openfigi_mapping.csv,data/01_raw/securities,On demand,True,True,False,True
3,DS-003,SRC-002,Security Master,Preparation,NaN,NaN,{},"[""DS-001"",""DS-002""]",securities_master.csv,data/02_processed/securities,On demand,True,True,False,True
4,DS-004,SRC-003B,Market Prices,Package,yfinance,NaN,"{\n ""symbol_column"": ""yahoo_symbol"",\n ""name_column"": ""Name"",\n ""exchange_column"": ""Exchange"",\n ""period"": ""max""...","[""DS-003""]",market_prices.csv,data/01_raw/market,Daily,True,True,True,True
5,DS-006,SRC-005A,Macro Indicators,API,fred,https://api.stlouisfed.org/fred/series/observations,"{\n ""series_ids"": [""CPIAUCSL"", ""UNRATE"", ""FEDFUNDS""],\n ""file_type"": ""json""\n}",[],macro_indicators.csv,data/01_raw/macro,Monthly,True,True,True,True
6,DS-008,SRC-004A,SEC Fundamentals,API,sec_edgar,https://data.sec.gov/api/xbrl/companyfacts/,"{\n ""ticker_column"": ""Ticker"",\n ""name_column"": ""Name"",\n ""exchange_column"": ""Exchange"",\n ""ticker_reference_end...","[""DS-003""]",fundamentals_sec.csv,data/01_raw/fundamentals,Quarterly,True,True,True,True
7,DS-009,SRC-006A,FX Rates,API,snb,https://data.snb.ch/api/cube,"{\n ""cube_id"": ""devkum"",\n ""language"": ""en"",\n ""file_type"": ""json"",\n ""from_date"": ""1970-01"",\n ""frequency_code...","[""DS-003""]",fx_rates.csv,data/01_raw/fx,Monthly,True,True,True,True
8,DS-010,SRC-007,ODD Assessment,Preparation,NaN,NaN,{},"[""DS-003""]",odd_assessment.csv,data/01_raw/odd,Annual,True,False,False,True
9,DS-011,SRC-006A,SARON,API,snb,https://data.snb.ch/api/cube,"{\n ""cube_id"": ""zimoma"",\n ""language"": ""en"",\n ""file_type"": ""json"",\n ""from_date"": ""2009-01"",\n ""series_codes"":...",[],saron.csv,data/01_raw/macro,Monthly,True,True,True,True

## 2.3 Intégrité Source ID

In [6]:
unknown_source_ids = (
    set(
        datasets_registry[
            "Source ID"
        ]
        .dropna()
        .astype(str)
    )
    - set(
        sources_registry[
            "Source ID"
        ]
        .dropna()
        .astype(str)
    )
)

if not unknown_source_ids:
    status = "PASS"
    message = (
        "Tous les `Source ID` utilisés dans la feuille "
        "Datasets existent dans la feuille Sources."
    )
else:
    status = "FAIL"
    message = (
        f"**{len(unknown_source_ids)} Source ID inconnu(s)** "
        "détecté(s) : "
        f"`{sorted(unknown_source_ids)}`."
    )

display(
    Markdown(
        f"""
{message}

**Résultat : {status}**
"""
    )
)

Tous les `Source ID` utilisés dans la feuille Datasets existent dans la feuille Sources.

**Résultat : PASS**

## 2.4 Production Methods et dépendances

In [7]:
print("Production Methods:")
print(datasets_registry["Production Method"].value_counts(dropna=False))
print()
print("Active datasets:")
active_mask = datasets_registry["Active"].astype(str).str.upper().isin(["TRUE", "1"])
datasets_registry.loc[active_mask, ["Dataset ID", "Dataset Name", "Production Method", "Input Dataset IDs"]]

Production Methods:
Production Method
API            5
Preparation    3
Download       1
Package        1
Name: count, dtype: int64

Active datasets:

  Dataset ID         Dataset Name Production Method    Input Dataset IDs
0     DS-000   Benchmark Holdings          Download                   []
1     DS-001  Security Candidates       Preparation           ["DS-000"]
2     DS-002     OpenFIGI Mapping               API           ["DS-001"]
3     DS-003      Security Master       Preparation  ["DS-001","DS-002"]
4     DS-004        Market Prices           Package           ["DS-003"]
5     DS-006     Macro Indicators               API                   []
6     DS-008     SEC Fundamentals               API           ["DS-003"]
7     DS-009             FX Rates               API           ["DS-003"]
8     DS-010       ODD Assessment       Preparation           ["DS-003"]
9     DS-011                SARON               API                   []

# 3. Gouvernance SQLite

La base SQLite conserve le registry technique et la traçabilité des exécutions. Les tables métier évoluent avec les datasets chargés et ne doivent pas être supposées à l’avance.

In [8]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        technical_tables = pd.read_sql(
            """
            SELECT name
            FROM sqlite_master
            WHERE type='table'
            ORDER BY name
            """,
            connection,
        )

    display(technical_tables)

else:
    print(
        "Database not found yet:",
        DATABASE_FILE,
    )

                      name
0          acquisition_log
1         dataset_registry
2         fundamentals_sec
3                 fx_rates
4         macro_indicators
5            market_prices
6           odd_assessment
7         openfigi_mapping
8   quality_control_result
9    quality_metric_result
10             quality_run
11                   saron
12       schema_migrations
13       securities_master
14     security_candidates

# 4. DS-000 / SRC-001 – Benchmark Holdings
On vérifie que le benchmark officiel a été acquis dans la couche RAW et on identifie automatiquement sa structure réelle pour la préparation DS-001.

In [9]:
benchmark_file = get_dataset_path(
    "DS-000"
)

if not benchmark_file.exists():
    raise FileNotFoundError(
        benchmark_file
    )

print(
    "Benchmark file:",
    benchmark_file,
)

Benchmark file: C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark\benchmark_holdings.xls

In [10]:
def inspect_file_structure(path: Path) -> dict:
    """
    Detect the physical file format from its content and inspect
    worksheet names when the detected format supports worksheets.
    """

    if not isinstance(path, Path):
        raise TypeError(
            "path must be a pathlib.Path."
        )

    if not path.exists():
        raise FileNotFoundError(path)

    if not path.is_file():
        raise ValueError(
            f"Path is not a file: {path}"
        )

    with path.open("rb") as handle:
        content = handle.read()

    result = {
        "format": None,
        "extension": path.suffix,
        "worksheets": [],
    }

    # Office Open XML / XLSX
    if content.startswith(b"PK\x03\x04"):
        result["format"] = "Office Open XML / XLSX"

        try:
            with zipfile.ZipFile(
                io.BytesIO(content)
            ) as archive:
                workbook_xml = archive.read(
                    "xl/workbook.xml"
                ).decode(
                    "utf-8",
                    errors="ignore",
                )

            result["worksheets"] = re.findall(
                r'<sheet[^>]+name="([^"]+)"',
                workbook_xml,
            )

        except (
            KeyError,
            zipfile.BadZipFile,
        ):
            pass

    # Legacy binary XLS
    elif content.startswith(
        b"\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1"
    ):
        result["format"] = "XLS Binary"

        try:
            workbook = pd.ExcelFile(path)

            result["worksheets"] = (
                workbook.sheet_names
            )

        except Exception:
            pass

    # PDF
    elif content.startswith(b"%PDF-"):
        result["format"] = "PDF"

    # Text-based formats
    else:
        text_content = content

        if text_content.startswith(
            b"\xEF\xBB\xBF"
        ):
            text_content = text_content[3:]

        try:
            text = text_content.decode(
                "utf-8"
            ).lstrip()

        except UnicodeDecodeError:
            result["format"] = (
                "Unknown binary format"
            )

        else:
            lowered = text.casefold()

            # SpreadsheetML XML
            if (
                "<ss:workbook" in lowered
                or (
                    text.startswith("<?xml")
                    and
                    "urn:schemas-microsoft-com:"
                    "office:spreadsheet"
                    in lowered
                )
            ):
                result["format"] = (
                    "SpreadsheetML XML"
                )

                result["worksheets"] = (
                    re.findall(
                        r'Worksheet\s+ss:Name="([^"]+)"',
                        text,
                    )
                )

            # Generic XML
            elif text.startswith("<?xml"):
                result["format"] = "XML"

            # HTML
            elif (
                lowered.startswith(
                    "<!doctype html"
                )
                or lowered.startswith(
                    "<html"
                )
            ):
                result["format"] = "HTML"

            else:
                result["format"] = (
                    "Unknown text format"
                )

    print(
        "Detected format:",
        result["format"],
    )

    print(
        "File extension:",
        result["extension"],
    )

    if result["worksheets"]:
        print(
            "Worksheets:",
            result["worksheets"],
        )

        print(
            "Worksheet count:",
            len(result["worksheets"]),
        )

    return result


benchmark_structure = inspect_file_structure(
    benchmark_file
)

Detected format: SpreadsheetML XML
File extension: .xls
Worksheets: ['Disclaimers', 'Holdings', 'Historical', 'Performance', 'Distributions']
Worksheet count: 5

# 5. DS-001 – Security Candidates

DS-001 est une préparation de DS-000 utilisée comme univers d’entrée pour les acquisitions nécessitant les instruments du benchmark.

In [11]:
security_candidates_file = get_dataset_path(
    "DS-001"
)

if not security_candidates_file.exists():
    raise FileNotFoundError(
        security_candidates_file
    )

security_candidates = pd.read_csv(
    security_candidates_file,
    dtype=str,
    keep_default_na=False,
)

if security_candidates.empty:
    status = "FAIL"
    message = "DS-001 est vide."

else:
    status = "PASS"
    message = (
        f"DS-001 contient "
        f"**{len(security_candidates):,} instruments**."
    )

display(
    security_candidates.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

  Ticker                     Name       Location               Exchange Currency Asset Class
0   MRVL       MARVELL TECHNOLOGY  United States                 NASDAQ      USD      Equity
1   NVDA                   NVIDIA  United States                 NASDAQ      USD      Equity
2   6669       WIWYNN CORPORATION         Taiwan  Taiwan Stock Exchange      USD      Equity
3    TSN  TYSON FOODS INC CLASS A  United States                   NYSE      USD      Equity
4    BMY     BRISTOL MYERS SQUIBB  United States                   NYSE      USD      Equity

DS-001 contient **120 instruments**.

**Résultat : PASS**

In [12]:
exchange_summary = (
    security_candidates["Exchange"]
    .value_counts()
    .rename_axis("Exchange")
    .reset_index(name="securities")
)

print(
    "Distinct exchanges:",
    security_candidates["Exchange"].nunique(),
)

display(exchange_summary)

Distinct exchanges: 29

                                Exchange  securities
0   Hong Kong Exchanges And Clearing Ltd          21
1                                 NASDAQ          14
2                   Tokyo Stock Exchange          10
3                                   NYSE           8
4                Shenzhen Stock Exchange           7
5                Shanghai Stock Exchange           7
6       National Stock Exchange Of India           6
7         Nyse Euronext - Euronext Paris           5
8     Omx Nordic Exchange Copenhagen A/S           4
9                  London Stock Exchange           4
10                 Taiwan Stock Exchange           3
11                    SIX Swiss Exchange           3
12                     Asx - All Markets           3
13                     Nasdaq Omx Nordic           3
14             Bolsa Mexicana De Valores           3
15                         Oslo Bors Asa           2
16                                 Xetra           2
17         Korea Exchange (Stock Market)           2
18     Nyse Euronext - Euronext Brussels           2
19                    Singapore Exchange           2
20                       Bolsa De Madrid           1
21                Toronto Stock Exchange           1
22               Korea Exchange (Kosdaq)           1
23                      Wiener Boerse Ag           1
24       Nyse Euronext - Euronext Lisbon           1
25               Tel Aviv Stock Exchange           1
26           Johannesburg Stock Exchange           1
27                        Borsa Italiana           1
28                  Saudi Stock Exchange           1

# 6. DS-002 / SRC-002 – OpenFIGI Mapping

On vérifie si l’acquisition OpenFIGI conserve toutes les réponses provider avant résolution dans le Security Master.

In [13]:
openfigi_file = get_dataset_path(
    "DS-002"
)

if not openfigi_file.exists():
    raise FileNotFoundError(
        openfigi_file
    )

openfigi_raw = pd.read_csv(
    openfigi_file,
    dtype=str,
    keep_default_na=False,
)

if openfigi_raw.empty:
    status = "FAIL"
    message = "DS-002 est vide."

else:
    status = "PASS"
    message = (
        f"DS-002 contient "
        f"**{len(openfigi_raw):,} lignes de réponses OpenFIGI** "
    )

display(
    openfigi_raw.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,input_position,input_index,id_type,id_value,result_position,figi,ticker,name,exch_code,market_sector,security_type,security_type_2,security_description,composite_figi,share_class_figi,provider_warning,provider_error
0,0,0,TICKER,MRVL,0.0,BBG002JV5037,MRVL,MAVEN RENOVAR VCT PLC,PO,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG000QXL3L5,BBG001SH8BP9,,
1,0,0,TICKER,MRVL,1.0,BBG006T7B0B4,MRVL,MAVEN RENOVAR VCT PLC,B3,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG006T7B097,BBG001SH8BP9,,
2,0,0,TICKER,MRVL,2.0,BBG006TBD390,MRVL,MAVEN RENOVAR VCT PLC,L3,Equity,Closed-End Fund,Mutual Fund,MRVL,BBG006TBD381,BBG001SH8BP9,,
3,0,0,TICKER,MRVL,3.0,BBG00MXMTC99,MRVL,MARVEL BIOSCIENCES CORP,CN,Equity,Common Stock,Common Stock,MRVL,BBG00MXMTC99,BBG00MXMTCB6,,
4,0,0,TICKER,MRVL,4.0,BBG00NGL3MV9,MRVL,MARVEL BIOSCIENCES CORP,CV,Equity,Common Stock,Common Stock,MRVL,BBG00MXMTC99,BBG00MXMTCB6,,

DS-002 contient **2,000 lignes de réponses OpenFIGI**

**Résultat : PASS**

In [14]:
positions = pd.to_numeric(
    openfigi_raw["input_position"],
    errors="raise",
).astype(int)

positions_valid = positions.between(
    0,
    len(security_candidates) - 1,
).all()

expected_tickers = positions.map(
    security_candidates
    .reset_index(drop=True)["Ticker"]
)

ticker_matches = (
    openfigi_raw["id_value"]
    .str.casefold()
    .eq(
        expected_tickers
        .str.casefold()
    )
)

mismatches = int(
    (~ticker_matches).sum()
)

if positions_valid and mismatches == 0:
    status = "PASS"
    message = (
        "La lineage DS-001 → DS-002 est complète : "
        f"**{openfigi_raw['input_position'].nunique():,} "
        "Security Candidates** sont représentés et tous les "
        "`id_value` correspondent au ticker source."
    )
else:
    status = "FAIL"
    message = (
        f"Anomalie de lineage détectée : "
        f"**{mismatches:,} correspondance(s) ticker incorrecte(s)**."
    )

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

La lineage DS-001 → DS-002 est complète : **120 Security Candidates** sont représentés et tous les `id_value` correspondent au ticker source.

**Résultat : PASS**

In [15]:
figi_count = (
    openfigi_raw.loc[
        openfigi_raw["figi"].ne(""),
        "figi",
    ]
    .nunique()
)

summary = pd.Series(
    {
        "Raw mapping rows":
            len(openfigi_raw),
        "Candidate positions represented":
            openfigi_raw["input_position"].nunique(),
        "Distinct non-empty FIGIs":
            openfigi_raw.loc[
                openfigi_raw["figi"].ne(""),
                "figi",
            ].nunique(),
        "Warnings":
            openfigi_raw["provider_warning"].ne("").sum(),
        "Errors":
            openfigi_raw["provider_error"].ne("").sum(),
    }
)

display(summary)

warnings = openfigi_raw.loc[
    openfigi_raw["provider_warning"].ne(""),
    [
        "id_value",
        "provider_warning",
    ],
].drop_duplicates()

errors = openfigi_raw.loc[
    openfigi_raw["provider_error"].ne(""),
    [
        "id_value",
        "provider_error",
    ],
].drop_duplicates()

if not warnings.empty:
    print("Provider warnings:")
    display(warnings)

if not errors.empty:
    print("Provider errors:")
    display(errors)

Raw mapping rows                   2000
Candidate positions represented     120
Distinct non-empty FIGIs           1991
Warnings                              9
Errors                                0
dtype: int64

Provider warnings:

        id_value      provider_warning
451     ESSITY B  No identifier found.
1001         UU.  No identifier found.
1175      SUZLON  No identifier found.
1410       SCA B  No identifier found.
1443  HINDUNILVR  No identifier found.
1846       LUPIN  No identifier found.
1951   NESTLEIND  No identifier found.
1955   FIBRAPL14  No identifier found.
1966      COLPAL  No identifier found.

# 7. DS-003 – Security Master

On vérifie que le Security Master associe correctement les Security Candidates aux résultats OpenFIGI et documente les instruments résolus, ambigus ou non résolus.

In [16]:
security_master_file = get_dataset_path(
    "DS-003"
)

if not security_master_file.exists():
    raise FileNotFoundError(
        security_master_file
    )

security_master = pd.read_csv(
    security_master_file,
    dtype=str,
    keep_default_na=False,
)

if security_master.empty:
    status = "FAIL"
    message = "DS-003 est vide."

else:
    status = "PASS"
    message = (
        f"DS-003 contient "
        f"**{len(security_master):,} instruments**."
    )

display(
    security_master.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,Ticker,Name,Location,Exchange,Currency,listing_currency,Asset Class,figi,composite_figi,share_class_figi,openfigi_ticker,openfigi_name,exch_code,market_sector,security_type,security_type_2,security_description,resolution_status,resolution_rule,mapping_candidates,expected_exch_code,yahoo_symbol
0,MRVL,MARVELL TECHNOLOGY,United States,NASDAQ,USD,USD,Equity,BBG00ZXBJ153,BBG00ZXBJ153,BBG00ZXBJ162,MRVL,MARVELL TECHNOLOGY INC,US,Equity,Common Stock,Common Stock,MRVL,RESOLVED,EXCHANGE_MATCH,1,US,MRVL
1,NVDA,NVIDIA,United States,NASDAQ,USD,USD,Equity,BBG000BBJQV0,BBG000BBJQV0,BBG001S5TZJ6,NVDA,NVIDIA CORP,US,Equity,Common Stock,Common Stock,NVDA,RESOLVED,MARKET_SECTOR_EQUITY_EXCHANGE_MATCH,1,US,NVDA
2,6669,WIWYNN CORPORATION,Taiwan,Taiwan Stock Exchange,USD,TWD,Equity,,,,,,,,,,,AMBIGUOUS,AMBIGUOUS_MULTIPLE_FIGIS,3,TT,6669.TW
3,TSN,TYSON FOODS INC CLASS A,United States,NYSE,USD,USD,Equity,BBG000DKCC19,BBG000DKCC19,BBG001S871D5,TSN,TYSON FOODS INC-CL A,US,Equity,Common Stock,Common Stock,TSN,RESOLVED,MARKET_SECTOR_EQUITY_EXCHANGE_MATCH,1,US,TSN
4,BMY,BRISTOL MYERS SQUIBB,United States,NYSE,USD,USD,Equity,BBG000DQLV23,BBG000DQLV23,BBG001S8N8J6,BMY,BRISTOL-MYERS SQUIBB CO,US,Equity,Common Stock,Common Stock,BMY,RESOLVED,MARKET_SECTOR_EQUITY_EXCHANGE_MATCH,1,US,BMY

DS-003 contient **120 instruments**.

**Résultat : PASS**

In [17]:
resolution_summary = (
    security_master["resolution_status"]
    .value_counts(dropna=False)
    .rename_axis("resolution_status")
    .reset_index(name="records")
)

resolution_summary["percentage"] = (
    resolution_summary["records"]
    / len(security_master)
    * 100
).round(2)

display(resolution_summary)

  resolution_status  records  percentage
0          RESOLVED      100       83.33
1         AMBIGUOUS       11        9.17
2        UNRESOLVED        9        7.50

In [18]:
resolution_rules = (
    security_master["resolution_rule"]
    .value_counts(dropna=False)
    .rename_axis("resolution_rule")
    .reset_index(name="records")
)

display(resolution_rules)

                       resolution_rule  records
0                       EXCHANGE_MATCH       74
1  MARKET_SECTOR_EQUITY_EXCHANGE_MATCH       25
2             AMBIGUOUS_MULTIPLE_FIGIS       11
3                   UNRESOLVED_NO_FIGI        9
4                          UNIQUE_FIGI        1

In [19]:
if "yahoo_symbol" in security_master.columns:
    yahoo_coverage = (
        security_master["yahoo_symbol"]
        .str.strip()
        .ne("")
        .sum()
    )

    print(
        "Yahoo symbols populated:",
        yahoo_coverage,
    )

    display(
        security_master[
            [
                "Ticker",
                "Exchange",
                "resolution_status",
                "yahoo_symbol",
            ]
        ].head(20)
    )

else:
    print(
        "yahoo_symbol is not present "
        "in DS-003."
    )

Yahoo symbols populated: 120

      Ticker                              Exchange resolution_status yahoo_symbol
0       MRVL                                NASDAQ          RESOLVED         MRVL
1       NVDA                                NASDAQ          RESOLVED         NVDA
2       6669                 Taiwan Stock Exchange         AMBIGUOUS      6669.TW
3        TSN                                  NYSE          RESOLVED          TSN
4        BMY                                  NYSE          RESOLVED          BMY
5        VWS    Omx Nordic Exchange Copenhagen A/S          RESOLVED       VWS.CO
6       FSLR                                NASDAQ          RESOLVED         FSLR
7       9020                  Tokyo Stock Exchange          RESOLVED       9020.T
8       NOVN                    SIX Swiss Exchange          RESOLVED      NOVN.SW
9       1216                 Taiwan Stock Exchange         AMBIGUOUS      1216.TW
10       288  Hong Kong Exchanges And Clearing Ltd          RESOLVED      0288.HK
11      2015  Hong Kong Exchanges And Clearing Ltd          RESOLVED      2015.HK
12      9698  Hong Kong Exchanges And Clearing Ltd          RESOLVED      9698.HK
13       KMB                                NASDAQ          RESOLVED          KMB
14      9866  Hong Kong Exchanges And Clearing Ltd          RESOLVED      9866.HK
15      EQIX                                NASDAQ          RESOLVED         EQIX
16       CSL                     Asx - All Markets          RESOLVED       CSL.AX
17      9022                  Tokyo Stock Exchange          RESOLVED       9022.T
18      REGN                                NASDAQ          RESOLVED         REGN
19  ESSITY B                     Nasdaq Omx Nordic        UNRESOLVED  ESSITY-B.ST

# 8. DS-004 / SRC-003B – Yahoo Finance Market Price

Cette section valide l'acquisition des données historiques de marché depuis Yahoo Finance, source principale du dataset `DS-004`.

La validation porte sur quatre dimensions :

1. **présence et exploitabilité de DS-004** ;
2. **couverture d'identité Yahoo** sur les 120 instruments configurés ;
3. **respect de la politique de résolution** (`DIRECT_VALIDATED`, `SEARCH_RESOLVED`, ambiguïtés) ;
4. **disponibilité et traçabilité des historiques effectivement acquis**.

La couverture n'est pas définie comme la capacité à trouver un symbole Yahoo pour chaque instrument.

Seuls les instruments `DIRECT_VALIDATED` sont automatiquement éligibles à l'acquisition. Les `SEARCH_RESOLVED` constituent des propositions de résolution soumises à revue et ne sont pas comptés comme données Yahoo acquises.

L'objectif est donc de mesurer la **couverture fiable** de Yahoo Finance, et non de forcer une couverture de 100 %.

In [20]:
market_prices_file = get_dataset_path(
    "DS-004"
)

if not market_prices_file.exists():
    raise FileNotFoundError(
        market_prices_file
    )

market_prices = pd.read_csv(
    market_prices_file,
    dtype=str,
    keep_default_na=False,
)

if market_prices.empty:
    status = "FAIL"
    message = "DS-004 est vide."
else:
    status = "PASS"
    message = (
        f"DS-004 contient "
        f"**{len(market_prices):,} observations de marché**."
    )

display(
    market_prices.head()
)

display(
    Markdown(
        f"{message}\n\n"
        f"**Résultat : {status}**"
    )
)

,input_position,input_index,configured_symbol,resolved_symbol,symbol_resolution_status,symbol,timestamp,open,high,low,close,adj_close,volume,dividends,stock_splits
0,40,40,9901.HK,9901.HK,DIRECT_VALIDATED,9901.HK,2020-11-09,138.10000610351562,138.8000030517578,131.89999389648438,136.5,135.93299865722656,7736210.0,0.0,0.0
1,40,40,9901.HK,9901.HK,DIRECT_VALIDATED,9901.HK,2020-11-10,133.60000610351562,135.10000610351562,132.3000030517578,134.0,133.44338989257812,2174800.0,0.0,0.0
2,40,40,9901.HK,9901.HK,DIRECT_VALIDATED,9901.HK,2020-11-11,134.0,136.6999969482422,133.0,133.8000030517578,133.24424743652344,1793170.0,0.0,0.0
3,40,40,9901.HK,9901.HK,DIRECT_VALIDATED,9901.HK,2020-11-12,133.60000610351562,134.8000030517578,132.5,134.1999969482422,133.64256286621094,1403200.0,0.0,0.0
4,40,40,9901.HK,9901.HK,DIRECT_VALIDATED,9901.HK,2020-11-13,133.0,133.0,130.0,132.0,131.45172119140625,421500.0,0.0,0.0

DS-004 contient **635,610 observations de marché**.

**Résultat : PASS**

In [21]:
coverage = (
    market_prices[
        [
            "configured_symbol",
            "resolved_symbol",
            "symbol_resolution_status",
        ]
    ]
    .drop_duplicates()
)

display(
    coverage[
        "symbol_resolution_status"
    ].value_counts()
)

configured_count = security_master[
    "yahoo_symbol"
].nunique()

acquired_count = coverage[
    "configured_symbol"
].nunique()

coverage_rate = (
    acquired_count
    / configured_count
    * 100
    if configured_count
    else 0
)

status = (
    "PASS"
    if acquired_count > 0
    and set(
        coverage["symbol_resolution_status"]
    ) == {"DIRECT_VALIDATED"}
    else "FAIL"
)

display(
    Markdown(
        f"DS-004 contient des données pour "
        f"**{acquired_count:,} instruments sur {configured_count:,}**, "
        f"soit **{coverage_rate:.2f} %** de couverture directement validée.\n\n"
        f"**Résultat : {status}**"
    )
)

symbol_resolution_status
DIRECT_VALIDATED    117
Name: count, dtype: int64

DS-004 contient des données pour **117 instruments sur 120**, soit **97.50 %** de couverture directement validée.

**Résultat : PASS**

In [22]:
configured_symbols = set(
    security_master["yahoo_symbol"]
    .astype(str)
    .str.strip()
)

acquired_symbols = set(
    coverage["configured_symbol"]
    .astype(str)
    .str.strip()
)

not_acquired = (
    security_master.loc[
        security_master["yahoo_symbol"].isin(
            configured_symbols - acquired_symbols
        ),
        [
            "Ticker",
            "Name",
            "Exchange",
            "yahoo_symbol",
        ],
    ]
    .sort_values("yahoo_symbol")
    .reset_index(drop=True)
)

display(not_acquired)

status = (
    "PASS"
    if len(not_acquired)
    == configured_count - acquired_count
    else "FAIL"
)

display(
    Markdown(
        f"**{len(not_acquired)} instrument(s)** ne sont pas présents "
        f"dans DS-004 car ils n'ont pas été directement validés "
        f"par le connecteur Yahoo.\n\n"
        f"**Résultat : {status}**"
    )
)

   Ticker                                Name                            Exchange yahoo_symbol
0    CICT  CAPITALAND INTEGRATED COMMERCIAL T                  Singapore Exchange      CICT.SI
1    CLAR            CAPITALAND ASCENDAS REIT                  Singapore Exchange      CLAR.SI
2  ORSTED                          ORSTED A/S  Omx Nordic Exchange Copenhagen A/S    ORSTED.CO

**3 instrument(s)** ne sont pas présents dans DS-004 car ils n'ont pas été directement validés par le connecteur Yahoo.

**Résultat : PASS**

In [23]:
history_coverage = (
    market_prices
    .groupby(
        "configured_symbol",
        as_index=False,
    )
    .agg(
        first_date=("timestamp", "min"),
        last_date=("timestamp", "max"),
        observations=("timestamp", "count"),
    )
)

missing_history = history_coverage.loc[
    history_coverage["observations"].eq(0)
]

status = (
    "PASS"
    if len(history_coverage) == acquired_count
    and missing_history.empty
    else "FAIL"
)

display(
    Markdown(
        f"Les **{len(history_coverage):,} instruments acquis** disposent "
        f"tous d'un historique de marché exploitable.\n\n"
        f"Période globale observée : "
        f"**{history_coverage['first_date'].min()}** à "
        f"**{history_coverage['last_date'].max()}**.\n\n"
        f"**Résultat : {status}**"
    )
)

display(
    history_coverage
    .sort_values("observations")
    .head(10)
    .reset_index(drop=True)
)

Les **117 instruments acquis** disposent tous d'un historique de marché exploitable.

Période globale observée : **1972-06-01** à **2026-10-15**.

**Résultat : PASS**

  configured_symbol  first_date   last_date  observations
0           3750.HK  2025-05-20  2026-10-15           350
1         688472.SS  2023-06-09  2026-10-15           810
2         301358.SZ  2023-02-09  2026-10-15           892
3            URW.PA  2023-04-14  2026-10-15           896
4           9863.HK  2022-09-29  2026-10-15           993
5           9866.HK  2022-03-10  2026-10-15          1130
6         373220.KS  2022-01-27  2026-10-15          1149
7           2082.SR  2021-12-19  2026-10-15          1202
8         688187.SS  2021-09-07  2026-10-15          1233
9              RIVN  2021-11-10  2026-10-14          1236

# 9. DS-006 / SRC-005A - FRED Macro Indicators

Cette section valide l'acquisition des indicateurs macroéconomiques depuis FRED pour le dataset `DS-006`.

Les séries configurées sont :

```text
CPIAUCSL
UNRATE
FEDFUNDS

In [24]:
macro_file = get_dataset_path("DS-006")

if not macro_file.exists():
    raise FileNotFoundError(macro_file)

macro_indicators = pd.read_csv(
    macro_file,
    dtype=str,
    keep_default_na=False,
)

expected_series = {
    "CPIAUCSL",
    "UNRATE",
    "FEDFUNDS",
}

observed_series = set(
    macro_indicators["series_id"]
    .astype(str)
    .str.strip()
)

duplicate_positions = macro_indicators.duplicated(
    subset=["series_id", "observation_position"],
    keep=False,
)

duplicate_dates = macro_indicators.duplicated(
    subset=["series_id", "date"],
    keep=False,
)

missing_source_values = (
    macro_indicators["value"]
    .astype(str)
    .str.strip()
    .eq(".")
)

series_summary = (
    macro_indicators
    .assign(
        missing_source_value=missing_source_values
    )
    .groupby(
        "series_id",
        as_index=False,
    )
    .agg(
        first_date=("date", "min"),
        last_date=("date", "max"),
        observations=("date", "count"),
        missing_values=("missing_source_value", "sum"),
    )
    .sort_values("series_id")
    .reset_index(drop=True)
)

status = (
    "PASS"
    if (
        not macro_indicators.empty
        and observed_series == expected_series
        and not duplicate_positions.any()
        and not duplicate_dates.any()
    )
    else "FAIL"
)

display(series_summary)

display(
    Markdown(
        f"DS-006 contient **{len(macro_indicators):,} observations FRED** "
        f"réparties sur **{len(observed_series)} séries sur "
        f"{len(expected_series)} attendues**.\n\n"
        f"**Séries observées :** {', '.join(sorted(observed_series))}\n\n"
        f"**Valeurs source manquantes (`.`) :** "
        f"{int(missing_source_values.sum()):,}\n\n"
        f"**Doublons techniques :** "
        f"{int(duplicate_positions.sum()):,}\n\n"
        f"**Doublons série/date :** "
        f"{int(duplicate_dates.sum()):,}\n\n"
        f"**Résultat : {status}**"
    )
)

  series_id  first_date   last_date  observations  missing_values
0  CPIAUCSL  1947-01-01  2026-08-01           956               1
1  FEDFUNDS  1954-07-01  2026-08-01           866               0
2    UNRATE  1948-01-01  2026-08-01           944               1

DS-006 contient **2,766 observations FRED** réparties sur **3 séries sur 3 attendues**.

**Séries observées :** CPIAUCSL, FEDFUNDS, UNRATE

**Valeurs source manquantes (`.`) :** 2

**Doublons techniques :** 0

**Doublons série/date :** 0

**Résultat : PASS**

# 12. DS-008 / SRC-004A - SEC EDGAR Company Facts

Cette section valide l'acquisition RAW des Company Facts XBRL depuis SEC EDGAR.

La validation porte sur :

1. la présence et l'exploitabilité de `DS-008` ;
2. la couverture des instruments effectivement acquis ;
3. l'intégrité du lignage `DS-003 → DS-008` ;
4. la cohérence `Ticker → CIK → entité SEC` ;
5. la structure des faits XBRL acquis ;
6. l'absence de doublons techniques et d'anomalies structurantes.

Le connecteur applique désormais une validation d'identité avant toute acquisition de Company Facts :

In [25]:
sec_file = get_dataset_path("DS-008")

if not sec_file.exists():
    raise FileNotFoundError(sec_file)

sec_raw = pd.read_csv(
    sec_file,
    dtype=str,
    keep_default_na=False,
)

SEC_EXPECTED_COLUMNS = [
    "input_position",
    "input_index",
    "input_ticker",
    "cik",
    "entity_name",
    "taxonomy",
    "concept",
    "label",
    "description",
    "unit",
    "start",
    "end",
    "value",
    "accession",
    "fiscal_year",
    "fiscal_period",
    "form",
    "filed",
    "frame",
]

column_contract_valid = (
    list(sec_raw.columns) == SEC_EXPECTED_COLUMNS
)

status = (
    "PASS"
    if (
        not sec_raw.empty
        and column_contract_valid
    )
    else "FAIL"
)

display(sec_raw.head())

display(
    Markdown(
        f"DS-008 contient **{len(sec_raw):,} faits XBRL**.\n\n"
        f"**Securities avec facts :** "
        f"{sec_raw['input_ticker'].nunique():,}\n\n"
        f"**CIK distincts :** "
        f"{sec_raw['cik'].nunique():,}\n\n"
        f"**Colonnes :** "
        f"{len(sec_raw.columns)}\n\n"
        f"**Contrat RAW conforme :** "
        f"{column_contract_valid}\n\n"
        f"**Résultat : {status}**"
    )
)

,input_position,input_index,input_ticker,cik,entity_name,taxonomy,concept,label,description,unit,start,end,value,accession,fiscal_year,fiscal_period,form,filed,frame
0,0,0,MRVL,0001835632,"MARVELL TECHNOLOGY, INC",dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or o...,shares,,2021-06-02,819500000.0,0001835632-21-000010,2022.0,Q1,10-Q,2021-06-09,CY2021Q2I
1,0,0,MRVL,0001835632,"MARVELL TECHNOLOGY, INC",dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or o...,shares,,2021-08-20,823600000.0,0001835632-21-000022,2022.0,Q2,10-Q,2021-08-27,CY2021Q3I
2,0,0,MRVL,0001835632,"MARVELL TECHNOLOGY, INC",dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or o...,shares,,2021-11-26,843800000.0,0001835632-21-000032,2022.0,Q3,10-Q,2021-12-03,CY2021Q4I
3,0,0,MRVL,0001835632,"MARVELL TECHNOLOGY, INC",dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or o...,shares,,2022-03-03,847800000.0,0001835632-22-000016,2022.0,FY,10-K,2022-03-10,CY2022Q1I
4,0,0,MRVL,0001835632,"MARVELL TECHNOLOGY, INC",dei,EntityCommonStockSharesOutstanding,"Entity Common Stock, Shares Outstanding",Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or o...,shares,,2022-05-20,849900000.0,0001835632-22-000028,2023.0,Q1,10-Q,2022-05-27,CY2022Q2I

DS-008 contient **494,279 faits XBRL**.

**Securities avec facts :** 25

**CIK distincts :** 25

**Colonnes :** 19

**Contrat RAW conforme :** True

**Résultat : PASS**

In [26]:
sec_covered_tickers = set(
    sec_raw["input_ticker"]
    .astype(str)
    .str.strip()
)

master_tickers = set(
    security_master["Ticker"]
    .astype(str)
    .str.strip()
)

unexpected_tickers = (
    sec_covered_tickers - master_tickers
)

sec_lineage = (
    sec_raw[
        [
            "input_position",
            "input_ticker",
            "cik",
            "entity_name",
        ]
    ]
    .drop_duplicates()
    .copy()
)

sec_lineage["input_position_int"] = pd.to_numeric(
    sec_lineage["input_position"],
    errors="raise",
).astype(int)

valid_positions = (
    sec_lineage["input_position_int"]
    .between(
        0,
        len(security_master) - 1,
    )
    .all()
)

master_ticker_by_position = (
    security_master
    .reset_index(drop=True)["Ticker"]
    .astype(str)
)

sec_lineage["master_ticker"] = (
    sec_lineage["input_position_int"]
    .map(master_ticker_by_position)
)

sec_lineage["ticker_match"] = (
    sec_lineage["input_ticker"]
    .astype(str)
    .str.casefold()
    ==
    sec_lineage["master_ticker"]
    .astype(str)
    .str.casefold()
)

multiple_ciks = (
    sec_lineage
    .groupby("input_ticker")["cik"]
    .nunique()
    .gt(1)
    .sum()
)

coverage_pct = (
    len(sec_covered_tickers)
    / security_master["Ticker"].nunique()
    * 100
)

status = (
    "PASS"
    if (
        valid_positions
        and sec_lineage["ticker_match"].all()
        and not unexpected_tickers
        and multiple_ciks == 0
    )
    else "FAIL"
)

display(
    Markdown(
        f"**Security Master :** "
        f"{security_master['Ticker'].nunique():,} securities\n\n"
        f"**Securities avec Company Facts :** "
        f"{len(sec_covered_tickers):,}\n\n"
        f"**Couverture RAW SEC :** "
        f"{coverage_pct:.2f} %\n\n"
        f"**Positions DS-003 valides :** "
        f"{valid_positions}\n\n"
        f"**Mismatches de lignage :** "
        f"{int((~sec_lineage['ticker_match']).sum()):,}\n\n"
        f"**Tickers hors DS-003 :** "
        f"{len(unexpected_tickers):,}\n\n"
        f"**Tickers associés à plusieurs CIK :** "
        f"{int(multiple_ciks):,}\n\n"
        f"**Résultat : {status}**"
    )
)

**Security Master :** 120 securities

**Securities avec Company Facts :** 25

**Couverture RAW SEC :** 20.83 %

**Positions DS-003 valides :** True

**Mismatches de lignage :** 17

**Tickers hors DS-003 :** 0

**Tickers associés à plusieurs CIK :** 0

**Résultat : FAIL**

In [27]:
sec_identity = (
    sec_raw
    .groupby("input_ticker")
    .agg(
        distinct_ciks=("cik", "nunique"),
        distinct_entities=("entity_name", "nunique"),
        cik=("cik", "first"),
        entity_name=("entity_name", "first"),
        fact_records=("concept", "size"),
    )
    .reset_index()
    .sort_values(
        "fact_records",
        ascending=False,
    )
    .reset_index(drop=True)
)

multiple_cik_tickers = int(
    sec_identity["distinct_ciks"]
    .gt(1)
    .sum()
)

multiple_entity_tickers = int(
    sec_identity["distinct_entities"]
    .gt(1)
    .sum()
)

status = (
    "PASS"
    if (
        multiple_cik_tickers == 0
        and multiple_entity_tickers == 0
    )
    else "FAIL"
)

display(sec_identity)

display(
    Markdown(
        f"**Securities SEC couvertes :** "
        f"{len(sec_identity):,}\n\n"
        f"**Tickers avec plusieurs CIK :** "
        f"{multiple_cik_tickers:,}\n\n"
        f"**Tickers avec plusieurs entités SEC :** "
        f"{multiple_entity_tickers:,}\n\n"
        f"**Résultat : {status}**"
    )
)

   input_ticker  distinct_ciks  distinct_entities         cik                       entity_name  fact_records
0           BMY              1                  1  0000014272      BRISTOL-MYERS SQUIBB COMPANY         37651
1          EQIX              1                  1  0001101239                     EQUINIX, INC.         32323
2          FSLR              1                  1  0001274494                 First Solar, Inc.         31775
3           MAS              1                  1  0000062996                 Masco Corporation         28701
4          NVDA              1                  1  0001045810                       NVIDIA CORP         27281
5            EW              1                  1  0001099800  Edwards Lifesciences Corporation         26992
6          VRTX              1                  1  0000875320   VERTEX PHARMACEUTICALS INC / MA         25970
7           DLR              1                  1  0001297996        DIGITAL REALTY TRUST, INC.         24663
8           SUI              1                  1  0000912593              SUN COMMUNITIES, INC         24632
9           TSN              1                  1  0000100493                 TYSON FOODS, INC.         23586
10          KMB              1                  1  0000055785        KIMBERLY-CLARK CORPORATION         23575
11           WY              1                  1  0000106535              WEYERHAEUSER COMPANY         22634
12         UTHR              1                  1  0001082554   United Therapeutics Corporation         20826
13         DXCM              1                  1  0001093557                      DEXCOM, INC.         20371
14         INCY              1                  1  0000879169                INCYTE CORPORATION         19702
15         REGN              1                  1  0000872589   REGENERON PHARMACEUTICALS, INC.         19466
16         INSM              1                  1  0001104506                        INSMED INC         17723
17         ALNY              1                  1  0001178670     ALNYLAM PHARMACEUTICALS, INC.         16818
18         NBIX              1                  1  0000914475        NEUROCRINE BIOSCIENCES INC         16543
19         MRVL              1                  1  0001835632           MARVELL TECHNOLOGY, INC          8423
20          TAL              1                  1  0001499620               TAL Education Group          6788
21         RIVN              1                  1  0001874178      Rivian Automotive, Inc. / DE          6215
22         ARGX              1                  1  0001697862                         ARGENX SE          5776
23         GMAB              1                  1  0001434265                        Genmab A/S          3748
24         ENLT              1                  1  0001922641     Enlight Renewable Energy Ltd.          2097

**Securities SEC couvertes :** 25

**Tickers avec plusieurs CIK :** 0

**Tickers avec plusieurs entités SEC :** 0

**Résultat : PASS**

In [28]:
SEC_STRUCTURAL_FIELDS = [
    "input_ticker",
    "cik",
    "entity_name",
    "taxonomy",
    "concept",
    "unit",
    "value",
    "accession",
    "form",
    "filed",
]

missing_summary = pd.DataFrame(
    [
        {
            "field": column,
            "missing_records": int(
                sec_raw[column]
                .astype(str)
                .str.strip()
                .eq("")
                .sum()
            ),
        }
        for column in SEC_STRUCTURAL_FIELDS
    ]
)

missing_summary["missing_pct"] = (
    missing_summary["missing_records"]
    / len(sec_raw)
    * 100
).round(4)

SEC_DUPLICATE_KEY = [
    "input_ticker",
    "cik",
    "taxonomy",
    "concept",
    "unit",
    "start",
    "end",
    "value",
    "accession",
    "form",
    "filed",
    "frame",
]

duplicate_mask = sec_raw.duplicated(
    subset=SEC_DUPLICATE_KEY,
    keep=False,
)

duplicate_rows = int(
    duplicate_mask.sum()
)

duplicate_groups = int(
    sec_raw.loc[
        duplicate_mask,
        SEC_DUPLICATE_KEY,
    ]
    .drop_duplicates()
    .shape[0]
)

structural_missing = int(
    missing_summary["missing_records"].sum()
)

status = (
    "PASS"
    if (
        structural_missing == 0
        and duplicate_rows == 0
    )
    else "FAIL"
)

display(missing_summary)

display(
    Markdown(
        f"**Faits XBRL :** {len(sec_raw):,}\n\n"
        f"**Valeurs structurantes manquantes :** "
        f"{structural_missing:,}\n\n"
        f"**Lignes impliquées dans des doublons exacts :** "
        f"{duplicate_rows:,}\n\n"
        f"**Groupes de doublons exacts :** "
        f"{duplicate_groups:,}\n\n"
        f"**Résultat : {status}**"
    )
)

          field  missing_records  missing_pct
0  input_ticker                0          0.0
1           cik                0          0.0
2   entity_name                0          0.0
3      taxonomy                0          0.0
4       concept                0          0.0
5          unit                0          0.0
6         value                0          0.0
7     accession                0          0.0
8          form                0          0.0
9         filed                0          0.0

**Faits XBRL :** 494,279

**Valeurs structurantes manquantes :** 0

**Lignes impliquées dans des doublons exacts :** 0

**Groupes de doublons exacts :** 0

**Résultat : PASS**

In [29]:
sec_taxonomies = (
    sec_raw["taxonomy"]
    .value_counts(dropna=False)
    .rename_axis("taxonomy")
    .reset_index(name="records")
)

sec_taxonomies["percentage"] = (
    sec_taxonomies["records"]
    / len(sec_raw)
    * 100
).round(2)


sec_forms = (
    sec_raw["form"]
    .value_counts(dropna=False)
    .rename_axis("form")
    .reset_index(name="records")
)

sec_forms["percentage"] = (
    sec_forms["records"]
    / len(sec_raw)
    * 100
).round(2)


sec_temporal = pd.DataFrame(
    {
        "field": [
            "filed",
            "end",
            "start",
            "fiscal_year",
            "fiscal_period",
            "frame",
        ],
        "available_records": [
            sec_raw["filed"].ne("").sum(),
            sec_raw["end"].ne("").sum(),
            sec_raw["start"].ne("").sum(),
            sec_raw["fiscal_year"].ne("").sum(),
            sec_raw["fiscal_period"].ne("").sum(),
            sec_raw["frame"].ne("").sum(),
        ],
    }
)

sec_temporal["availability_pct"] = (
    sec_temporal["available_records"]
    / len(sec_raw)
    * 100
).round(2)


display(
    Markdown(
        "**Taxonomies XBRL**"
    )
)

display(sec_taxonomies)


display(
    Markdown(
        "**Principaux formulaires SEC**"
    )
)

display(sec_forms.head(15))


display(
    Markdown(
        "**Disponibilité des champs temporels**"
    )
)

display(sec_temporal)

**Taxonomies XBRL**

    taxonomy  records  percentage
0    us-gaap   480483       97.21
1  ifrs-full    11598        2.35
2        dei     1644        0.33
3        ecd      337        0.07
4        ffd       93        0.02
5        srt       63        0.01
6     invest       61        0.01

**Principaux formulaires SEC**

       form  records  percentage
0      10-Q   293917       59.46
1      10-K   175579       35.52
2      20-F    13520        2.74
3       6-K     4478        0.91
4       8-K     3165        0.64
5    10-Q/A     1496        0.30
6    10-K/A     1231        0.25
7    20-F/A      406        0.08
8   DEF 14A      392        0.08
9     424B5       23        0.00
10      S-8       20        0.00
11    424B7       18        0.00
12    424B2       12        0.00
13   S-3ASR       10        0.00
14  SC TO-T        5        0.00

**Disponibilité des champs temporels**

           field  available_records  availability_pct
0          filed             494279            100.00
1            end             494279            100.00
2          start             300490             60.79
3    fiscal_year             491364             99.41
4  fiscal_period             491364             99.41
5          frame             208156             42.11

In [30]:
sec_uncovered = (
    security_master[
        ~security_master["Ticker"].isin(
            sec_covered_tickers
        )
    ]
    [
        [
            "Ticker",
            "Name",
            "Location",
            "Exchange",
            "resolution_status",
        ]
    ]
    .sort_values(
        [
            "Location",
            "Exchange",
            "Ticker",
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

coverage_pct = (
    len(sec_covered_tickers)
    / security_master["Ticker"].nunique()
    * 100
)

display(sec_uncovered)

display(
    Markdown(
        f"**Securities DS-003 :** "
        f"{security_master['Ticker'].nunique():,}\n\n"
        f"**Couvertes par DS-008 :** "
        f"{len(sec_covered_tickers):,}\n\n"
        f"**Sans Company Facts DS-008 :** "
        f"{len(sec_uncovered):,}\n\n"
        f"**Couverture SEC :** "
        f"{coverage_pct:.2f} %"
    )
)

        Ticker                                Name        Location                              Exchange resolution_status
0          CSL                                 CSL       Australia                     Asx - All Markets          RESOLVED
1          SCG                       SCENTRE GROUP       Australia                     Asx - All Markets          RESOLVED
2          VCX                    VICINITY CENTRES       Australia                     Asx - All Markets          RESOLVED
3          VER                          VERBUND AG         Austria                      Wiener Boerse Ag          RESOLVED
4          ELI                       ELIA GROUP SA         Belgium     Nyse Euronext - Euronext Brussels          RESOLVED
5          SAP                              SAPUTO          Canada                Toronto Stock Exchange          RESOLVED
6         1044          HENGAN INTERNATIONAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
7         1093           CSPC PHARMACEUTICAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
8         1585                YADEA GROUP HOLDINGS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
9         1801                  INNOVENT BIOLOGICS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
10        2015                     LI AUTO CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
11        2319             CHINA MENGNIU DAIRY LTD           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
12         322    TINGYI (CAYMAN ISLANDS) HOLDINGS           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
13        3692         HANSOH PHARMACEUTICAL GROUP           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
14        3750  CONTEMPORARY AMPEREX TECHNOLOGY CL           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
15        3898   ZHUZHOU CRRC TIMES ELECTRIC LTD H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
16        6160                  BEONE MEDICINES AG           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
17         916        CHINA LONGYUAN POWER GROUP H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
18        9633                 NONGFU SPRING LTD H           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
19        9698                GDS HOLDINGS CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
20        9863   ZHEJIANG LEAPMOTOR TECHNOLOGY LTD           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
21        9866                         NIO CLASS A           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
22        9868                   XPENG CLASS A INC           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
23        9901  NEW ORIENTAL EDUCATION & TECHNOLOG           China  Hong Kong Exchanges And Clearing Ltd          RESOLVED
24      600905  CHINA THREE GORGES RENEWABLES(GROU           China               Shanghai Stock Exchange          RESOLVED
25      601127                       SERES GROUP A           China               Shanghai Stock Exchange          RESOLVED
26      603806  HANGZHOU FIRST APPLIED MATERIAL LT           China               Shanghai Stock Exchange          RESOLVED
27      605117       NINGBO DEYE TECHNOLOGY CORP A           China               Shanghai Stock Exchange          RESOLVED
28      688187   ZHUZHOU CRRC TIMES ELECTRIC LTD A           China               Shanghai Stock Exchange          RESOLVED
29      688472                     CSI SOLAR LTD A           China               Shanghai Stock Exchange          RESOLVED
30      688578  SHANGHAI ALLIST PHARMACEUTICALS LT           China               Shanghai Stock Exchange          RESOLVED
31      000895  HENAN SHUANGHUI INVESTMENT & DEVEL           China               Shenzhen Stock Exchange         AMBIGUOUS
32      001979   CHINA MERCHANTS SHEKOU INDUSTRIAL           China               Shenzhen Stock Exchange         AMBIGUOUS
33      002129  TCL ZHONGHUAN RENEWABLE ENERGY TEC           China               Shenzhen Stock Exchange         AMBIGUOUS
34      002202   GOLDWIND SCIENCE&TECHNOLOGY LTD A           China               Shenzhen Stock Exchange         AMBIGUOUS
35      300274          SUNGROW POWER SUPPLY LTD A           China               Shenzhen Stock Exchange         AMBIGUOUS
36      300750   CONTEMPORARY AMPEREX TECHNOLOGY A           China               Shenzhen Stock Exchange         AMBIGUOUS
37      301358  HUNAN YUNENG NEW ENERGY BATTERY MA           China               Shenzhen Stock Exchange         AMBIGUOUS
38      DEMANT                              DEMANT         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
39      ORSTED                          ORSTED A/S         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
40         VWS                 VESTAS WIND SYSTEMS         Denmark    Omx Nordic Exchange Copenhagen A/S          RESOLVED
41         COV                          COVIVIO SA          France        Nyse Euronext - Euronext Paris          RESOLVED
42         GFC                           GECINA SA          France        Nyse Euronext - Euronext Paris          RESOLVED
43         IPN                            IPSEN SA          France        Nyse Euronext - Euronext Paris          RESOLVED
44          LI                   KLEPIERRE REIT SA          France        Nyse Euronext - Euronext Paris          RESOLVED
45         URW    UNIBAIL RODAMCO WE STAPLED UNITS          France        Nyse Euronext - Euronext Paris          RESOLVED
46         HOT                         HOCHTIEF AG         Germany                                 Xetra          RESOLVED
47         VNA                          VONOVIA SE         Germany                                 Xetra          RESOLVED
48          12      HENDERSON LAND DEVELOPMENT LTD       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
49         288                            WH GROUP       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
50          66                     MTR CORPORATION       Hong Kong  Hong Kong Exchanges And Clearing Ltd          RESOLVED
51      COLPAL         COLGATE PALMOLIVE INDIA LTD           India      National Stock Exchange Of India        UNRESOLVED
52  HINDUNILVR              HINDUSTAN UNILEVER LTD           India      National Stock Exchange Of India        UNRESOLVED
53       LODHA                LODHA DEVELOPERS LTD           India      National Stock Exchange Of India          RESOLVED
54       LUPIN                               LUPIN           India      National Stock Exchange Of India        UNRESOLVED
55   NESTLEIND                    NESTLE INDIA LTD           India      National Stock Exchange Of India        UNRESOLVED
56      SUZLON                       SUZLON ENERGY           India      National Stock Exchange Of India        UNRESOLVED
57         REC  RECORDATI INDUSTRIA CHIMICA E FARM           Italy                        Borsa Italiana          RESOLVED
58        4151                     KYOWA KIRIN LTD           Japan                  Tokyo Stock Exchange          RESOLVED
59        4507                            SHIONOGI           Japan                  Tokyo Stock Exchange          RESOLVED
60        4519           CHUGAI PHARMACEUTICAL LTD           Japan                  Tokyo Stock Exchange          RESOLVED
61        4523                               EISAI           Japan                  Tokyo Stock Exchange          RESOLVED
62        4543                              TERUMO           Japan                  Tokyo Stock Exchange          RESOLVED
63        4568                  DAIICHI SANKYO LTD           Japan                  Tokyo Stock Exchange          RESOLVED
64        8113                            UNICHARM           Japan                  Tokyo Stock Exchange          RESOLVED
65        8951           NIPPON BUILDING FUND REIT           Japan                  Tokyo Stock Exchange          RESOLVED
66        9020                  EAST JAPAN RAILWAY           Japan                  Tokyo Stock Exchange          RESOLVED
67        9022               CENTRAL JAPAN RAILWAY           Japan                  Tokyo Stock Exchange          RESOLVED
68      247540                       ECOPRO BM LTD   Korea (South)               Korea Exchange (Kosdaq)          RESOLVED
69      010120                     LS ELECTRIC LTD   Korea (South)         Korea Exchange (Stock Market)          RESOLVED
70      373220              LG ENERGY SOLUTION LTD   Korea (South)         Korea Exchange (Stock Market)          RESOLVED
71   FIBRAPL14       PROLOGIS PROPERTY MEXICO REIT          Mexico             Bolsa Mexicana De Valores        UNRESOLVED
72     KIMBERA    KIMBERLY-CLARK DE MEXICO CLASS A          Mexico             Bolsa Mexicana De Valores          RESOLVED
73     SIGMAFA                              ALFA A          Mexico             Bolsa Mexicana De Valores          RESOLVED
74        MOWI                                MOWI          Norway                         Oslo Bors Asa          RESOLVED
75        SALM                              SALMAR          Norway                         Oslo Bors Asa          RESOLVED
76        EDPR                   EDP RENEWABLES SA        Portugal       Nyse Euronext - Euronext Lisbon          RESOLVED
77        2082                       ACWA POWER CO    Saudi Arabia                  Saudi Stock Exchange         AMBIGUOUS
78        CICT  CAPITALAND INTEGRATED COMMERCIAL T       Singapore                    Singapore Exchange          RESOLVED
79        CLAR            CAPITALAND ASCENDAS REIT       Singapore                    Singapore Exchange          RESOLVED
80         NRP                     NEPI ROCKCASTLE    South Africa           Johannesburg Stock Exchange          RESOLVED
81         ANA                             ACCIONA           Spain                       Bolsa De Madrid          RESOLVED
82    ESSITY B                      ESSITY CLASS B          Sweden                     Nasdaq Omx Nordic        UNRESOLVED
83       SCA B                 SVENSKA CELLULOSA B          Sweden                     Nasdaq Omx Nordic        UNRESOLVED
84        SOBI            SWEDISH ORPHAN BIOVITRUM          Sweden                     Nasdaq Omx Nordic          RESOLVED
85        NOVN                         NOVARTIS AG     Switzerland                    SIX Swiss Exchange          RESOLVED
86        SOON                   SONOVA HOLDING AG     Switzerland                    SIX Swiss Exchange          RESOLVED
87        SPSN                 SWISS PRIME SITE AG     Switzerland                    SIX Swiss Exchange          RESOLVED
88        1216           UNI-PRESIDENT ENTERPRISES          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
89        6446                      PHARMAESSENTIA          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
90        6669                  WIWYNN CORPORATION          Taiwan                 Taiwan Stock Exchange         AMBIGUOUS
91        LAND      LAND SECURITIES GROUP REIT PLC  United Kingdom                 London Stock Exchange          RESOLVED
92        PSON                         PEARSON PLC  United Kingdom                 London Stock Exchange          RESOLVED
93        SGRO                      SEGRO REIT PLC  United Kingdom                 London Stock Exchange          RESOLVED
94         UU.          UNITED UTILITIES GROUP PLC  United Kingdom                 London Stock Exchange        UNRESOLVED

**Securities DS-003 :** 120

**Couvertes par DS-008 :** 25

**Sans Company Facts DS-008 :** 95

**Couverture SEC :** 20.83 %

In [31]:
gap_market_summary = (
    sec_uncovered
    .groupby(
        [
            "Location",
            "Exchange",
        ],
        dropna=False,
    )
    .agg(
        securities=("Ticker", "size")
    )
    .reset_index()
)

gap_market_summary["gap_pct"] = (
    gap_market_summary["securities"]
    / len(sec_uncovered)
    * 100
).round(2)

gap_market_summary = (
    gap_market_summary
    .sort_values(
        [
            "securities",
            "Location",
            "Exchange",
        ],
        ascending=[
            False,
            True,
            True,
        ],
        kind="stable",
    )
    .reset_index(drop=True)
)

gap_location_summary = (
    sec_uncovered
    .groupby(
        "Location",
        dropna=False,
    )
    .agg(
        securities=("Ticker", "size"),
        markets=("Exchange", "nunique"),
    )
    .reset_index()
)

gap_location_summary["gap_pct"] = (
    gap_location_summary["securities"]
    / len(sec_uncovered)
    * 100
).round(2)

gap_location_summary = (
    gap_location_summary
    .sort_values(
        "securities",
        ascending=False,
        kind="stable",
    )
    .reset_index(drop=True)
)

display(
    Markdown(
        "**Gaps par juridiction**"
    )
)

display(gap_location_summary)

display(
    Markdown(
        "**Gaps par marché**"
    )
)

display(gap_market_summary)

**Gaps par juridiction**

          Location  securities  markets  gap_pct
0            China          32        3    33.68
1            Japan          10        1    10.53
2            India           6        1     6.32
3           France           5        1     5.26
4   United Kingdom           4        1     4.21
5        Australia           3        1     3.16
6          Denmark           3        1     3.16
7        Hong Kong           3        1     3.16
8    Korea (South)           3        2     3.16
9           Mexico           3        1     3.16
10          Sweden           3        1     3.16
11     Switzerland           3        1     3.16
12          Taiwan           3        1     3.16
13         Germany           2        1     2.11
14          Norway           2        1     2.11
15       Singapore           2        1     2.11
16         Austria           1        1     1.05
17         Belgium           1        1     1.05
18          Canada           1        1     1.05
19           Italy           1        1     1.05
20        Portugal           1        1     1.05
21    Saudi Arabia           1        1     1.05
22    South Africa           1        1     1.05
23           Spain           1        1     1.05

**Gaps par marché**

          Location                              Exchange  securities  gap_pct
0            China  Hong Kong Exchanges And Clearing Ltd          18    18.95
1            Japan                  Tokyo Stock Exchange          10    10.53
2            China               Shanghai Stock Exchange           7     7.37
3            China               Shenzhen Stock Exchange           7     7.37
4            India      National Stock Exchange Of India           6     6.32
5           France        Nyse Euronext - Euronext Paris           5     5.26
6   United Kingdom                 London Stock Exchange           4     4.21
7        Australia                     Asx - All Markets           3     3.16
8          Denmark    Omx Nordic Exchange Copenhagen A/S           3     3.16
9        Hong Kong  Hong Kong Exchanges And Clearing Ltd           3     3.16
10          Mexico             Bolsa Mexicana De Valores           3     3.16
11          Sweden                     Nasdaq Omx Nordic           3     3.16
12     Switzerland                    SIX Swiss Exchange           3     3.16
13          Taiwan                 Taiwan Stock Exchange           3     3.16
14         Germany                                 Xetra           2     2.11
15   Korea (South)         Korea Exchange (Stock Market)           2     2.11
16          Norway                         Oslo Bors Asa           2     2.11
17       Singapore                    Singapore Exchange           2     2.11
18         Austria                      Wiener Boerse Ag           1     1.05
19         Belgium     Nyse Euronext - Euronext Brussels           1     1.05
20          Canada                Toronto Stock Exchange           1     1.05
21           Italy                        Borsa Italiana           1     1.05
22   Korea (South)               Korea Exchange (Kosdaq)           1     1.05
23        Portugal       Nyse Euronext - Euronext Lisbon           1     1.05
24    Saudi Arabia                  Saudi Stock Exchange           1     1.05
25    South Africa           Johannesburg Stock Exchange           1     1.05
26           Spain                       Bolsa De Madrid           1     1.05

**Je gèle la chasse aux fundamentals internationaux jusqu'à ce que le pipeline complet fonctionne de bout en bout. Ensuite, à la fin du projet, je reviendrai enrichir les sources avec une architecture déjà solide.**

# 13. DS-009 / SRC-006A – SNB FX Rates

Cette section valide l'acquisition des cours de change CHF depuis le portail de données de la BNS pour le dataset `DS-009`.

Les devises demandées viennent de `listing_currency` dans DS-003. `snb_currency_codes` traduit chaque code ISO vers le code du cube BNS. La devise de reporting n'est pas demandée. Une devise de cotation absente de cette table n'est pas envoyée au fournisseur ; la cellule la montre comme un écart de couverture, pas comme un échec du téléchargement.

La sortie sépare deux unités. Une **série** est un cours de change (une devise). Un **titre** est une ligne du master. Plusieurs titres partagent la même série. Ces deux nombres ne s'additionnent pas.

Les cours restent dans l'unité publiée : `USD1` signifie 1 dollar, `JPY100` signifie 100 yens. La division par 100 n'est pas faite à l'acquisition.

In [32]:
fx_file = get_dataset_path("DS-009")

if not fx_file.exists():
    raise FileNotFoundError(fx_file)

fx_rates = pd.read_csv(
    fx_file,
    dtype=str,
    keep_default_na=False,
)

fx_row = datasets_registry.loc[
    datasets_registry["Dataset ID"].eq("DS-009")
]

if len(fx_row) != 1:
    raise ValueError(
        "Expected exactly one DS-009 registry row."
    )

raw_parameters = fx_row.iloc[0]["Parameters"]

fx_parameters = (
    json.loads(raw_parameters)
    if isinstance(raw_parameters, str)
    else dict(raw_parameters)
)

configured_cube = str(
    fx_parameters["cube_id"]
).strip()

security_master = pd.read_csv(
    get_dataset_path("DS-003"),
    dtype=str,
    keep_default_na=False,
)

currency_column = str(
    fx_parameters["currency_column"]
).strip()

reporting_currency = str(
    fx_parameters["reporting_currency"]
).strip()

configured_frequency_code = str(
    fx_parameters["frequency_code"]
).strip()

code_map = {
    str(currency).strip(): str(code).strip()
    for currency, code in fx_parameters["snb_currency_codes"].items()
}

listing_currencies = sorted(
    set(
        security_master[currency_column]
        .astype(str)
        .str.strip()
    )
)

unmapped_currencies = [
    currency
    for currency in listing_currencies
    if currency != reporting_currency
    and currency not in code_map
]

configured_currency_codes = {
    code_map[currency]
    for currency in listing_currencies
    if currency != reporting_currency
    and currency in code_map
}

fx_gap = (
    security_master.loc[
        security_master[currency_column].isin(
            unmapped_currencies
        ),
        ["Ticker", "Name", "Exchange", currency_column],
    ]
    .sort_values([currency_column, "Ticker"])
    .reset_index(drop=True)
)

def published_dimension_codes(series_key):
    match = re.fullmatch(
        r"[^{]+\{([^,]+),([^}]+)\}",
        str(series_key).strip(),
    )
    if match is None:
        raise ValueError(
            f"Unexpected SNB series key: {series_key}"
        )
    return match.group(1), match.group(2)

parsed_keys = fx_rates["series_key"].map(
    published_dimension_codes
)

observed_frequency_codes = {
    item[0] for item in parsed_keys
}

observed_currency_codes = {
    item[1] for item in parsed_keys
}

observed_series = set(
    fx_rates["series_key"].astype(str).str.strip()
)

duplicate_positions = fx_rates.duplicated(
    subset=["series_key", "value_position"],
    keep=False,
)

duplicate_dates = fx_rates.duplicated(
    subset=["series_key", "date"],
    keep=False,
)

missing_source_values = (
    fx_rates["value"].astype(str).str.strip().eq("")
)

numeric_values = pd.to_numeric(
    fx_rates["value"],
    errors="coerce",
)

series_summary = (
    fx_rates
    .assign(missing_source_value=missing_source_values)
    .groupby("series_key", as_index=False)
    .agg(
        first_date=("date", "min"),
        last_date=("date", "max"),
        observations=("date", "count"),
        missing_values=("missing_source_value", "sum"),
    )
    .sort_values("series_key")
    .reset_index(drop=True)
)

published_units = set(
    fx_rates["unit"].astype(str).str.strip()
)

published_labels = set(
    fx_rates["header_item_1"].astype(str).str.strip()
)

published_frequencies = set(
    fx_rates["frequency"].astype(str).str.strip()
)

contract_ok = (
    set(fx_rates["cube_id"].astype(str).str.strip())
    == {configured_cube}
    and observed_frequency_codes == {configured_frequency_code}
    and observed_currency_codes == configured_currency_codes
    and len(observed_series) == len(configured_currency_codes)
    and len(published_units) == 1
    and "" not in published_units
    and len(published_labels) == 1
    and "" not in published_labels
    and len(published_frequencies) == 1
    and "" not in published_frequencies
    and bool(numeric_values.notna().all())
)

status = (
    "PASS"
    if (
        not fx_rates.empty
        and not duplicate_positions.any()
        and not duplicate_dates.any()
        and contract_ok
    )
    else "FAIL"
)

code_to_currency = {
    code: currency
    for currency, code in code_map.items()
}

series_summary.insert(
    0,
    "listing_currency",
    series_summary["series_key"].map(
        lambda series_key: code_to_currency[
            published_dimension_codes(series_key)[1]
        ]
    ),
)

title_counts = (
    security_master[currency_column]
    .astype(str)
    .str.strip()
    .value_counts()
)

series_summary.insert(
    1,
    "titles",
    series_summary["listing_currency"].map(title_counts).astype(int),
)

mapped_currencies = [
    currency
    for currency in listing_currencies
    if currency != reporting_currency and currency in code_map
]

reporting_titles = int(
    security_master[currency_column]
    .astype(str)
    .str.strip()
    .eq(reporting_currency)
    .sum()
)

mapped_titles = int(
    security_master[currency_column]
    .astype(str)
    .str.strip()
    .isin(mapped_currencies)
    .sum()
)

coverage = pd.DataFrame(
    [
        {
            "groupe": "Série BNS publiée",
            "devises": len(mapped_currencies),
            "titres": mapped_titles,
            "note": (
                "Une série par devise. "
                "La colonne titres compte les lignes du master."
            ),
        },
        {
            "groupe": "Déjà en devise de reporting",
            "devises": int(reporting_currency in listing_currencies),
            "titres": reporting_titles,
            "note": (
                f"{reporting_currency} n'a pas de cours "
                f"{reporting_currency}/{reporting_currency}."
            ),
        },
        {
            "groupe": "Devise absente du cube BNS",
            "devises": len(unmapped_currencies),
            "titres": len(fx_gap),
            "note": (
                "Écart de couverture affiché ensuite. "
                "Ce n'est pas un échec du téléchargement."
            ),
        },
        {
            "groupe": "Total master DS-003",
            "devises": len(listing_currencies),
            "titres": len(security_master),
            "note": (
                "Somme des trois lignes. "
                "Devises et titres ne s'additionnent pas entre eux."
            ),
        },
    ]
)

missing_codes = ", ".join(unmapped_currencies) or "aucune"

display(
    Markdown(
        "**Comment lire ce résultat.** "
        "Une série est un cours de change. "
        "Un titre est une ligne du master. "
        "Plusieurs titres partagent la même série, "
        "donc le nombre de séries et le nombre de titres "
        "ne se combinent pas."
    )
)
display(coverage)

display(
    Markdown(
        "**Séries publiées.** "
        "Une ligne = une devise demandée à la BNS. "
        "`titles` indique combien de titres du master utilisent cette devise."
    )
)
display(series_summary)

display(
    Markdown(
        "**Titres sans cours BNS.** "
        "Une ligne = un titre. "
        f"Ces {len(fx_gap)} titres portent {len(unmapped_currencies)} devises "
        f"({missing_codes}), pas {len(fx_gap)} séries manquantes."
    )
)
display(fx_gap)

display(
    Markdown(
        f"DS-009 contient **{len(fx_rates):,} observations** "
        f"sur **{len(observed_series)} séries**, "
        f"soit les **{len(configured_currency_codes)} devises** "
        f"du master présentes dans `snb_currency_codes`.\n\n"
        f"**Cube :** {configured_cube}, code {configured_frequency_code}\n\n"
        f"**Période :** {fx_rates['date'].min()} → {fx_rates['date'].max()}\n\n"
        f"**Unité publiée :** {next(iter(published_units))}\n\n"
        f"**Valeurs vides :** {int(missing_source_values.sum()):,}\n\n"
        f"**Doublons techniques :** {int(duplicate_positions.sum()):,}\n\n"
        f"**Doublons série/date :** {int(duplicate_dates.sum()):,}\n\n"
        f"**Résultat : {status}** — "
        "les séries demandées sont toutes présentes. "
        "L'écart de couverture reste visible dans le tableau du haut."
    )
)

**Comment lire ce résultat.** Une série est un cours de change. Un titre est une ligne du master. Plusieurs titres partagent la même série, donc le nombre de séries et le nombre de titres ne se combinent pas.

                        groupe  devises  titres                                                                           note
0            Série BNS publiée       15     106           Une série par devise. La colonne titres compte les lignes du master.
1  Déjà en devise de reporting        1       3                                                  CHF n'a pas de cours CHF/CHF.
2   Devise absente du cube BNS        4      11  Écart de couverture affiché ensuite. Ce n'est pas un échec du téléchargement.
3          Total master DS-003       20     120     Somme des trois lignes. Devises et titres ne s'additionnent pas entre eux.

**Séries publiées.** Une ligne = une devise demandée à la BNS. `titles` indique combien de titres du master utilisent cette devise.

   listing_currency  titles                 series_key first_date last_date  observations  missing_values
0               AUD       3    EPB@SNB.devkum{M1,AUD1}    1992-01   2026-09           417               0
1               CAD       1    EPB@SNB.devkum{M1,CAD1}    1970-01   2026-09           680               0
2               CNY      14  EPB@SNB.devkum{M1,CNY100}    1998-12   2026-09           334               0
3               DKK       4  EPB@SNB.devkum{M1,DKK100}    1970-01   2026-09           680               0
4               EUR      13    EPB@SNB.devkum{M1,EUR1}    1999-01   2026-09           333               0
5               GBP       4    EPB@SNB.devkum{M1,GBP1}    1970-01   2026-09           680               0
6               HKD      21  EPB@SNB.devkum{M1,HKD100}    1999-01   2026-09           333               0
7               JPY      10  EPB@SNB.devkum{M1,JPY100}    1972-01   2026-09           656               0
8               KRW       3  EPB@SNB.devkum{M1,KRW100}    1999-01   2026-09           333               0
9               MXN       3  EPB@SNB.devkum{M1,MXN100}    1999-01   2026-09           333               0
10              NOK       2  EPB@SNB.devkum{M1,NOK100}    1970-01   2026-09           680               0
11              SEK       3  EPB@SNB.devkum{M1,SEK100}    1970-01   2026-09           680               0
12              SGD       2    EPB@SNB.devkum{M1,SGD1}    1999-01   2026-09           333               0
13              USD      22    EPB@SNB.devkum{M1,USD1}    1970-01   2026-09           680               0
14              ZAR       1    EPB@SNB.devkum{M1,ZAR1}    1992-07   2026-09           411               0

**Titres sans cours BNS.** Une ligne = un titre. Ces 11 titres portent 4 devises (ILS, INR, SAR, TWD), pas 11 séries manquantes.

        Ticker                         Name                          Exchange listing_currency
0         ENLT     ENLIGHT RENEWABLE ENERGY           Tel Aviv Stock Exchange              ILS
1       COLPAL  COLGATE PALMOLIVE INDIA LTD  National Stock Exchange Of India              INR
2   HINDUNILVR       HINDUSTAN UNILEVER LTD  National Stock Exchange Of India              INR
3        LODHA         LODHA DEVELOPERS LTD  National Stock Exchange Of India              INR
4        LUPIN                        LUPIN  National Stock Exchange Of India              INR
5    NESTLEIND             NESTLE INDIA LTD  National Stock Exchange Of India              INR
6       SUZLON                SUZLON ENERGY  National Stock Exchange Of India              INR
7         2082                ACWA POWER CO              Saudi Stock Exchange              SAR
8         1216    UNI-PRESIDENT ENTERPRISES             Taiwan Stock Exchange              TWD
9         6446               PHARMAESSENTIA             Taiwan Stock Exchange              TWD
10        6669           WIWYNN CORPORATION             Taiwan Stock Exchange              TWD

DS-009 contient **7,563 observations** sur **15 séries**, soit les **15 devises** du master présentes dans `snb_currency_codes`.

**Cube :** devkum, code M1

**Période :** 1970-01 → 2026-09

**Unité publiée :** Rates at 11 am. in CHF

**Valeurs vides :** 0

**Doublons techniques :** 0

**Doublons série/date :** 0

**Résultat : PASS** — les séries demandées sont toutes présentes. L'écart de couverture reste visible dans le tableau du haut.

# 14. DS-010 / SRC-007 – ODD Assessment

Cette section valide le registre d'évaluation ODD. SRC-007 n'a pas d'endpoint unique : les rapports annuels, les rapports de durabilité et les sites des sociétés ne passent pas par un connecteur.

La préparation part de DS-003 et ouvre une ligne par titre. Les colonnes de preuve restent vides. Le code ne décide ni l'ODD, ni la contribution, ni l'éligibilité. Une nouvelle exécution conserve les preuves déjà saisies et ajoute seulement les titres qui manquent.

`ISIN` est prévu par l'architecture, mais le master ne le fournit pas. La colonne reste vide. L'identité du registre est `Ticker` + `Exchange`.

In [33]:
odd_file = get_dataset_path("DS-010")

if not odd_file.exists():
    raise FileNotFoundError(odd_file)

odd_assessment = pd.read_csv(
    odd_file,
    dtype=str,
    keep_default_na=False,
)

odd_row = datasets_registry.loc[
    datasets_registry["Dataset ID"].eq("DS-010")
]

if len(odd_row) != 1:
    raise ValueError(
        "Expected exactly one DS-010 registry row."
    )

if str(odd_row.iloc[0]["Production Method"]).strip() != "Preparation":
    raise ValueError("DS-010 must be a Preparation dataset.")

if str(odd_row.iloc[0]["Connector"]).strip() not in {"", "nan", "None"}:
    raise ValueError("DS-010 must not declare a connector.")

security_master = pd.read_csv(
    get_dataset_path("DS-003"),
    dtype=str,
    keep_default_na=False,
)

evidence_columns = [
    "SDG",
    "Activity",
    "Positive Contribution",
    "Negative Contribution",
    "Evidence",
    "Source",
    "Controversy",
    "Data Quality",
    "Status",
]

expected_columns = [
    "Ticker",
    "Exchange",
    "figi",
    "ISIN",
    "Company",
    *evidence_columns,
]

master_identity = set(
    zip(
        security_master["Ticker"].str.strip(),
        security_master["Exchange"].str.strip(),
    )
)

register_identity = set(
    zip(
        odd_assessment["Ticker"].str.strip(),
        odd_assessment["Exchange"].str.strip(),
    )
)

filled_evidence = odd_assessment[evidence_columns].ne("").any(axis=1)

duplicate_assessment = odd_assessment.duplicated(
    subset=["Ticker", "Exchange", "SDG"],
    keep=False,
)

contract_ok = (
    list(odd_assessment.columns) == expected_columns
    and register_identity == master_identity
    and not duplicate_assessment.any()
    and odd_assessment["ISIN"].str.strip().eq("").all()
)

status = "PASS" if contract_ok and not odd_assessment.empty else "FAIL"

coverage = pd.DataFrame(
    [
        {
            "groupe": "Titres du master",
            "lignes": len(security_master),
            "note": "Une ligne de registre est ouverte pour chacun.",
        },
        {
            "groupe": "Preuves déjà saisies",
            "lignes": int(filled_evidence.sum()),
            "note": "Le code ne remplit pas ces colonnes.",
        },
        {
            "groupe": "Preuves encore vides",
            "lignes": int((~filled_evidence).sum()),
            "note": "À compléter depuis les rapports de SRC-007.",
        },
        {
            "groupe": "ISIN renseigné",
            "lignes": int(odd_assessment["ISIN"].str.strip().ne("").sum()),
            "note": "Le master ne fournit pas d'ISIN.",
        },
    ]
)

display(coverage)
display(
    Markdown(
        f"DS-010 contient **{len(odd_assessment):,} lignes**, "
        f"soit **{len(register_identity)} titres** du master.\n\n"
        f"**Preuves saisies :** {int(filled_evidence.sum()):,} lignes\n\n"
        f"**Statut d'éligibilité vide :** "
        f"{int(odd_assessment['Status'].str.strip().eq('').sum()):,} lignes\n\n"
        f"**Doublons titre / place / ODD :** "
        f"{int(duplicate_assessment.sum()):,}\n\n"
        f"**Résultat : {status}** — le registre est ouvert. "
        "Ce résultat ne juge pas l'éligibilité ODD."
    )
)

                 groupe  lignes                                            note
0      Titres du master     120  Une ligne de registre est ouverte pour chacun.
1  Preuves déjà saisies      25            Le code ne remplit pas ces colonnes.
2  Preuves encore vides      95     À compléter depuis les rapports de SRC-007.
3        ISIN renseigné       0                Le master ne fournit pas d'ISIN.

DS-010 contient **120 lignes**, soit **120 titres** du master.

**Preuves saisies :** 25 lignes

**Statut d'éligibilité vide :** 120 lignes

**Doublons titre / place / ODD :** 0

**Résultat : PASS** — le registre est ouvert. Ce résultat ne juge pas l'éligibilité ODD.

# 15. Logging et traçabilité

## Technical Log

Le Technical Log documente les étapes d’exécution, validations, warnings et erreurs techniques.

In [34]:
if TECHNICAL_LOG.exists():
    with open(TECHNICAL_LOG, "r", encoding="utf-8", errors="ignore") as handle:
        log_lines = handle.readlines()
    print("Technical log lines:", len(log_lines))
    print("".join(log_lines[-20:]))
else:
    print("Technical log not found:", TECHNICAL_LOG)

Technical log lines: 4430
2026-10-15 14:53:55,043 | INFO | Portfolio output monthly_returns written to C:\Users\MameBARBOSAMONTEIRO\projet01\data\04_portfolios\portfolio_monthly_returns.csv (360 rows)
2026-10-15 14:53:55,050 | INFO | Portfolio output membership written to C:\Users\MameBARBOSAMONTEIRO\projet01\data\04_portfolios\portfolio_membership.csv (120 rows)
2026-10-15 14:53:55,051 | INFO | Portfolio construction finished: 83 names, 120 months
2026-10-15 15:02:31,614 | INFO | Source Registry validation started
2026-10-15 15:02:32,136 | INFO | Source Registry sources validated: 11
2026-10-15 15:02:32,136 | INFO | Source Registry datasets validated: 10
2026-10-15 15:02:32,136 | INFO | Source Registry controls executed: 21
2026-10-15 15:02:32,136 | INFO | Source Registry failed controls: 1
2026-10-15 15:02:32,155 | ERROR | Source Registry validation failed: Source Registry validation failed: [{'control_id': 'SR-019', 'control_name': 'Production Method Consistency', 'notes': "Issues: [{'excel_row': 10, 'dataset_id': 'DS-010', 'reason': 'Preparation cannot declare Access Endpoint.'}]"}]
Traceback (most recent call last):
  File "C:\Users\MameBARBOSAMONTEIRO\projet01\src\governance\validate_source_registry.py", line 2915, in validate_source_registry
    raise ValueError(
ValueError: Source Registry validation failed: [{'control_id': 'SR-019', 'control_name': 'Production Method Consistency', 'notes': "Issues: [{'excel_row': 10, 'dataset_id': 'DS-010', 'reason': 'Preparation cannot declare Access Endpoint.'}]"}]
2026-10-15 15:04:38,403 | INFO | Source Registry validation started
2026-10-15 15:04:38,925 | INFO | Source Registry sources validated: 11
2026-10-15 15:04:38,925 | INFO | Source Registry datasets validated: 10
2026-10-15 15:04:38,925 | INFO | Source Registry controls executed: 21
2026-10-15 15:04:38,925 | INFO | Source Registry failed controls: 0
2026-10-15 15:04:38,925 | INFO | Source Registry validation completed successfully
2026-10-15 15:04:38,925 | INFO | Source Registry valid: True

## Acquisition / Preparation Log

La validation du log métier doit s’appuyer sur la table ou le fichier réellement utilisé par `acquisition_logger.py`. Le workbook ne suppose plus l’ancien contrat Excel si le mécanisme courant a évolué.

In [35]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        tables = set(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", connection)["name"])
        if "acquisition_log" in tables:
            acquisition_log = pd.read_sql(
                "SELECT * FROM acquisition_log ORDER BY execution_date DESC LIMIT 30",
                connection,
            )
            display(acquisition_log)
        else:
            print("acquisition_log table not found.")

,run_id,execution_date,process_type,output_file,storage_location,status,records_produced,notes,created_at
0,RUN-20261015-125214-AC6E475E,2026-10-15T12:52:14+00:00,Preparation,chf_portfolio_universe.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\03_universe\eligible,Success,120.0,"{""excluded"": 11, ""included"": 109}",2026-10-15T12:52:14+00:00
1,RUN-20261015-125212-5D4038AF,2026-10-15T12:52:12+00:00,Preparation,macro_indicators.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,2766.0,"{""empty_values"": 2}",2026-10-15T12:52:12+00:00
2,RUN-20261015-125210-091A7E96,2026-10-15T12:52:10+00:00,Preparation,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,213.0,"{""empty_values"": 0, ""rate_currency"": ""CHF"", ""series_id"": ""SARON""}",2026-10-15T12:52:10+00:00
3,RUN-20261015-125209-A86E9D12,2026-10-15T12:52:09+00:00,Preparation,market_price_exclusions.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,60434.0,"{""missing_close"": 1120, ""missing_monthly_fx"": 6922, ""no_snb_series"": 50657, ""outside_high_low"": 1735}",2026-10-15T12:52:09+00:00
4,RUN-20261015-125207-B50D0C28,2026-10-15T12:52:07+00:00,Preparation,market_prices_chf.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,575176.0,"{""excluded_rows"": 60434, ""kept_rows"": 575176, ""reporting_currency"": ""CHF"", ""source_rows"": 635610}",2026-10-15T12:52:07+00:00
5,RUN-20261015-125029-C8093835,2026-10-15T12:50:29+00:00,Acquisition,market_prices.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\market,Success,635610.0,"{""connector"": ""yfinance"", ""dataset_id"": ""DS-004"", ""metadata"": {""end"": null, ""identity_resolution"": {""000895.SZ"": {""d...",2026-10-15T12:50:29+00:00
6,RUN-20261015-124831-39E511EF,2026-10-15T12:48:31+00:00,Preparation,securities_master.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,"{""ambiguous_records"": 11, ""candidate_records"": 120, ""inputs"": [""security_candidates.csv"", ""openfigi_mapping.csv""], ""...",2026-10-15T12:48:31+00:00
7,RUN-20261015-124827-3A90F137,2026-10-15T12:48:27+00:00,Acquisition,openfigi_mapping.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\securities,Success,2000.0,"{""connector"": ""openfigi"", ""dataset_id"": ""DS-002"", ""metadata"": {""http_requests"": 2, ""input_records"": 120, ""mapping_jo...",2026-10-15T12:48:27+00:00
8,RUN-20261015-124820-5A14C04F,2026-10-15T12:48:20+00:00,Preparation,security_candidates.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\securities,Success,120.0,Input=benchmark_holdings.xls; Worksheet=Holdings; HoldingsRows=149; SelectedRows=120; InvalidTickerRejected=0; Missi...,2026-10-15T12:48:20+00:00
9,RUN-20261015-124818-C0B59EC4,2026-10-15T12:48:18+00:00,Acquisition,benchmark_holdings.xls,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\benchmark,Success,NaN,"{""bytes_written"": 1383050, ""content_length"": 1383050, ""content_type"": ""application/vnd.ms-excel"", ""dataset_id"": ""DS-...",2026-10-15T12:48:18+00:00
10,RUN-20261015-122812-42D98F5A,2026-10-15T12:28:12+00:00,Preparation,chf_portfolio_universe.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\03_universe\eligible,Success,120.0,"{""excluded"": 11, ""included"": 109}",2026-10-15T12:28:12+00:00
11,RUN-20261015-122810-530FED41,2026-10-15T12:28:10+00:00,Preparation,macro_indicators.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,2766.0,"{""empty_values"": 2}",2026-10-15T12:28:10+00:00
12,RUN-20261015-122807-A923C6E5,2026-10-15T12:28:07+00:00,Preparation,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,213.0,"{""empty_values"": 0, ""rate_currency"": ""CHF"", ""series_id"": ""SARON""}",2026-10-15T12:28:07+00:00
13,RUN-20261015-122805-C9F85945,2026-10-15T12:28:05+00:00,Preparation,market_price_exclusions.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,59419.0,"{""missing_close"": 1122, ""missing_monthly_fx"": 5973, ""no_snb_series"": 50597, ""outside_high_low"": 1727}",2026-10-15T12:28:05+00:00
14,RUN-20261015-122801-15142AF0,2026-10-15T12:28:01+00:00,Preparation,market_prices_chf.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,575146.0,"{""excluded_rows"": 59419, ""kept_rows"": 575146, ""reporting_currency"": ""CHF"", ""source_rows"": 634565}",2026-10-15T12:28:01+00:00
15,RUN-20261015-122727-248D3726,2026-10-15T12:27:27+00:00,Preparation,quote_currency.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,120.0,"{""currencies_absent"": 2, ""currencies_present"": 118, ""fetched"": 2, ""symbols"": 120}",2026-10-15T12:27:27+00:00
16,RUN-20261015-102437-48694C31,2026-10-15T10:24:37+00:00,Preparation,chf_portfolio_universe.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\03_universe\eligible,Success,120.0,"{""excluded"": 11, ""included"": 109}",2026-10-15T10:24:37+00:00
17,RUN-20261015-102434-190BB488,2026-10-15T10:24:34+00:00,Preparation,macro_indicators.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,2766.0,"{""empty_values"": 2}",2026-10-15T10:24:34+00:00
18,RUN-20261015-102431-101304A0,2026-10-15T10:24:31+00:00,Preparation,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,213.0,"{""empty_values"": 0, ""rate_currency"": ""CHF"", ""series_id"": ""SARON""}",2026-10-15T10:24:31+00:00
19,RUN-20261015-102428-B6E67768,2026-10-15T10:24:28+00:00,Preparation,market_price_exclusions.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,59419.0,"{""missing_close"": 1122, ""missing_monthly_fx"": 5973, ""no_snb_series"": 50597, ""outside_high_low"": 1727}",2026-10-15T10:24:28+00:00
20,RUN-20261015-102426-4A021559,2026-10-15T10:24:26+00:00,Preparation,market_prices_chf.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,575146.0,"{""excluded_rows"": 59419, ""kept_rows"": 575146, ""reporting_currency"": ""CHF"", ""source_rows"": 634565}",2026-10-15T10:24:26+00:00
21,RUN-20261015-101204-77D064AA,2026-10-15T10:12:04+00:00,Preparation,chf_portfolio_universe.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\03_universe\eligible,Success,120.0,"{""excluded"": 11, ""included"": 109}",2026-10-15T10:12:04+00:00
22,RUN-20261015-101201-EE56E402,2026-10-15T10:12:01+00:00,Preparation,macro_indicators.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,2766.0,"{""empty_values"": 2}",2026-10-15T10:12:01+00:00
23,RUN-20261015-101158-62545A7A,2026-10-15T10:11:58+00:00,Preparation,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,213.0,"{""empty_values"": 0, ""rate_currency"": ""CHF"", ""series_id"": ""SARON""}",2026-10-15T10:11:58+00:00
24,RUN-20261015-101153-EA51152E,2026-10-15T10:11:53+00:00,Preparation,market_price_exclusions.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,59419.0,"{""missing_close"": 1122, ""missing_monthly_fx"": 5973, ""no_snb_series"": 50597, ""outside_high_low"": 1727}",2026-10-15T10:11:53+00:00
25,RUN-20261015-101150-26C49D14,2026-10-15T10:11:50+00:00,Preparation,market_prices_chf.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\market,Success,575146.0,"{""excluded_rows"": 59419, ""kept_rows"": 575146, ""reporting_currency"": ""CHF"", ""source_rows"": 634565}",2026-10-15T10:11:50+00:00
26,RUN-20261015-100926-2D51E4DA,2026-10-15T10:09:26+00:00,Acquisition,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\macro,Success,213.0,"{""connector"": ""snb"", ""dataset_id"": ""DS-011"", ""metadata"": {""cube_id"": ""zimoma"", ""dim_sel"": ""D0(SARON)"", ""edition_date...",2026-10-15T10:09:26+00:00
27,RUN-20261015-100831-2FF0C1C5,2026-10-15T10:08:31+00:00,Acquisition,saron.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\01_raw\macro,Success,13.0,"{""connector"": ""snb"", ""dataset_id"": ""DS-011"", ""metadata"": {""cube_id"": ""zimoma"", ""dim_sel"": ""D0(SARON)"", ""edition_date...",2026-10-15T10:08:31+00:00
28,RUN-20261015-094618-C996D92A,2026-10-15T09:46:18+00:00,Preparation,chf_portfolio_universe.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\03_universe\eligible,Success,120.0,"{""excluded"": 11, ""included"": 109}",2026-10-15T09:46:18+00:00
29,RUN-20261015-094615-97559182,2026-10-15T09:46:15+00:00,Preparation,macro_indicators.csv,C:\Users\MameBARBOSAMONTEIRO\projet01\data\02_processed\macro,Success,2766.0,"{""empty_values"": 2}",2026-10-15T09:46:15+00:00

# 16. Database – état courant

Le chargement SQLite est une étape distincte de l’acquisition. Ce contrôle inventorie les tables réellement disponibles sans exiger des tables historiques supprimées par le refactoring.

In [36]:
if DATABASE_FILE.exists():
    with sqlite3.connect(DATABASE_FILE) as connection:
        database_tables = pd.read_sql(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name",
            connection,
        )
    database_tables
else:
    print("Database not found.")

# 17. Couverture globale de la Phase 3

Ce tableau est mis à jour à mesure que chaque source est définitivement validée.

In [37]:
phase3_status = pd.DataFrame([
    {"Source": "SRC-001", "Dataset": "DS-000", "Domain": "Benchmark", "Status": "VALIDATED"},
    {"Source": "SRC-002", "Dataset": "DS-002", "Domain": "Security identifiers", "Status": "VALIDATED"},
    {"Source": "SRC-003B", "Dataset": "DS-004", "Domain": "Market", "Status": "VALIDATED"},
    {"Source": "SRC-004A", "Dataset": "DS-008", "Domain": "Fundamentals", "Status": "VALIDATED / COVERAGE INCOMPLETE"},
    {"Source": "SRC-004B+", "Dataset": "TBD", "Domain": "Fundamentals", "Status": "REQUIRED"},
    {"Source": "SRC-005A", "Dataset": "DS-006", "Domain": "Macro", "Status": "VALIDATED"},
    {"Source": "SRC-005B", "Dataset": "TBD", "Domain": "Macro", "Status": "TO BUILD"},
    {"Source": "SRC-005C", "Dataset": "TBD", "Domain": "Macro", "Status": "TO BUILD"},
    {"Source": "SRC-006A", "Dataset": "DS-009 / DS-011", "Domain": "FX / CHF rate", "Status": "VALIDATED"},
    {"Source": "SRC-007", "Dataset": "DS-010", "Domain": "ODD", "Status": "REGISTER READY"},
    {"Source": "SRC-008", "Dataset": "TBD", "Domain": "Exclusions", "Status": "TO BUILD"},
])
phase3_status

       Source          Dataset                Domain                           Status
0     SRC-001           DS-000             Benchmark                        VALIDATED
1     SRC-002           DS-002  Security identifiers                        VALIDATED
2    SRC-003B           DS-004                Market                        VALIDATED
3    SRC-004A           DS-008          Fundamentals  VALIDATED / COVERAGE INCOMPLETE
4   SRC-004B+              TBD          Fundamentals                         REQUIRED
5    SRC-005A           DS-006                 Macro                        VALIDATED
6    SRC-005B              TBD                 Macro                         TO BUILD
7    SRC-005C              TBD                 Macro                         TO BUILD
8    SRC-006A  DS-009 / DS-011         FX / CHF rate                        VALIDATED
9     SRC-007           DS-010                   ODD                   REGISTER READY
10    SRC-008              TBD            Exclusions                         TO BUILD

# 1. Critères de clôture de la Phase 3

La Phase 3 sera considérée comme terminée lorsque :

1. toutes les sources nécessaires du Source Registry disposent d’un contrat Dataset exploitable ;
2. chaque source automatisable possède un connector ou une méthode Download fonctionnelle ;
3. les acquisitions RAW sont produites et validées ;
4. les sources de backup nécessaires sont construites jusqu’à atteindre une couverture suffisante ;
5. les dépendances et la lineage sont validées ;
6. les runs sont traçables ;
7. les datasets destinés à SQLite disposent d’un contrat de chargement ;
8. les exceptions connues sont documentées ;
9. aucune nouvelle source n’est ajoutée lorsqu’elle n’apporte plus de couverture utile.

# Conclusion actuelle

Les acquisitions SRC-001, SRC-002 et SRC-004A sont techniquement validées dans l’architecture actuelle.

Le pipeline `DS-000 → DS-001 → DS-002 → DS-003` fournit la base de lineage des instruments. SRC-004A / DS-008 ajoute une première couche Fundamentals RAW structurée via SEC EDGAR, avec 32 securities couvertes sur 120 et 586 809 faits XBRL acquis.

La couverture Fundamentals reste insuffisante et nécessite au moins une source supplémentaire. Les cours de marché viennent de Yahoo Finance, `DS-004`. L'orchestrateur `python -m src.pipeline.refresh` reprend chaque jeu actif selon sa fréquence dans le registre.

Le workbook doit continuer à être enrichi source par source jusqu’à satisfaire les critères de clôture de la Phase 3.