In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

import pandas as pd
import sqlite3

from src.config import DATABASE_FILE

from src.quality.quality_checks import (
    load_quality_enabled_datasets,
    run_quality_checks,
)

from src.quality.quality_metrics import (
    calculate_quality_metrics,
)

# Phase 4 - Data Quality Framework

## Objectif

L'objectif de cette phase est de mettre en place un framework de contrôle
qualité permettant d'évaluer la fiabilité des données intégrées dans la
plateforme d'investissement.

La qualité des données constitue un élément fondamental dans les institutions
financières. Une donnée incorrecte peut conduire à :

- une analyse erronée ;
- une décision d'investissement inappropriée ;
- une perte financière ;
- un risque opérationnel ;
- un risque de conformité.

Cette phase introduit un modèle de contrôle qualité standardisé,
intégrable à tout nouveau dataset chargé dans la plateforme.

## Architecture du Framework

Le framework qualité repose sur quatre composants principaux :

1. dataset_registry
2. quality_checks.py
3. quality_metrics.py
4. data_control_center.py

Flux de traitement :

Source Registry
↓
Database Loader
↓
SQLite Database
↓
Dataset Registry
↓
Quality Checks
↓
Quality Metrics
↓
Data Control Center

## Datasets soumis au contrôle qualité

Le framework identifie automatiquement les datasets dont :

- active = 1
- quality_enabled = 1

Les règles qualité sont donc pilotées par le Dataset Registry
et non par des noms de tables codés en dur.

In [2]:
connection = sqlite3.connect(
    DATABASE_FILE
)

datasets = load_quality_enabled_datasets(
    connection
)

datasets

  dataset_id source_id         table_name  chronology_enabled
0     DS-002   SRC-002   openfigi_mapping                   0
1     DS-003   SRC-002  securities_master                   0
2     DS-004  SRC-003B      market_prices                   1
3     DS-006  SRC-005A   macro_indicators                   1
4     DS-008  SRC-004A   fundamentals_sec                   1
5     DS-009  SRC-006A           fx_rates                   1
6     DS-011  SRC-006A              saron                   1

## Contrôles implémentés

Les contrôles suivent le brief de la phase 4. Chaque jeu dont `quality_enabled = 1` reçoit les six contrôles. Un contrôle sans objet sur la table reçoit le statut `NOT_APPLICABLE` et sort du score.

QC-001 Valeurs manquantes

Compte les lignes dont un champ obligatoire est vide. Le point de FRED `.` est une valeur manquante. Sur le master, le FIGI n'est obligatoire que pour un titre `RESOLVED`.

QC-002 Doublons

Détecte les doublons sur la clé métier : titre et place, symbole et date, série et date.

QC-003 Valeurs aberrantes

Repère un cours négatif ou hors de sa fourchette high-low, un taux de change nul ou négatif, et un indicateur macro hors de son intervalle.

QC-004 Formats incorrects

Vérifie le format ISO des devises, le format FIGI lorsqu'il est présent, et le caractère numérique des valeurs fondamentales.

QC-005 Cohérence des devises

Vérifie que la devise de cotation correspond à la place. Un titre qui n'est pas déjà en CHF doit avoir une série de change cotée en CHF. La devise de benchmark du master peut différer de la devise de cotation.

QC-006 Chronologie

Lorsque le registre active la chronologie, les dates doivent se lire et ne pas être postérieures à la date du contrôle. Pour les fondamentaux, une date de début renseignée ne peut pas dépasser la date de fin.

In [3]:
from src.quality.quality_checks import (
    run_quality_checks,
)

controls = run_quality_checks()

controls

,dataset_id,source_id,table_name,control_id,control_name,status,issues,records_checked,execution_date,notes,applicable
0,DS-002,SRC-002,openfigi_mapping,QC-001,Valeurs manquantes,WARNING,9,1992,2026-10-15 12:26:15,9 ligne(s) ont au moins un champ obligatoire v...,1
1,DS-002,SRC-002,openfigi_mapping,QC-002,Doublons,PASS,0,1992,2026-10-15 12:26:15,"Aucun doublon sur la clé input_position, resul...",1
2,DS-002,SRC-002,openfigi_mapping,QC-003,Valeurs aberrantes,NOT_APPLICABLE,0,1992,2026-10-15 12:26:15,Pas de mesure numérique contrôlée sur cette ta...,0
3,DS-002,SRC-002,openfigi_mapping,QC-004,Formats incorrects,PASS,0,1992,2026-10-15 12:26:15,Les identifiants contrôlés respectent leur for...,1
4,DS-002,SRC-002,openfigi_mapping,QC-005,Cohérence des devises,NOT_APPLICABLE,0,1992,2026-10-15 12:26:15,Cette table ne porte pas de devise à rapprocher.,0
5,DS-002,SRC-002,openfigi_mapping,QC-006,Chronologie,NOT_APPLICABLE,0,1992,2026-10-15 12:26:15,Chronologie désactivée pour ce jeu.,0
6,DS-003,SRC-002,securities_master,QC-001,Valeurs manquantes,PASS,0,120,2026-10-15 12:26:15,Les champs obligatoires sont renseignés.,1
7,DS-003,SRC-002,securities_master,QC-002,Doublons,PASS,0,120,2026-10-15 12:26:15,"Aucun doublon sur la clé ticker, exchange.",1
8,DS-003,SRC-002,securities_master,QC-003,Valeurs aberrantes,NOT_APPLICABLE,0,120,2026-10-15 12:26:15,Pas de mesure numérique contrôlée sur cette ta...,0
9,DS-003,SRC-002,securities_master,QC-004,Formats incorrects,PASS,0,120,2026-10-15 12:26:15,Les identifiants contrôlés respectent leur for...,1
10,DS-003,SRC-002,securities_master,QC-005,Cohérence des devises,WARNING,11,120,2026-10-15 12:26:15,"11 titre(s) sans série de change : ILS, INR, S...",1
11,DS-003,SRC-002,securities_master,QC-006,Chronologie,NOT_APPLICABLE,0,120,2026-10-15 12:26:15,Chronologie désactivée pour ce jeu.,0
12,DS-004,SRC-003B,market_prices,QC-001,Valeurs manquantes,WARNING,1122,634565,2026-10-15 12:26:15,1122 ligne(s) ont au moins un champ obligatoir...,1
13,DS-004,SRC-003B,market_prices,QC-002,Doublons,PASS,0,634565,2026-10-15 12:26:15,"Aucun doublon sur la clé symbol, timestamp.",1
14,DS-004,SRC-003B,market_prices,QC-003,Valeurs aberrantes,WARNING,1727,634565,2026-10-15 12:26:15,1727 barre(s) ont un cours négatif ou hors de ...,1
15,DS-004,SRC-003B,market_prices,QC-004,Formats incorrects,NOT_APPLICABLE,0,634565,2026-10-15 12:26:15,Aucun format d'identifiant à contrôler sur cet...,0
16,DS-004,SRC-003B,market_prices,QC-005,Cohérence des devises,NOT_APPLICABLE,0,634565,2026-10-15 12:26:15,Cette table ne porte pas de devise à rapprocher.,0
17,DS-004,SRC-003B,market_prices,QC-006,Chronologie,PASS,0,634565,2026-10-15 12:26:15,Les dates se lisent et ne sont pas postérieure...,1
18,DS-006,SRC-005A,macro_indicators,QC-001,Valeurs manquantes,WARNING,2,2766,2026-10-15 12:26:15,2 ligne(s) ont au moins un champ obligatoire v...,1
19,DS-006,SRC-005A,macro_indicators,QC-002,Doublons,PASS,0,2766,2026-10-15 12:26:15,"Aucun doublon sur la clé series_id, date.",1
20,DS-006,SRC-005A,macro_indicators,QC-003,Valeurs aberrantes,PASS,0,2766,2026-10-15 12:26:15,Les indicateurs macro renseignés restent dans ...,1
21,DS-006,SRC-005A,macro_indicators,QC-004,Formats incorrects,NOT_APPLICABLE,0,2766,2026-10-15 12:26:15,Aucun format d'identifiant à contrôler sur cet...,0
22,DS-006,SRC-005A,macro_indicators,QC-005,Cohérence des devises,NOT_APPLICABLE,0,2766,2026-10-15 12:26:15,Cette table ne porte pas de devise à rapprocher.,0
23,DS-006,SRC-005A,macro_indicators,QC-006,Chronologie,PASS,0,2766,2026-10-15 12:26:15,Les dates se lisent et ne sont pas postérieure...,1
24,DS-008,SRC-004A,fundamentals_sec,QC-001,Valeurs manquantes,PASS,0,494279,2026-10-15 12:26:15,Les champs obligatoires sont renseignés.,1
25,DS-008,SRC-004A,fundamentals_sec,QC-002,Doublons,PASS,0,494279,2026-10-15 12:26:15,"Aucun doublon sur la clé cik, concept, unit, s...",1
26,DS-008,SRC-004A,fundamentals_sec,QC-003,Valeurs aberrantes,NOT_APPLICABLE,0,494279,2026-10-15 12:26:15,Pas de mesure numérique contrôlée sur cette ta...,0
27,DS-008,SRC-004A,fundamentals_sec,QC-004,Formats incorrects,PASS,0,494279,2026-10-15 12:26:15,Les identifiants contrôlés respectent leur for...,1
28,DS-008,SRC-004A,fundamentals_sec,QC-005,Cohérence des devises,NOT_APPLICABLE,0,494279,2026-10-15 12:26:15,Cette table ne porte pas de devise à rapprocher.,0
29,DS-008,SRC-004A,fundamentals_sec,QC-006,Chronologie,PASS,0,494279,2026-10-15 12:26:15,Les dates se lisent et ne sont pas postérieure...,1
30,DS-009,SRC-006A,fx_rates,QC-001,Valeurs manquantes,PASS,0,7563,2026-10-15 12:26:15,Les champs obligatoires sont renseignés.,1
31,DS-009,SRC-006A,fx_rates,QC-002,Doublons,PASS,0,7563,2026-10-15 12:26:15,"Aucun doublon sur la clé series_key, date.",1
32,DS-009,SRC-006A,fx_rates,QC-003,Valeurs aberrantes,PASS,0,7563,2026-10-15 12:26:15,Tous les taux de change renseignés sont strict...,1
33,DS-009,SRC-006A,fx_rates,QC-004,Formats incorrects,NOT_APPLICABLE,0,7563,2026-10-15 12:26:15,Aucun format d'identifiant à contrôler sur cet...,0
34,DS-009,SRC-006A,fx_rates,QC-005,Cohérence des devises,PASS,0,7563,2026-10-15 12:26:15,"Les séries sont cotées en CHF, avec un code de...",1
35,DS-009,SRC-006A,fx_rates,QC-006,Chronologie,PASS,0,7563,2026-10-15 12:26:15,Les dates se lisent et ne sont pas postérieure...,1
36,DS-011,SRC-006A,saron,QC-001,Valeurs manquantes,PASS,0,213,2026-10-15 12:26:15,Les champs obligatoires sont renseignés.,1
37,DS-011,SRC-006A,saron,QC-002,Doublons,PASS,0,213,2026-10-15 12:26:15,"Aucun doublon sur la clé series_key, date.",1
38,DS-011,SRC-006A,saron,QC-003,Valeurs aberrantes,PASS,0,213,2026-10-15 12:26:15,Le SARON renseigné reste dans l'intervalle -5 ...,1
39,DS-011,SRC-006A,saron,QC-004,Formats incorrects,NOT_APPLICABLE,0,213,2026-10-15 12:26:15,Aucun format d'identifiant à contrôler sur cet...,0
40,DS-011,SRC-006A,saron,QC-005,Cohérence des devises,PASS,0,213,2026-10-15 12:26:15,"Le SARON est publié en CHF, en pourcentage.",1
41,DS-011,SRC-006A,saron,QC-006,Chronologie,PASS,0,213,2026-10-15 12:26:15,Les dates se lisent et ne sont pas postérieure...,1

## KPI calculés

Le framework produit un taux par contrôle, puis un score par jeu :

- Valeurs manquantes
- Doublons
- Valeurs aberrantes
- Formats incorrects
- Cohérence des devises
- Chronologie
- Score du jeu
- Note
- Statut

Le score global est la moyenne non pondérée des jeux.

## Modèle de scoring

Chaque contrôle applicable produit un taux : la part des lignes sans anomalie.

- aucune anomalie : PASS
- au moins une anomalie et un taux d'au moins 80 : WARNING
- taux inférieur à 80, ou table vide : FAIL

Le score d'un jeu est la moyenne de ses contrôles applicables. Le score global est la moyenne des jeux. Un jeu d'un million de lignes ne pèse pas plus que le master.

La note suit le score : A à partir de 97, B à partir de 90, C à partir de 80, sinon D. Le statut global est le moins bon statut de jeu. Une note A peut donc coexister avec un statut WARNING : le score est élevé, et des anomalies restent visibles dans le rapport.

In [4]:
quality_results = calculate_quality_metrics(
    controls
)

quality_results["dataset_metrics"]

,dataset_id,source_id,table_name,records_checked,dataset_quality_score,dataset_quality_grade,dataset_quality_status
0,DS-002,SRC-002,openfigi_mapping,1992,99.85,A,WARNING
1,DS-003,SRC-002,securities_master,120,97.71,A,WARNING
2,DS-004,SRC-003B,market_prices,634565,99.89,A,WARNING
3,DS-006,SRC-005A,macro_indicators,2766,99.98,A,WARNING
4,DS-008,SRC-004A,fundamentals_sec,494279,100.00,A,PASS
5,DS-009,SRC-006A,fx_rates,7563,100.00,A,PASS
6,DS-011,SRC-006A,saron,213,100.00,A,PASS

In [5]:
print(
    "Score:",
    quality_results[
        "global_quality_score"
    ]
)

print(
    "Grade:",
    quality_results[
        "global_quality_grade"
    ]
)

print(
    "Status:",
    quality_results[
        "global_quality_status"
    ]
)

Score: 99.63
Grade: A
Status: WARNING

## Champs non applicables

Un contrôle qui n'a pas d'objet sur une table n'entre pas dans le score. Exemples :

- la chronologie est désactivée pour le master et pour OpenFIGI ;
- les valeurs aberrantes ne s'appliquent pas à un référentiel d'identifiants ;
- la cohérence des devises s'applique au master et aux changes.

Les cellules volontairement vides du registre ODD ne sont pas notées : DS-010 a `quality_enabled = 0`. Les relancer dans un contrôle de valeurs manquantes les ferait échouer pour une raison de méthode.

Le point `.` publié par FRED est compté comme une valeur manquante, pas comme un format incorrect.

## Livrables

Le framework produit le rapport, les KPI et le dashboard.

Le rapport qualité est la feuille `Quality Controls` de `audit/data_control_center.xlsx`, complétée par `Quality Issues` pour les anomalies. Les mêmes lignes sont conservées dans `quality_control_result`.

Les KPI sont les six taux, le score, la note et le statut. Ils sont dans la feuille `Quality Dashboard` et dans `quality_metric_result`.

Le dashboard est le classeur `audit/data_control_center.xlsx` :

- Quality Dashboard
- Quality Controls
- Quality Issues
- Quality History

Les graphiques sont placés sous les tableaux. Le titre et les titres d'axes sont hors du tracé.

La commande du dashboard est :

```text
python -m src.quality.data_control_center
```

Les séries traitées sont un livrable distinct, publié par `python -m src.preparation.quality_treatment`. Elles sont décrites dans la section suivante. Leur vérification est dans `tests/quality/phase_04_validation.ipynb`.

## Traitement des anomalies

Le rapport qualité constate les écarts. Il ne réécrit pas les fichiers bruts. Un seul passage de préparation publie les séries que les phases suivantes partagent, afin que les trois portefeuilles, le suivi, la performance, le risque et les stress tests utilisent les mêmes rendements en CHF.

La commande est :

```text
python -m src.preparation.quality_treatment
```

Les règles sont les suivantes.

- Une barre de cours est écartée lorsque le close est absent, lorsqu'un prix ou le volume est négatif, ou lorsque l'open ou le close sort de la fourchette high-low au-delà de la tolérance du contrôle des valeurs aberrantes. Elle n'est pas remplacée par le close précédent. Le motif est écrit dans `data/02_processed/market/market_price_exclusions.csv`.
- Le close conservé est converti en CHF avec le taux SNB du mois du cours. Une cotation SNB publiée pour 100 unités est ramenée à une unité. Une place en CHF n'a pas besoin de taux. Un mois sans taux est écarté, sans interpolation.
- L'échelle du cours vient de la devise que Yahoo publie pour le symbole, dans `data/02_processed/market/quote_currency.csv`. Un code égal à la devise de cotation laisse le close inchangé. `GBp`, `ZAc` et `ILA` sont les unités mineures publiées par Yahoo pour la livre, le rand et le shekel : le close est alors divisé par 100. L'échelle reste dans `quote_scale`. Un autre code, ou une devise absente, écarte la barre au lieu de deviner l'échelle.
- Le point `.` publié par FRED devient une cellule vide dans `data/02_processed/macro/macro_indicators.csv`. La date est conservée.
- Le taux du Trésor américain `DGS3MO` a été retiré du registre, de la base et des fichiers traités. Le seul taux sans risque est le SARON.
- Le taux sans risque en CHF est le SARON publié par la BNS, cube `zimoma`, série mensuelle depuis janvier 2009. Le fichier traité est `data/02_processed/macro/saron.csv`, avec `rate_currency` égal à CHF. C'est un taux au jour le jour, en pourcentage. C'est lui que le Sharpe utilisera.
- L'univers éligible en CHF est le master moins les cotations dont la devise n'a pas de série SNB. Le fichier est `data/03_universe/eligible/chf_portfolio_universe.csv`. Aucun FIGI, aucun change croisé, aucune ligne obligataire et aucune ligne ETF n'est ajouté.

Les fichiers de `data/01_raw` ne sont pas modifiés. La vérification de ces fichiers est dans `tests/quality`, pas dans ce notebook.

In [6]:
from src.config import (
    ELIGIBLE_UNIVERSE,
    PROCESSED_MACRO,
    PROCESSED_MARKET,
)

prices = pd.read_csv(PROCESSED_MARKET / "market_prices_chf.csv")
exclusions = pd.read_csv(
    PROCESSED_MARKET / "market_price_exclusions.csv",
    dtype=str,
    keep_default_na=False,
)
saron = pd.read_csv(PROCESSED_MACRO / "saron.csv")
macro = pd.read_csv(PROCESSED_MACRO / "macro_indicators.csv")
universe = pd.read_csv(
    ELIGIBLE_UNIVERSE / "chf_portfolio_universe.csv",
    dtype=str,
    keep_default_na=False,
)

print(f"Cours conservés : {len(prices):,}".replace(",", " "))
print("Barres écartées :")
print(exclusions["reason"].value_counts().to_string())
print()
print("Univers CHF :")
print(universe["chf_status"].value_counts().to_string())
print(
    "Devises sans série SNB :",
    sorted(universe.loc[universe["chf_status"].eq("excluded"), "listing_currency"].unique()),
)
print(f"SARON : {len(saron):,} observations".replace(",", " ") + f" ; devise : {saron['rate_currency'].unique().tolist()}")
print(f"Indicateurs macro vides : {int(macro['value'].isna().sum())}")

Cours conservés : 575 146
Barres écartées :
reason
no_snb_series         50597
missing_monthly_fx     5973
outside_high_low       1727
missing_close          1122

Univers CHF :
chf_status
included    109
excluded     11
Devises sans série SNB : ['ILS', 'INR', 'SAR', 'TWD']
SARON : 213 observations ; devise : ['CHF']
Indicateurs macro vides : 2

## Conclusion

La phase 4 contrôle les jeux activés dans le registre, avec les six contrôles demandés, puis publie les séries traitées que les phases suivantes utiliseront.

Le score ne dépend plus d'une seule table, ni d'une fraîcheur fixée à 100. Une anomalie reste visible dans le rapport même lorsque le taux du jeu reste élevé. Le statut global retient le moins bon jeu, afin qu'une note élevée ne masque pas les écarts.

Les fichiers bruts restent la source. Le traitement écarte les barres inutilisables, convertit les closes conservés en CHF et laisse vides les points FRED, sans inventer un cours, un taux ou un identifiant.

## Suites possibles

- Règles d'aberration propres à d'autres concepts comptables
- Fraîcheur mesurée à partir de `last_acquisition_date` une fois cette date alimentée par le chargement
- Les cours de marché contrôlés sont ceux de Yahoo, DS-004.